#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 001

  まだ主人公に腕があった頃。

  北の大陸が血の嵐に閉ざされてからしばらく経った。そこで調査隊が派遣されたものの帰ってこない。連絡も途絶えたままだというので，後発隊が組織されることになった。とはいうものの，予算も人員も限られているので，各々が足りない分は自力で補充し，現地集合ということになった。ひどい話である。

  仕方がないので，主人公は町の戦士斡旋所に向かい，相性の良さそうな者がいれば，護衛，もしくは調査補助として雇うつもりであった。すると，こちらの思惑を見透かしたかのような人物に会った。屈強な戦士が酒をくみかわすテーブルが並ぶなか，部屋の隅にある暗がりで，その人物は座ってひとり本を読みつづけている。大きなふたつの三つ編みは床まで届くほど長く，よく手入れされていた。

  「君からは人間のにおいがする」，とその人物に話しかけた。この発言からわかるように，この主人公なる者はまともではない。もとよりまともな性格であれば，調査隊が消息を絶った場所へ向かうこともないのだが。まあそれはいい。相手はぶ厚い眼鏡をかけたその顔を上げた。無言だった。「少し待っていてくれ。今手続きをしてくるから」そう言って主人公は酒場もとい斡旋所のカウンターへと向かった。

  1E50C。雇用にかかる費用だった。「なにかの間違いでは」と主人公は受付に言い，マスターを呼ぶようお願いした。1E50Cというのがどれくらいの金額か，たとえるのは難しい。というのも，仮に昼食一回分，としても，人によっては立食い蕎麦で済ませるものもあれば，友達と贅沢なランチをとるものもおり，財産の程度によって捉え方が変わってしまうからである。まあ，とてつもなく安い，ということにしてほしい。

  「あのこはちょっと変わった子なんでね。」とマスターは言った。「先代までの雇い主が書いたメモもあるよ。いる？」

  メモの束は50Eだった。つまりはちゃんと扱うには51E50Cの資金が必要だということだ。しかも契約書にサインするまではメモの中身を見せてもらえないという。かなりワケ有りのようだ。だが主人公は自身のカンを信じ，契約書にサインした。どうしても確認しておきたいことがあったのだ。

  実際にはメモは役立たずであった。言語も多様なら表現も自由。しかも複写した人物が雑に仕事をしたせいで元の文字が何なのかさえわからないものもある。何より主人公は学が全くないわけではないのだが字が読めない。返品はきかないので，失った50Eをうらめしく思いながらも，例の変わった子のテーブルについた。

  「本を読んでいるところ申し訳ないのだが，少し話を聞いてほしい。」相手は顔を上げると本を閉じ，わきに置いた。「私はアルジ。北大陸の調査隊だ。君に私の護衛をお願いしたい」

  「はい」それは即答だったのか，相槌だったのかは判然としない。おそらく後者だろうが，アルジと名乗る主人公はそのまま具体的な話に入った。

  通常，戦士を雇う場合，面接のような手続きを経てから雇用するか決めるものなのだが，アルジは雇ってから面接をするという逆の方法をとった。それだけ相手に何か感じるものがあったのかもしれないが，それで50Eをみすみす捨て去ることになったのだから，無計画な人物であることは間違いないだろう。しかも初対面の相手にむかって「君からは人間のにおいがする」，である。先のマスターはこの眼鏡をかけた三つ編みの人物を変わった子，と言ったが，アルジの場合は，変わった，を通り越して寒気がするほどの気持ち悪さである。一刻も早くこの地上から消滅していただきたいところだが，残念ながらその身体が裂けるのはしばらく先である。読者の皆さんはそのときに「ざまあみろ」と思っていただきたい。

  「ところでここのマスターに渡されたメモにも君の名前が書いてないんだけど，何ていうの」失礼な言い方で，しかも嘘である。だが相手は気にせず

  「ケライです」と名乗った。

  雇い主がアルジで雇われた者がケライ，なんて都合のいい話はない。事実，この二人には本来の名前がある。だが，ただでさえカタカナ語の氾濫する現代においてこの二人の本名をここで出して何になろう。名前というのは元来忘れやすいのだから，物語のなかだけでもテキトーに済ませたいものだ。とまあ，こんな無駄話をしているあいだに二人の会話は終わったようだ。アルジはこれまでの準備に手間取ってしまったためか，他の調査隊メンバーよりも出立するのがずいぶんと遅れてしまっていた。ゆえに，今晩宿をとり，明日の朝に北大陸行きの獣車を手配することにした。

  <br>
  <br>
  (c) 2017 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
