#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 002

  北の空に流星が見えるとき，それは不吉の予兆である。

  といった言い伝えは多くの地域でみられる。この世界においてもそれは例外ではないのだが，あえていうならば，その流星は紫の光を帯びていた。

  二人を乗せた獣車は北への道を進んでいた。獣車は毛むくじゃらで温厚なダモスという家畜を利用した移動および輸送手段である。ダモスは鈍重だが力が強いので，荷車を引きながら進むのに都合がよい。速度はいまいちではあるが，安価で多くの荷物が運べるため，この世界では一般的な乗り物として広く用いられている。アルジは獣車を運転手ごと雇い，朝方に街を出たのだ。とまあ，こんなどうでもいい話をするのにはわけがある。

  荷車のなかで，アルジとケライは互いに向かいあったまま無言であった。寝ているわけでもないのに，知り合い同士が言葉を交わさないのは気まずいので，獣車がどうの，という話でお茶を濁したわけだ。そもそもはケライの声が小さいので，アルジは隣に座ろうと思っていたのだが断られたのである。では嫌われているのかというとそうでもない。話しかければすぐに「はい」「いいえ」「わかりません」のいずれかで返事をする。ケライの気をひくような話の種を持たないアルジのほうに原因があろう。まあ人並の話芸を持っていれば，こんな旅路を進むこともなかったのだが。

  後発隊というと聞こえはいいが，実のところは島流しに近い。というか，人のいる場所ではいいかげん暮らせなくなってしまった者が，北の大陸に住処を求めた結果が調査隊という組織の起こりである。先の調査隊が消息を絶ったというのも，あまりにも居心地が良く連絡する気さえ起きなくなったから，という可能性もある。

  まあおそらくは何かが原因で全滅したのだろうが。

  それを昨晩ケライに伝えたとき，何のためらいも見せなかったのは奇妙ではあったが，というかそんなことには興味がないのだろうが，いずれにせよ何が起きるかわからぬ場所へ向かうわけだから，アルジ自身も明るい気持ちになどなれようもなく，それがつまるところ無言の時間が続く一番の理由である。

  やがて冷気が差してきた。北の地に入ったのである。アルジの知るところによれば，そう遠くないところに調査隊の拠点があるはずだ。日はとうに傾いているものの，空はうすい藍色にすみ渡り，そこから冷気が吐き出されているのではないかと思うほどにどこまでも透き通っていた。

  雲ひとつない空に流星が通った。アルジが目にするのは初めてではあったが，流星とはこんな円を描くようなものだろうか。

  「ち」

  アルジはケライを抱き上げ荷台から飛び降りると，運転手に逃げるよう声を張り上げながら全力で駆けた。直後，鼓膜を突き破るほどの爆音とともに，背後からすさまじい土煙が視界を覆い，石つぶてが背中に当たるのを感じた。どうか頭には当たりませんように，とアルジは祈りながら茶色く染まった世界をひたすらに走った。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2017 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
