#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 006

  二人が乗っているのはオオカミに似た大型の獣である。いまは素直に走ってくれてはいるが，いつ機嫌を損ねるか気が気でない。だがそんなことより，アルジは振り落とされないよう姿勢を維持するだけで精一杯だった。アルジの背中に腕を回すのを嫌がったケライは前に座ったのだが，その背中にアルジの身体が触れるたびにヒジを入れてくるので，上半身に力を込め，獣につながれた綱から手が離れないようきばるしかなかったのだ。

  獣が猛烈な勢いで山をかけあがると，湯気のあがる建物が並ぶのが見えた。期待はしたものの，里とは言ったが，大きな中央の建物を含め，5つほどしかない。

  「シッショ!ジブーがかえってきた!」元気な声が響くとともに，ジブーと呼ばれたこの獣も歩みを止めた。二人が降りると，片手に白い饅頭のようなものを持った人物が駆けてくる。錆びついた大きな首輪をはめていた。この寒さを気にしないかのような薄着で，ヘソも太股も丸出しのまま，怪訝な顔で二人をながめながら手に持ったものをほおばっている。

  「ミミじゃないぞ。おまえだれだ？ミミくったか？」鼻をすんすん鳴らしながら言う。

  「私は調査隊・後発隊のアルジといいます。こちらは助手のケライ。ここへ来る途中で敵に襲われ，ミミさんに助けていただいたんです」

  「アルジ，くさいな。オヤブンとおなじニオイだ。ケライはいいにおいがする」正直である。

  「こら，クビワ。失礼なことを言ったらいけないよ」

  向かいの建物から毛むくじゃらの獣，ではない，小柄で栗毛の獣人がやってきて，クビワと呼ばれる薄着の人物に注意をした。アルジはその獣人にも同じように挨拶をすると，切れ長の目でこちらを見て，自分のことをシッショと名乗った。隣にいる野生児のような人物はクビワといい，シッショの師匠を務めているらしい。

  「へんきょうさいきょうのせんしだ!」紹介されたクビワの威勢のよい返事に，シッショは苦笑いしながら続ける。「随分ひどいめにあったんじゃないかな？泥だらけだね。湯治場があるから，入ってきなよ。ここは温泉が出るんだ」

  「ありがとうございます。でもその前にほかの皆さんに挨拶がしたいのですが」

  聞けばシッショとクビワの他に，ミミを含めたボッチ団とよばれる四人組がいるのだという。そしてラウンジにいるオヤブンと，事務作業や医療活動を担当するショム。それで全部だと伝えられた。わずか八人？後発隊は？いろいろと聞きたいことがあったが，それは親分とやらに尋ねるしかない。

  「オヤブンはこわいぞ。」クビワはにやりとした顔で言った。すぐにシッショがたしなめる。先のクビワの発言といい，不穏な予感を抱きながら，アルジはオヤブンのところへ向かった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
