#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 010

  アルジはケライが先に自分を捕えた得物が釣竿のような武器であると確認すると，可能なかぎり外れないようアルジと糸を結びつけることを依頼した。ケライがアルジの胸に手を回し，回収の際に胴体が切断されないよう，金網を挟んだうえで糸を巻く。

  「私がここを出たら，洞窟の外で待機してくれ。しばらくすると大きな音がするはずだから，そうしたら全力で糸を巻き取ってほしい。できるか」

  「はい」

  ケライの返事を確認するとアルジは洞窟の出口へ向かおうとしたが，ふと何かを思い出し，振り返ると言った。

  「ケライの仕事は私を守ることだと言ったな」「はい」「ではケライが私を守るとはどういうことか，私の解釈をいま言っておく」「はい」

  少しのためらいがあったが，アルジは胸のうちを正直に言うことにした。

  「私はケライが好きだ。ケライと一緒にいると安心する」「はい」返事に少しの遅れがあった。

  「それは自由に動き回る私にとってケライが基地の役割を果たしているからだ。意味はわからないかもしれないが，私がこの世界で危険のある道をえらべるのも，ケライという，帰ってくる場所があるからだ。調査団に対する里のようなもので，ケライという基地があるから，私は安心して自分の選択に自信を持つことができるし，この世界でも自分の思うように冒険できる」「はい」

  「だから，ケライがケライのままでいるだけで私は守られている，どこにいてもケライに守られていると感じることができる。私を守るためにケライの身体を危険に晒さなくても，ケライは十分に仕事を果たしているんだ」

  「どういうことですか」ケライの言うとおりだった。「帰ってきたら詳しく言うよ」

  帰ってこれたら，と言わなかった理由は定かではない。ケライに疑問を残したままアルジは洞窟を出た。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
