#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 012

  そこは静寂に包まれ，アルジの作った赤いしみがあちこちに残っているだけだった。だが確信とともに，肩の鞄を緩め，靴を脱ぐと，全神経を耳と足に傾けた。

  一歩，また一歩。反応はない。

  足を伝わる雪の感触が変わった。ここからやつのテリトリーだ。やつが突き上げるのにかかる時間は瞬きよりも短い。

  「見えるぞ」アルジは呟いた。

  <br>

  見えるぞ!

  <br>

  その大声はケライに届くほどではなかった。だが，その声に反応したわずかな動きから，ターゲットの位置を把握するのには十分であった。それは感覚が研ぎ澄まされ，直接自分の腕を食われたアルジだからこそ可能な戦術だった。

  相手が姿を潜める場所に近付くが，動きはない。これは範囲に入った獲物を突き上げて食らう準備だ。好都合だ。

  アルジは一直線に駆けると，急に角度を変え，飛びのいた。それとともに，肩から鞄が抜け，直後，足の指わずか先の雪面に黄土色の柱がそびえたち，再び雪中に収まった。

  勝った。

  くぐもった轟音とともに桃色のしぶきがあたりに飛び散り，アルジの身体にも降り注ぐ。鞄に仕込んだ爆薬が内部で炸裂したのだ。パニック映画の王道だ。同時に，アルジはしくじったと感じた。背中がくいっと引っぱられる感触をきっかけに，自分の身体がすさまじい勢いで雪面をすべってゆく。それにあわせるように山そのものがもだえるような唸り声を上げ，山の上から白い悪魔が大岩とともに駆け下りてきた。

  アルジは当初，敵を倒し，素材を回収してから，雪崩の音を合図に引き上げてもらう計画をたてていた。だが雪中の浅いところで爆発が起きたのが引き金となり，素材を回収するまえにケライの引き上げ作業が始まってしまったのだ。だがそれは結果的に正しかった。雪崩の速度はアルジが想像するよりもはるかに速く，みるみるうちに雪原は白い霧に覆われ，目の前を大岩が転がり落ちてゆく。まきこまれればひとたまりもないにも関わらず，アルジは

  おもしろいな。

  と，遊園地のアトラクションに乗っているかのような，とはいえこの世界にそんなものはないが，そんな興奮を抱いていた。

  ほんとうは雪崩に巻き込まれ死ぬはずだった。だがケライの幸運な勘違いによって，アルジの命は再びこの世界に留まることになった。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
