#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 013

  安全を知らせる信号弾のあと，勝利を告げるかのように登る太陽とともに，二人は里に帰ってきた。出迎えたメンバーが驚いたのはアルジの変わりはてた姿である。その腕はなく，全身に桃色の液体がへばりついてひどい悪臭を放っている。

  「アルジ，まるのみされたか？」クビワの質問も最もだった。「早く手当てしないと」「傷口の縫合はあとでもよさそうだ。とりあえず身体を洗おう。」ショムの気遣いにシッショがアドバイスをする。「クビワ。手伝ってくれるよね」「いいぞ。あさぶろだな」

  「ええと，それはちょっと」アルジがうろたえる。「大丈夫だよ。クビワは気にしないから」アルジのためらう理由にショムは気付き，苦笑いをした。「アルジ。あさぶろはいいぞ!」クビワに背中を押され，しぶしぶアルジは回収した素材をケライに託し，湯治場へ向かった。その間，ショムはケライを呼び，事情をオヤブンに説明することになった。

  腕には水避けの膜が張られているものの，頭から薬湯がかけられるたび，熱が伝わり激烈な痛みをひきおこした。だが，石鹸で全身をくまなく洗ってもらっている間もアルジはつとめて無心を保とうとした。「アルジ，どうしてずっとめをつぶってる？もうあたまにせっけんついてないぞ。いたくないぞ」「いえ，腕は痛いです」「うでがいたいとめに，めが？めが!めがしみるのか？」「はい，色々と」「うでがいたいとめがしみるのか!ふしぎだな!」その二人の珍妙なやりとりに，シッショは笑いを抑えることができなかった。

  その後3人は並んで湯船につかった。クビワはあおむけのまま器用に浮き，満足気に眠っている。

  「クビワさんは面白い方ですね」「だろ。自分の子供みたいでさ。かわいくてしょうがないんだこれが」

  「私たちと初めて会ったときのこと覚えていますか」「もちろん。二人とも凍死しかけてたっけ」当時を思い出したのかシッショは笑う。それを見てアルジは言葉を続けた。「私はミミさんにもオヤブンさんにも初めて会ったときはいろいろ疑われたんですが」「ん？」「どうしてシッショさんは私が本物の後発隊だとすぐにわかったんですか」

  「どうしても何も」シッショは当たりまえの理由を問われたようで，少し考えた。そして，ジブーに乗ってきたっていうのもあるけど，と前置きしたうえで，「アルジが不器用にみえたからさ」と言った。

  「不器用？」「密偵ならもっとまともな性格をしてるだろう，ってことだよ」その言葉を口にしてから，シッショははっとして自分の非礼をあわてて詫びた。だがアルジは自覚があるので気にしないよう答えた。

  気が緩むとつい本音が漏れちゃうんだよなぁ。そうひとりごとのように言ってから，シッショは遠くを見るような目で「クビワを見てるとさ。不器用でも一生懸命生きてる人見ると応援したくなっちゃうんだ」とつぶやいた。

  「わー!」シッショは突然大声をあげ，二人を驚かせた。さらに「のぼせちゃった。先に出るよ。クビワはアルジの身体を拭いてあげてね」と言いのこして逃げるように先にあがってしまった。

  まずい。「いえ，私ももうあがります」アルジは立ちあがろうとしたが，シッショの声で起きあがったクビワに頭から抑えつけられてしまう。「よいこはひゃくかぞえるまであがっちゃだめだぞ!」

  そのまま動けないよう背後から組みつかれ，100まで数えることになった。暴れて腕を濡らすわけにはいかない。だがクビワの数え方はテキトーだったため，アルジがかわりに全部数えるはめになった。

  その後，ゆでだこ状態となったアルジは，しばらく意識が朦朧としていた。そのおかげもあり，気絶することなく不要な骨の除去と腕の縫合を済ませることができた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
