#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 014

  縫合を終え，ラウンジに戻ると随分とにぎやかな雰囲気だった。ボッチ団が調査から帰ってきたのだ。登場人物が一度に3人も増えてしまった。覚えられるわけがない。そもそもケライに親しそうに抱きついているのは誰だ。そしてそれに関せずもう一人と話すケライの様子は何だ。

  ミミがこちらに気付き，軽く手を振ったが，アルジの変化に気付くと顔を豹変させて駆けよってきた。「おかえりなさい，ミミさん。おかげさまで助かりました」「全然助かってないじゃないですか。どうしたんですかその身体，凍傷にやられたんですか，ハッ!？まさかジブーが!？」「いやいや，違いますって」あわてるミミをなだめ，アルジは事情を説明する。

  「それじゃあ，あんたがアルジさんか。俺はボッチだ」ミミの様子から，ケライとの話を切り上げアルジのところへやってきた人物は自信満々にそう言った。「シンキでーす」ケライにくっついた方は元気に手を挙げる。つまり自信にみちあふれ態度のでかいほうがボッチで，ケライが大好きなのがシンキか。というかそんな覚え方をする必要はない。

  実力の割にプライドが高く，実力の割に，というのは余計だが，とにかく，他者に対する攻撃性が高いせいで仲間が少ないからボッチ。一方育ちは良いが経験が少ないからシンキ。ここにはいないが獣舎でペットの世話をしているのが命をかけて仕事をしないキセイ。というのが互いの会話を通してアルジが抱いた印象をもとに，物語の都合上覚えやすいようにつけた名前である。アルジとケライの由来の際にも述べたが，当然ながらそれが本名ではない。

  そして最初に出会ったときにはフードで気付かなかったが，ミミはウサギのロップイヤー種のような長く垂れた耳を持った獣人族だった。だが全身を毛に覆われたシッショと違い，耳と尾をのぞいて普通の人とほとんど区別はつかない。

  「皆さんごはんいかがですか」シンキが提案した。気配りのできる人物である。ボッチは報告がてらオヤブンやショムと済ませる予定だという。クビワとシッショは打ち合わせがあり，キセイは獣舎で過ごしているので，4人で食事をすることになった。

  そこで困ったのがアルジである。両腕がないので何もできないのだ。「すみませんが机をきれいにしておくので，私の分の食事を持ってきていただけませんか」「いいよーそんなの気にしなくても」シンキが笑顔で答えた。

  例によってケライの席だけはすさまじい量のメニューが並んでいる。「噂には聞いてたけどすごいね。10人分くらいあるんじゃない？」「ですね，ほんと」シンキとミミはその迫力に舌を巻く。だが昨日までと違うのはメニューの色合いが随分鮮やかになっていたことだった。「これ，ㇰ，野菜ですか？」「そうそう!あたし達が収穫してきたの。おいしいといいね」普段から心のなかで悪態をついているアルジは思わず草と言いそうになった。仮にそれを口にしていたら，全ての信用が灰燼に帰すところであった。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
