#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 019
  
  この章では，ストーリーに進展はない。ゆえに，キッチンにこびりついた油汚れのしつこさ，そういったものを嫌う読者は飛ばしてほしい。

  寝息をたてるミミの横で，アルジはこれまでに起きた偶然に感謝するとともに，もう一人の自分が歩んだはずの恐怖も感じていた。

  もしケライと出会わなかったら。あの雪原で出会ったのがミミでなかったら。里で出会ったのがシッショとクビワでなかったら。オヤブンが冷静じゃなかったら。シッショとクビワに足の使い方を教わらなかったら。ケライに報告書の書き方を教わっていなかったら。ボッチ団にミミとシンキがいなかったら。

  ふだんは落ち着いた様子でいても，自分の内で常に獣が暴れ，隙あらば殻を突き破って表に出ようと始終体当たりしていることが調査隊の人々に知れたら。

  いまと違った道を歩み，ばらばらに千切れるたくさんの自分の姿と，それらが部品の欠けた顔でうらめしそうにアルジを見る。いずれは自分もそこに入るのだろうか。いつそこに入るのか。自分の顔がひきさかれる。

  「眠れないんですか」ミミのささやく声にアルジはハッとして現実にひきもどされた。

  「怖いんです」意図せずアルジは声に出してしまっていた。

  ミミは静かに起き上がると，周りを見回してから言った。「みなさん起こさないように，少し外でお話しましょうか」

  <br>
  <br>

  キャンプの外で，一枚の大きな毛布に二人でくるまっていた。寒さを防ぐために顔もほとんど隠れているので，はたから見れば丸い毛玉のようである。

  「時々，自分なんかが生きていていいのかと思うことがあるんです。あのとき自分が代わりに死んでいればよかったんじゃないかと」

  「そんなことないですよ」ミミはそっと抱き寄せる。「私よりつらいめにあっている人は私よりもたくさんいるのに，私だけがこんなにいい思いをしていて良いのか，そんな資格はないともう一人の自分が言うんです」「大丈夫ですよ」「これは全部夢なんじゃないか，逃げるために自分がついている嘘なんじゃないか，あるとき目覚めると全部終わってしまうんじゃないか，そう思うと怖くて」「夢じゃないですよ，安心してください」ミミは悲しそうな顔で抱きしめる。

  「痛くて，つらくて，でももっとつらい人はたくさんいて，そんなのにくらべたら私は全然つらくないはずで，でも，本当に痛いんです，苦しいんです」「うん，うん」頭をこするように大きくうなずく。「そんな駄目な自分をみんな守ってくれるんです，優しいんです，でも自分にそんな価値はないんです」「駄目なんかじゃないですよ，立派ですよ」「こんな駄目な自分なのに，優しくしてもお礼なんかできるわけないのに，みんな優しくしてくれるのが，うれしいのに，つらいと思う自分がいて，そんな自分が本当に嫌なんです」「私たちはじゅうぶんにお礼を受けてますよ，大丈夫ですよ」

  嫌悪の螺旋を落ちつづけようとするその腕をつかみながら，ミミは優しい言葉をかけ続けた。その温もりに小さいアルジは安心したのか，もしくは話し疲れたのか，ようやく眠りにつくことができた。その様子を確認したミミは，二人で肩を寄せあったまま浅い眠りについた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
