#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 023

  キャンプは，数時間前の明るい雰囲気からはかけ離れた陰惨な場所へと姿を変えていた。上半身に包帯を巻き，壁際に腰をおろすボッチ，呆けた表情で座りこむミミ。

  そして，仕切りの向こうからただよう肉の焦げたにおい。一命は取り留めたようだが，それは文字通りの意味でしかなく，余談を許さないことは明らかだった。

  騒然とした様子にキセイは怯え，緊張の糸もとぎれ大声で泣き出してしまった。アルジは膝立ちになり，泣きじゃくるキセイを引き寄せようとしたがはねのけられた。そのままキセイは毛布にもぐりこみ，泣きつづける。

  先ほどまでの緊張あふれる戦闘に，アルジは雪灯籠と戦ったときのような興奮さえおぼえていた。だがそれがいかに異常なことかを目の前の悲劇から思い知らされる。

  「帰還しましょう」アルジが立ち上がって言う。

  「お前が決めるな」部屋の隅から憎しみのこもった声がした。ボッチだった。

  「お前のせいだ。お前が範囲を広げようなんて言わなかったらこんなことにならなかったんだ」アルジは反論するつもりはなかった。下っ端がどんな提案をしようが，許可をしたのはボッチの責任だからだ。だがボッチ団のリーダーとして，数時間で壊滅状態になったこの状況を受け入れることはできなかった。そのためには何かに責任を押しつけられずにはいられなかった。

  「けんかは やめてください」ミミが虚ろな視線のまま，独り言のように言う。

  「一刻も早く帰って，シンキさんの治療をしないと」「だからお前が決めるな!」「やめて!」吠えるボッチに，とうとうミミが決壊してしまった。

  「もうやめて，お願い…」両手で顔を抑え，押し殺すこともできず声をあげて泣く。「どうして？どうして私たちがこんなめにあわなきゃいけないの？どうして…」

  <br>

  「アタシガ ワルイノ」

  どこからかくぐもった，ありえないほど低い声がした。聞き覚えのない声だったが，その主にアルジが気付いたとき，戦慄した。

  「アタシガ モリ ヘ イコウ ナンテ」

  痛々しく，時折空気の漏れるような声が仕切りの向こうから届き，アルジの顔が歪んだ。「もういい。お前は悪くない。」

  「悪いのは俺だ」

  ボッチはつぶやいた。その調子は，まるでアルジが自分で発したようでもあった。

  昨日とは逆の道を進む獣車。その足取りは変わらないはずなのに，奇妙に重く，遅く感じられたのだった。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
