#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 028

  この章では，ストーリーに進展はない。ゆえに，雨の日にできた路地裏の水たまり，そういったものを嫌う読者は飛ばしてほしい。

  自室のベッドで毛布にくるまり，アルジは虚空をながめている。こんな間もショムは2人を救うため，夜を徹して治療にあたっている。あの夜，優しく自分をなぐさめてくれたミミは自室にこもりきりで，シッショは何か上の空だ。

  そんな状況なのに，アルジは自分がワクワクしているのが不思議でしょうがなかった。自分はおかしいのだ。普通は相手の悲しみにあわせ，落ち込んでいるべきなのだ。だがこの間も頭の中では常にザエルと組み手をし，どうすればかわせるか，倒せるか，そればかりを考えている。ザエルはボッチ団にとって悪夢だ。それだけじゃない。ほとんどの人にとって，あんなバケモノに襲われ，仲間に瀕死の怪我を負わされれば，誰でもボッチのように，キセイのように，そしてミミのように，おかしくなる。あの出来事を思い出すことさえも憚られるだろう。

  あの日は忘れられるべきだ。森のような危険な場所には近付かず，もっと安全な場所を調査し，穏やかな日々を送るべきなのだ。そして些細な発見に一喜一憂し，報告書の誤字に笑い，採取された食材で彩られた食事に満足し，湯で身体を癒し，大地とともに眠りにつく。

  だがアルジの心は，一刻もはやくザエルと戦いたいという興奮にかられていた。その巨躯から想像できない身のこなし，視野，そして狙った敵を確実に葬る必殺の拳。あんなものがこの世にいて，そして今でも生きているのだ。

  なんて素晴らしいのだろう。

  仮にザエルがいかに素晴らしいモンスターかをこの里の誰かに語ろうものなら，軽蔑だけでは済まない。信じられない。おまえに人の心はないのか。あらゆる負の言葉がアルジにふりかかってくる。やがて唾棄すべき存在として排除される。

  そうだ。自分でも信じられない。シンキが爆炎に包まれたとき，アルジは隠しきれない喜びを感じたのだ。あの霧に，やつの秘密が隠されているに違いない。仲間の生死よりもその好奇心が先に立ったことに，アルジはひどく後悔し，そんな自分を嫌悪し，同時に己が飼う獣に恐怖した。

  いや，もともと自分に人の心などないのかもしれない。そうアルジは考えていた。里のなかで，相手の一挙手一投足に気を配り，傷つけないような言葉を選び，それでもしくじり，そのたびに毎晩後悔する。けれども自分以外の人達は，それを何なくこなし，笑い，泣き，過ごしている。ケライでさえも。

  人が喜ぶものに自分は苦しみ，逆に人が恐れるものに自分は興奮をおぼえる。多少のずれであれば修正できようが，完全に逆になっているものを，どのように直すのか。直せるのか。直せないなら，人の世で同じように笑い，泣き，暮らすことはかなわないのだ。自分はどこにもいられない。居場所など，はじめからない。

  だがアルジは心のどこかで，そんな自分に対する奇妙な信頼もおぼえている。消すべきだと思いながら，同時に絶対に失うべきでないとも思っている。それは自分に対するある種の期待でもあった。全ての人が同じものを恐れれば，それを克服することはできない。けれども人の恐れるものを喜ぶ自分なら。

  「私だけが」

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
