#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 033

  シッショのくびきから解かれたクビワは，夜の雪山を飛ぶように駆けた。足に自信のあるアルジが全くついていけない。

  夕方に里を出たアルジ達は，二手に別れて捜索することになった。そして，雪灯籠が見つかり次第，地図に印をつけ，信号弾を打ちあげたから引き返す予定になっていた。

  アルジとクビワは，クビワのおもむくまま高い所を目指していたが，ゆとりのあるはずのロープはピンと張られたままで，アルジは半ば引きずられるようなかたちでついてゆく。だが弱音は吐けない。見つかるのが早ければ早いほど，ケライとシンキを助けられる可能性も高まるのだ。

  そんな余計なことを考えていたためか，ふいにアルジは大きくコケてしまった。引っ張る力が強まったことにクビワが気付き，引き返してくる。

  アルジは右足と額から血を流していた。腕がないから突っ張ることもできず，岩場に豪快にぶつけたのだ。

  「アルジ，だいじょうぶか？いたいか？」クビワは腰をおろすと，心配そうにアルジの髪をかきあげ傷口を確認する。「少し痛いですけど大丈夫です」

  するとクビワはアルジに顔を近づけると，傷口をぺろぺろ舐め始めた。「わっ」アルジがあわてて壁際に飛びのく。

  「うごいたらだめだぞ」そう言ってクビワはアルジの腰に乗り，なおも舌を近づける。「ちょっと，恥ずかしいです。やめてください」「クビワがナメればどんなけがもいちころだ」クビワは恥ずかしさに目をつぶるアルジの額をしばらく舐めた。そして血が止まったのを確認すると，今度は身体の向きを逆にして裾をめくり，足も舐めはじめた。「くすぐったいですって」臀部がアルジの顔にぐいぐいと押しつけられ，足からは柔らかい感触とぴちゃぴちゃという音だけが聞こえてくる。「もうすぐなおるからがまんしろ」

  不思議なことに，確かに痛みがおさまってゆくように感じた。恥ずかしさとくすぐったさに痛覚が麻痺しただけかもしれないが。「どうだ？なおっただろ？」「はい，クビワさんの言う通りですね」クビワは立ち上がると，満足気に両手をはたいて笑顔で言った。「クビワのベロはばんのうやくだからな!」

  アルジはお礼を言って立ち上がろうとした。「あれ」右足はカクンと折れ，力が入らない。「すみません，ちょっとくじいちゃったみたいで」クビワは困った顔をする。「うーん，クビワのベロはあかいケガしかなおせない」

  ふと何か閃いたように，クビワが目を見開く。そしてアルジを抱えあげ，その腰の上に余ったヒモを乗せた。「いまからクビワさまがぜんりょくをみせてやるぞ。しっかりつかまってろ」

  「いえ，掴まりようがないんですが…」そう言い切らないうちに，急に風景が線のように変わった。耳に風のギュンギュン流れる音が聞こえる。

  さっきまでの速度でさえもかなりセーブしていたというのだろうか。アルジを抱えていなければさらに数段速いはずだ。これが人間が出せるスピードなのか。クビワの隠された真の実力にアルジは圧倒された。

  辺境最強というのもあながち嘘ではないかもしれない。そんなシッショの言葉が思い出された。

  胃が上下する。周囲の情景が，天地が，目まぐるしく変化する。まるで，

  「夢の中を飛んでいるようです」とアルジはつぶやいた。それが聞こえたのか，クビワは「マーマはクビワをこうしてゆりかごしてくれた」と答えた。「ゆりかご？クビワのお母さんが？」「そう。クビワがねるまで」

  しばらくしてクビワが立ち止まり，アルジをおろした。ほとんど息をきらしていない。一方のアルジは動悸がおさまらなかった。

  「ここがてっぺんだ」

  そうだ。ここが雪山の頂上なのだ。風の穏やかなこの雪山にあって，いまや二人を見下ろすものはない。そしてここからはるか遠く，やがて調査隊が訪れるであろう場所が見渡せた。雪山から森，湿原，薄靄のかかる山々。緑の草があふれる大地。そして，

  「あれは海か」

  地図にはない場所。そこには海がある。「クビワさんは前にもここに来たことがあるんですか」その問いにクビワはアルジの唇を指でおさえ，「シッショにはナイショだぞ」と小声で答えた。指を当てるべき人物が逆なことには言及しなかった。

  ？

  視線の端に，陽に由来するものとは違う色の光が見えた。「あれは」

  間違いない。見間違えようもない。雪灯籠の光だ。ここから遠くない崖際の台地。そこにケライとシンキを助ける秘薬が隠されている。

  「見つけましたよ!クビワさ…」そう言って振りむくと，膝を抱えて眠るクビワの姿があった。寝る子は育つ。ふだんならもう寝ている時間なのだ。眠くなるのも当然だった。

  アルジは地図に印をつけると，発見を知らせる信号弾を打ち上げた。しばらくしてそれに応じる信号弾がボッチ側から放たれる。

  それを確認すると，アルジは上着を脱ぎ，足がつりそうになりながらも，クビワが落ちないよう紐をかけて背負った。そして再度上着をクビワの背中にかけると，痛みの和らいだ足をかばいながら山をおりた。

  救助の信号弾も打つべきだったか。だが時間をかければ危険もなく里に帰還できるだろう。

  「マーマ」

  クビワは寝言を言いながら，アルジの背中に頬をすりつけた。

  「マーマ，あったかい」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
