#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 036

  里で飼う二頭のダモス，アルジ，マッパ，ボッチ，シッショ，さらに自ら参加を志願したキセイと相棒のゴリ，ワンワ。棍棒のような捕獲兵器を携え，調査隊が動員しうる全戦力は雪灯籠の近くで息をひそめている。すでに胞子状の光から場所を割り出し，アルジの確認のもと，装置の投下地点は決定した。あとはタイミングを合わせ放つだけだ。

  調査隊らが待機する雪面には水が撒かれ，引き上げる際に足が沈まないようにした。それに合わせ，各々の靴底も滑らないよう鋭利に加工してある。それがどれだけ有効かはわからないが，ダモスとゴリ，ワンワの力だけで足りないときにわずかでも加勢するのが目的だった。

  「準備はいいな」ボッチが言う。アルジらは無言で頷いた。時間がないながらも里で練習を積んだ。やるべきことはやった。

  「いくぞ」4人とゴリは棍棒をかつぐと，全力で走った。最後尾のマッパにすさまじい負荷がかかる。

  そしてそれは天に向かって放たれ，綺麗な山なりの軌道を描いた。ダモスはキセイの合図で逆方向に走りはじめる。

  雪の弾ける音とともに，その忌々しい柱が姿を現した。全身を見るのはアルジも初めてだ。

  捕獲装置は計画通りその身体へ飲み込まれた。「やった」ボッチとシッショが歓喜の声を漏らす。すぐにマッパとゴリはダモスの加勢に入る。

  まずい。二つの意味でアルジは思った。でかすぎる。アルジが初めて会った個体の倍近い大きさだった。おそらく棍棒についたトゲの返しは大して機能していないだろう。雪灯籠の口でひっかかっているだけなのではないか。そして雪灯籠の口の鋭さは，あれだけ硬い縄をも断ち切ろうとするほどだった。

  雪灯籠の柱は縄に引かれるように斜めになり，耐える。時間はない。雪灯籠の口から装置が飛び出す前に全身を引きずり出せるのか。縄は耐えられるのか。キセイもわずかながら助力し，全員で引く。

  すると不意に抵抗がなくなった。同時に，柱から桃色の物体がずるずると力なく引き出される。

  やった。成功だ。誰もが思った。次の瞬間，その硬い口が割れ，黒い棍棒が飛び出した。「よけろ!」マッパが叫ぶ。それは重さに似合わずくるくると回転すると，アルジ達に迫った。蜘蛛の子を散らすように逃げるアルジ達。だが，そのなかで一人だけ，恐怖で身動きできない者があった。

  「キセイ!」アルジは渾身の力で駆けた。キセイを腕のない肘で抱きかかえると，そのまま雪面に飛び込む。

  轟音と氷雪をぶちまけ，巨大な棍棒は地面に突き刺さった。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
