#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 037

  アルジが次に目覚めたのは地獄か。少なくともこの白い天井は地獄ではなさそうだ。ここはどこだ。あたりを見回すと，部屋の隅でケライが椅子に腰かけ本を読んでいる。…ケライが？

  「ケライ」アルジはケライに呼びかけた。「おはようございます」ケライは本を開いたまま顔を上げて返事をする。

  「ごぶさたしております」アルジは上体を起こしてケライをまじまじと見つめると，わけのわからないことを言った。「はい」とケライはいつもの調子で答える。だが実際，随分久しぶりに会ったような気がした。これまで治療室には入ることもできず，閉ざされたカーテンの向こうでケライがどうなっているのか全くわからなかったのだから。

  「ケライ，もう大丈夫なの？」「はい，おかげさまで」雪灯籠の素材が効いたのだろうか。「それよりもアルジさんの方こそ大丈夫ですか。一週間眠ったままだったそうですが」

  一週間。ずいぶん経ってしまった。マッパは待ちそびれて再び里を発ってしまったかもしれない。

  「そうだ。キセイさんは大丈夫？ケガしてない？」

  「寝ているのはもうアルジさんだけですよ」その答えにアルジは安心し，同時に少し焦りをおぼえる。「随分みんなに遅れをとっちゃったな」

  早く挨拶に行かなきゃ。そう言いながら着ていた布団を剥ぎ，ベッドの脇に腰をおろすと立ちあがろうとした。だが足に力が入らず，大きく体勢を崩す。あわててケライが間に入り，なんとか床に打ちつけずには済んだ。「あれ？」

  「大丈夫ですか」アルジはいつもケライに心配されてばかりいる。「ありがとう。なんか足に力が入らなくて」そう言ってアルジが視線をうつすと，膝から下がなくなっていた。

  「え？」

  そのままの体勢だとケライが苦しいので，再びベッドに腰掛けさせてもらう。疑問が身体全体の血管をかけめぐる。ちょっと待ってというやつだ。誰も焦らせたりなどしない。いくら時間をかけようが現実は変わらないからだ。

  「ケライ」「何ですか」「私の足がないんだけど」「そうですね」「何で？」「アルジさんの足がなくなった理由ですか」「そう」「私の聞いた話では，雪灯籠捕獲の際に喪失したそうです」

  避けきれなかったのだ。キセイが無事だったのは朗報だが。ただ，それと引き換えに，自分は手足のない喋るだけの人形になってしまったということか？

  「ケライ」「はい」「このまま黙っていると私はおかしくなってしまう。だから急いで私を落ち着かせてほしい」「わかりました」

  そう言ってケライは部屋を出て，一分も経たずに帰ってきた。そして何のためらいもなくアルジに注射を打つ。強力な鎮静剤だった。さすがケライだ。すごいぞ。

  強烈な睡魔に襲われ視界が暗くなるなか，ショムが勢いよくドアを開け放って入ってくるのが見えた。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
