#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 038

  その後，ミミに作ってもらった歩行器を使いアルジはラウンジに向かった。

  「おかえりアルジさん!」低く元気な声が響いた。見ると，ボッチの隣で，まだら顔の見慣れない人物が笑顔で手を振っている。

  「シンキさん，元気になったんですね」アルジの言葉に相手はほっとしたようだった。「アルジさんのおかげだよっ」「アルジだけの功績じゃないだろ」「もう，そういうこと言わない」ムードメーカーのシンキが復帰して，ボッチ団はようやく普段の明るさを取り戻したようだ。

  「アルジさん」ミミが笑顔で呼びかける。「キセイさんが言いたいことがあるそうですよ」そう言うミミの腰にキセイがしがみついている。

  「ほら，キセイさん」キセイはもじもじしながらも，ミミの服で顔を隠したまま小声で言った。

  「アルジ，ありがと」

  その一言で場が和んだ。「キセイさんも無事で何よりです」

  「アルジさんも足はもう大丈夫？」シンキが尋ねる。大丈夫じゃないとはいえない。「ミミさんのおかげで歩けるようになったので，まあまあですかね」「これからはあたしたちが守ってあげるからね!ね，ボッチ」

  そう言われたボッチは，ふん，と鼻を鳴らしながらもわずかに笑顔を浮かべて言った。「そうだな。アルジもボッチ団の一員だからな」ワッと歓声があがる。「やったねアルジさん!ボッチのお墨付きだよ!」

  アルジが恥ずかしそうに頭をかく。ふいにシンキの口元から笑みが消えた。「アルジさん，ボッチを助けてくれてありがと」

  「おい，俺は助けられてなんか…」「あのときボッチがあたしのせいで落ち込んで，もうヤケになっちゃうんじゃないか，立ち直れないんじゃないかって思ったの。でも治療室でショムさんが，ボッチがあたしを助けるために必死に頑張ってるって言ってるの聞いて，あたし本当にうれしくて，どんなに痛くても絶対負けないぞって思えたんだ。だから，ありがと」

  「そうだな。俺も礼を言わないとな，アルジ。シンキを助けてくれて，ありがとう」

  自分への感謝に満たされた空間。それは本当に気持ちのいいものだった。アルジはその世界にひたっていたかった。だがどれだけ歓迎されようと，自分がボッチ団の一員でいつづけることはできないだろうと思っていた。その穏やかな世界に不満を持ち，いずれ耐えきれなくなる。

  「皆さんに謝らなければいけないことがあります」その言葉で切り出した。「シンキさん達が襲われたのは私のせいなんです」

  それまでの明るい雰囲気が一瞬にして止む。「どういうこと？」まさかアルジは自分たちを罠に陥れたのだろうか。

  アルジはザエルのエサであろう卵について自分の考えを述べた。「それじゃあキセイは俺たちが襲われる前にそいつを見ていたってのか？」ボッチがキセイにつめよる。「キセイさんに責任はありません。私が勘違いしてあいつのエサに手を出していなければ，見逃してもらえたかもしれない」

  「それなら卵を回収したのは私です。私にも責任があります」ミミがアルジをかばう。「ミミさんは悪くない。私に腕がないから頼んだだけなんですから」「でも実際に取ったのは私です」ミミはアルジに寄り添い，優しく言った。「お願いだから，これ以上自分を責めないでください」

  シンキは心配そうにボッチを見る。誰も責めないでほしいというメッセージだ。

  「わかった。このことは全て報告する。オヤブンに何か言われるかもしれないが，森を調査対象にした俺に全ての責任がある。あとはその卵とやらが本当にやつのエサなのかは，今後調べなきゃいけない。俺たちでな」的確な判断だった。シンキは「さっすが」と言いながらボッチの肩を小突いた。シンキの前では，ボッチは勇敢さと冷静さを兼ね備える優れたリーダーなのだ。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
