#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 038

  その後，ミミに作ってもらった歩行器を使いアルジはラウンジに向かった。

  「おかえりアルジさん!」低く元気な声が響いた。そちらを見ると，ボッチの隣で，まだら顔の見慣れない人物が笑顔で手を振っている。

  「シンキさん，元気になったんですね」アルジの言葉に声の主はほっとしたようだった。「アルジさんのおかげだよっ」「アルジだけの功績じゃないだろ」「もう，そういうこと言わない」ムードメーカーのシンキが復帰して，ボッチ団はようやく普段の明るさを取り戻したようだ。

  「アルジさん」ミミが笑顔で呼びかける。「キセイさんが言いたいことがあるそうですよ」そう言うミミの腰にキセイがしがみついている。

  「ほら，キセイさん」キセイはもじもじしながらも，ミミの服で顔を隠したまま小声で言った。

  「アルジ，ありがと」

  その一言で場が和んだ。「キセイさんも無事で何よりです」

  「アルジさんも足はもう大丈夫？」シンキが尋ねる。大丈夫じゃないとはいえない。「ミミさんのおかげで歩けるようになったので，まあまあですかね」「これからはあたしたちが守ってあげるからね!ね，ボッチ」

  そう言われたボッチは，ふん，と鼻を鳴らしながらもわずかに笑顔を浮かべて言った。「そうだな。アルジもボッチ団の一員だからな」ワッと歓声があがる。「やったねアルジさん!ボッチのお墨付きだよ!」

  アルジが恥ずかしそうに頭をかく。ふいにシンキの口元から笑みが消えた。「アルジさん，ボッチを助けてくれてありがと」

  「おい，俺は助けられてなんか…」「あのときボッチがあたしのせいで落ち込んで，もうヤケになっちゃうんじゃないか，立ち直れないんじゃないかって思ったの。でも治療室でショムさんが，ボッチがあたしを助けるために必死に頑張ってるって言ってるの聞いて，あたし本当にうれしくて，どんなに痛くても絶対負けないぞって思えたんだ。だから，ありがと」

  「そうだな。俺も礼を言わないとな，アルジ。シンキを助けてくれて，ありがとう」

  自分への感謝に満たされた空間。それは本当に気持ちのいいものだった。アルジはその世界にひたっていたかった。だがどれだけ歓迎されようと，自分がボッチ団の一員でいつづけることはできないだろうと思っていた。その穏やかな世界に不満を持ち，耐えきれなくなると思っていた。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
