#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 039

  「どうしてキミは報告を怠るのかね」

  お前が気にいらないからだよ，とは言わなかった。

  治療を終えたこともあり，オヤブンに呼び出されたアルジは自身の身勝手な行動を責められていた。アルジの関与は至るところで報告されるものの，肝心のアルジから報告が上がらないためしびれをきらしたのだ。

  申し訳ありません，とアルジは詫びた。「キミの自由を禁止しているわけじゃない。行動するなら報告をしなさい」はい，今後は報告を常に意識するようにします。そうオヤブンの顔の向こうを見るようにして言う。直接目を合わせる気はない。

  「報告書も書かない，報告もしないというんじゃ困るんだよ」同じ話の繰り返しだった。おそらくオヤブンはふだんの生活で気にいらないことがあったのだろう。八つ当たりできる相手で不満を発散しているだけだ。「そもそもキミが手足を失ったのだってキミの不注意のせいだろう。事前に相談して実力を把握していれば失わずに済んだかもしれないのだ」「キミの無責任な行動が原因で今後ボッチくん達はキミの世話もしなきゃいけない。調査隊にとって迷惑な行動は慎んでもらいたい」

  オヤブンを黙らせるには実績を積むしかない。それには報告書を書く技能と，交渉術がなければならない。どちらの能力もないからといって，それを怠って行動すれば叱られるのは当然だ。身勝手なアルジがふてくされるのは御門違いもはなはだしい愚行である。

  アルジのふるまいで調査隊の士気が下がっているというわけではない。だがそれとこれとは話が別だ。物事にはルールがあり，それを破ればどんどん規制が厳しくなる。自由が失われる。誰にとっても悪いことにしかならない。だがアルジはそんなことは知らないといった様子で，心の内でうんざりし，能面のような表情で謝りつづけた。やがてネタもつきたのか，オヤブンが無言になったのを見計らい，今後は報告を欠かさないようにします。申し訳ありませんでした。と言って退室した。

  アルジは自分が幼稚なのはわかっている。けれどもオヤブンの幼稚な態度に，本当に紫針竜を倒す気があるのか疑問に思った。そして，どれだけつらくても，いかなるときも決してオヤブンの愚痴は言わないよう心に決めた。

  部屋の外にはミミが立っていた。おそらくオヤブンの叱責を受けるアルジが心配になったのだろう。

  「大丈夫ですか。何かひどいことでも」ミミの言葉を遮り，アルジは口に亡き指を当てるそぶりをし，またドアを亡き指で差すそぶりをした。肘までしかなくても意味は十分に伝わる。ドアの外で話してオヤブンに聞かれたら大変なのだ。

  ラウンジでは未だボッチとシンキが仲良くしゃべっている。ボッチの武勇伝にシンキがうんうんと頷く様子は，子供が親に今日あった出来事を嬉しそうに報告するようだった。そこに水を差さないよう，アルジは自分の部屋へ案内することにした。

  ベッドに二人で腰掛ける。「歩行器の具合はどうですか」アルジが話しやすくなるように，ミミは世間話を振った。「はい，自分で思うように歩けるのが嘘みたいです。本当に助かります」「それはよかった」

  「あの」アルジは普段から思っていた疑問を打ち明けることにした。「どうしてミミさんはそんなに優しくしてくれるんですか」「えぇっ？」ミミは驚いて笑ってしまう。「そんな。私は優しくなんてないですよ。よく怒るし」「優しいです。ほんとに優しくて，私が嬉しさでドキドキするくらい，」言い始めてから言葉の整理がつかなかったのか，一旦区切ってからアルジは言い直す。「だから，どうして私に優しくしてくれるのか，不思議なので，正直に言ってくれませんか」

  「そうですね…」ミミはアルジに向けていた顔を一旦そらすと，思い出すように話し出した。「いつも無理して強がっている様子がかわいいからっていうのもありますけど」「か，かわいい，ですか，私が」初めて受ける評価に赤面する。

  「でも，目を離すと時々どこかへ行ってしまいそうで，それが心配なんです」そう言われアルジはハッとする。「里のみんなとおしゃべりしている間も，一緒に調べものしている間も，ごはん食べている間も，どこかフワフワしてて，落ち着かない様子で，心はどこか別の方を見ていて」

  「そんな私たちって信用されてないのかなって」ミミの声が詰まる。

  「隠していても伝わるものなんですね」アルジは本心に従うまま打ち明けることにした。「やっぱり私たち信用されてなかったんですか」「そうじゃなくて」

  アルジは一呼吸おく。「私，監視されてたり，束縛されてたりすると駄目なんです。身体が震えて，何もできなくなってしまう」「オヤブンさんのことですか」アルジは返事をしなかった。「ボッチさんも」無言だった。それには答えず言葉を続ける。

  「組織だからしょうがないんですけど，でも」言わないつもりだった。だが堰をきった。「私に手足がないのをことあるごとにバカにされたり，それがみんなの迷惑だって言われるのは」ひどい，そう言ってミミは口元を隠し，耐えきれずポロポロと涙を流しはじめる。

  「正直，結構堪えます」

  「なんてひどいことを」そう言ってミミはアルジの肩にもたれかかり，長い時間，涙を流し続けた。アルジの分まで泣いてくれているように思えた。

  「わかりました」不意にミミは顔を上げ涙をぬぐうと，鼻声のまま真剣な顔で言った。「義足を作りましょう」

  「義足？」「そうです。アルジさんの義手と義足を私が作ります。みんなが嫉妬するくらい，何でも持てて，どこまでも走れるくらい便利な義手と義足です」「ミミさんは作ったことがあるんですか」「もちろんこれから調べるんです!」

  ミミはアルジの正面に膝立ちになり，アルジの両肘を持って言った。「私たちは人間なんです。なければ作ればいいんですよ!」

  「ないから作る…

  わからないから，調べる」「そう!そうですよアルジさん!頑張りましょ!」

  ミミの言葉に，アルジは自分の根幹と対話したように感じた。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
