#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 039

  選り好みをするような者には相応の仕打ちがある。

  「どうしてキミは報告を怠るのかね」

  お前が気にいらないからだよ，とは言わなかった。

  治療を終えたこともあり，オヤブンに呼び出されたアルジは自身の身勝手な行動を責められていた。アルジの関与は至るところで報告されるものの，肝心のアルジから報告が上がらないためしびれをきらしたのだ。

  申し訳ありません，とアルジは詫びた。「キミの自由を禁止しているわけじゃない。行動するなら報告をしなさい」はい，今後は報告を常に意識するようにします。そうオヤブンの顔の向こうを見るようにして言う。目を合わせる気はないが，あたかも目を見て話しているかのように振る舞える小技である。

  「報告書も書かない，報告もしないというんじゃ困るんだよ」同じ話の繰り返しだった。おそらくオヤブンはふだんの生活で気にいらないことがあったのだろう。八つ当たりできる相手で不満を発散しているだけだ。「そもそもキミが手足を失ったのだってキミの不注意のせいだろう。事前に相談してから行動していれば失わずに済んだかもしれないのだ」「キミの無責任な行動が原因で今後ボッチくん達はキミの世話もしなきゃいけない。調査隊にとって大きな損失だよ。もう少し反省しなさい」

  オヤブンを黙らせるには実績を積むしかない。それには報告書を書く技能と，交渉術がなければならない。どちらの能力もないからといって，それを怠って行動すれば叱られるのは当然だ。

  アルジは心の内でうんざりし，能面のような表情で謝りつづけた。無心でいることで，落ち込んでいる様子のように見える小技である。やがてネタもつきたのか，オヤブンが無言になったのを見計らい，今後は報告を欠かさないようにします。申し訳ありませんでした。と言って退室した。

  アルジはオヤブンの幼稚な態度に，本当に紫針竜を倒す気があるのか疑問に思った。そして，どれだけつらくても，いかなるときも決してオヤブンの愚痴は言わないよう心に決めた。

  私はオヤブンとは違う。オヤブンと違うニオイになってみせる。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
