#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 042

  その晩，シッショとクビワが調査から帰ってきた。

  「アルジ!かえってきたぞ!」泥だらけのクビワがアルジに抱きつく。

  シッショはラウンジのメンバーに，湿原の状況と，そこで発見された新種の生物について話した。マッパが昔設営したキャンプを拠点として，今後の調査を進めていく予定だという。マッパは湿原を抜け，その先まで足をのばしているそうだ。

  「マッパさんももっと記録を残してくれると僕らも調査しやすいんだけどなぁ」「シッショだって日記みたいな報告書しか書けないくせに何言ってんだよ」ボッチのツッコミに全員が笑った。

  マッパはいないものの，久し振りに全員揃った夕食となった。アルジにとっては送別会のようでもあった。

  北の空に流星が見えた頃，皆が寝静まったのを確認してアルジは里を出た。ケライには何も伝えなかった。万が一知られると何が起きるかわからなかったからだ。もはや以前のように自分に構うことはないほど，里に馴染んだ様子なのが，アルジには残念に思うと同時に嬉しかった。

  「もっとケライのこと知りたかったな」

  そうして義足の感触を確かめながら山道をとぼとぼと下っていると，風に毛をなびかせる人影が視界に入った。

  「シッショさん」

  「歩くと朝までかかるだろ，獣車が停めてあるから乗っていきなよ」

  それから獣車を操るシッショと，アルジは背中越しに話をした。

  ミミはシッショにだけこっそり打ち明けていた。ボッチに伝えるとおおごとになる。アルジを助けられるのはシッショだけだった。「シッショさんに迷惑をかけるわけには」「僕は怒られてもなんとも思わないから気にするなよ」

  「それより」シッショは少し気持ちをこめた調子で次の言葉を発した。「君はもう少し自分の命を大事にするべきだ」

  それを聞き，アルジはシッショの背中から目を反らすと背後の道に目をうつした。これまで自分がたどってきた道だ。これから進む道はダモスに隠されているように，通りすぎるまでは決して見えない。

  「君が死んだらクビワが悲しむ。それもある。でも，『どうせ人は死ぬから』『簡単に死ぬから』そんな知ったふうな気持ちで命を投げ捨てるようなことは調査隊員としてもするべきじゃない。生きて帰らなければ調査結果を知ることは誰にもできないのだから」

  世界の果てに達した。だとしても，それを生きて帰り知らせることがなければ，誰もそいつが世界の果てに行ったとは認めない。本人が世界の果てに行ったと豪語しても，その証がなければ，薬に溺れて見た夢かもしれないのだ。

  とはいえ今のアルジは，仮に薬に溺れて見た夢であっても，自分が世界の果てに行ったと思えさえすればよい，と考えているようである。

  それをわかっているのか，シッショは予想外のことを話し出した。

  「アルジ。」「何ですか」「君が本当に生きて帰ると，心の中からそう思って僕と約束してくれるなら，僕がみんなに隠していた秘密を明かそう。どうだい」

  なんとも魅力的な言葉だった。それはアルジがなかばヤケになっていた気持ちを，一気に引き戻すほどのものだった。

  「どう？約束する？」

  些細な好奇心でさえも人の心の向きを変えることができる。

  「約束します。絶対，生きて，調査を終えます」

  それでこそだよ，とシッショは言ったうえで，その秘密を明かした。

  <br>

  「僕とアルジで，そのバケモノを倒してみないか」

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
