#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 043

  アルジとシッショは，あの忌まわしき記憶の残るキャンプにたどりつき，互いの持ちうる知識すべてをもってザエルに対抗しようとした。そのやりとりはいささか専門的で退屈だったが，アルジが対峙した際の経験はシッショに伝わったようである。

  「アルジに渡しておきたいものがある」そう言ってシッショは獣車に積んでいた，布に包まれた長い物体を取り出した。それをとりはらって姿を現したのは，射出機構を備える鋭い槍である。

  「君の腕でも使える秘密兵器だ。西の地方で使っていたものと少し違うから対人用のものだろうけど，武器庫にあったのを持ってきた」そう言ってシッショは腕にはめて，構えを見せる。「燃料の爆発圧でこの槍を敵に打ち込む。重いからふだんは背負っておいて，いつでも構えられるようにしておくといい。射程はこのキャンプの端から端くらいまでだからそれほど長くはないけど，威力は折り紙つきだよ」「気持ちが高ぶりますね」

  シッショがザエルの討伐を提案したのも，この強力な兵器を発見したからかもしれない。当然，許可など取っていないだろう。見つかればどれだけ重い処分を受けるかわからない。アルジの血気はやる態度に影響されたのかもしれないが，これが蔓延すれば組織の統制がとれなくなり，極めて危険な状況となる。シッショほどの人物がそのことを理解していないとも思えないのだが，何がシッショをそこまで駆りたてているのだろうか。

  シッショは槍に手をそえると，アルジを正面から見て言った。「この形状だと，大型モンスターに使えば一回で先端が潰れてしまうだろう。だから使えるのは一度きりだ。好機が訪れたら，僕のことは気にせず使ってほしい。そしてザエルを倒してくれ。いいかい？」

  アルジは無言で頷いた。そしてアルジは槍を背負い，シッショは愛用の三尖槍を携え，森へ足を踏み入れた。シッショの不在は早々に里に知れる。それまでに決着をつけなければならない。ただし，ザエルとの遭遇は避けられないとしても，あくまでも第一目標は卵の採取である。

  先の戦いでアルジ達は大きな被害をこうむったものの，それでさえザエルにとっては邪魔者を追い払う程度のものでしかなかったはずだ。もしザエルが生命の危機を感じ，本来の力を発揮すれば，どれほど熾烈な攻撃をくりだしてくるのか，予想もできなかった。

  アルジの眼前に，やがて見覚えのある倒木や水たまりが姿を現す。どうやってやつの攻撃を避けるか，こちらの攻撃を当てるか。夢で何度も訪れた場所だ。実際にやってきたのは一度限りだが，もはや目を閉じても走り回れるほど，記憶に焼きついている。

  「このあたりでエサとなる卵が採取できます。この先に下草の茂る開けた場所があって，そこがおそらくやつの寝床かと」「しっ」シッショがアルジの口に指を当て，しきりに耳を動かす。

  破壊の象徴が近くに迫っているにも関わらず，そのときアルジは，かつてクビワが自分にしたのと同じポーズをシッショがとったことを思った。クビワが自分の口に指を当てたのは，シッショゆずりだったか。クビワはどこまでもシッショを慕っている。大事に思っている。

  だが事態はそんな思い出に浸っていられるほど呑気なものではなかった。

  「アルジ」見たことのない真剣な顔でシッショが聞いた。

  「はい」アルジはシッショに顔を近付けた。どんな言葉も決して聞き漏らさないように。

  「そのバケモノは木の間を飛び移れるのか？」

  <br>

  アルジの時間が一瞬止まった。心臓が口から飛び出しそうなのを抑えながら，震える声で答える。「私と以前に戦ったときは，そんなことはしませんでした」

  シッショはなおも全神経を耳に集中したまま，目を動かすのも忘れたように静止している。「大きなものが枝を飛び移る音が聞こえる」

  地上に縛られた相手だからこそ，こちらはまだ戦う方法があるのだ。あれだけ俊敏な相手が立体起動で襲ってきたらどうしようもない。

  「撤退しましょう」アルジが小声で提案する。シッショは身動きひとつしない。アルジは目だけシッショの方を向け，様子をうかがった。

  「駄目だ。囲まれている」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
