#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 046

  幸運なことは，人間と同様に，ザエルも後ろに目を持たないということだ。ゆえに，こちらは常にザエルの死角から攻撃を仕掛けることができる。その時間は瞬きほどかもしれない。だがゼロではないのだ。

  アルジは右腕の装置から糸を引き出し，口に咥えた。それを合図にシッショが動き出す。シッショが持つ槍はブラフではない。巨大なモンスターをも仕留める強力な武器である。それを察したザエルは首を動かしながら，シッショの動きを注視する。

  ふいにアルジが跳ねた。そちらに注意のとられるザエルにシッショが迫る。だが相手は森の王だ。よほどの隙がないかぎり，シッショの槍がその巨体を捉えることはない。ザエルの反撃が襲う。その爪を，牙を，シッショはかわす。槍では受けない。受けとめられるはずがない。

  アルジはきらめく光をたなびかせ，時おり擦れる音を発しながら木々を駆ける。必死に隙を探す。ザエルの身体を貫く準備はいつでもできている。だが相手が隙を見せるはずがない。隙がなければ，作るまで。

  さすがシッショだ。ザエルと一対一の様相を呈しながら，互角にわたりあっている。アルジがザエルから虫のように這い回っていたのに対し，シッショとザエルは踊るように立ち回っている。あのバケモノを倒してみないか。その言葉が冗談でなかったのを思い知らされる，無駄のない洗練された動き。なんと美しいのか。だが，アルジが仕掛けなければ，確実にシッショは死ぬ。シッショの武器だけではザエルは仕留められないのだ。

  準備はできた。

  パパパン。

  爆竹が鳴る音があり，次いで激しく何かの擦れる音がした。

  それを聞いたシッショが全力で音の鳴った方へ後退する。やや遅れてそれを追うザエル。だが何かに捕えられ動きが止まる。その頭部に，中身の詰まった硬い木が折り重なって倒れこんできた。大木の群れがザエルの身体を押し潰す。

  アルジだ。アルジがやった。それは森の王に初めて与えた有効打だった。円を描くように糸を通し，装置を使って一気に回収したのだ。先の摩擦音はその際に生じた。糸はザエルの動きを一瞬封じるとともに多数の大木を切断し，支えを失った木がザエルに襲いかかると，その巨体を地に沈めたのだった。

  「爆竹を鳴らすのが遅い。死ぬところだったよ」アルジの隣に立ったシッショは，息をあげながら言う。「すみません」アルジの返事を聞くか聞かないか，再びシッショは槍を構え倒木の群れに突進する。

  それに応じるようにそこから腕が伸び，あの忌まわしい霧を発した。

  互いに読んでいる。だがシッショのほうがわずかに速い。

  倒れこんだザエルの上半身。その肩にシッショは槍を突き立てた。金属音とともに両側の刃が瞬時に閉じる。

  はずだった。刃は途中で止まった。鎧のようなぶ厚い体毛が肉に達するのを防いだのだ。

  勝った。森の王がそう思ったかは定かではない。だがその腕がシッショを捉えることはなかった。

  シッショの背後から飛んできた鋼の針はザエルの掌を貫き，その剛腕ごと虚空へ弾きとばした。アルジの槍だ。

  仲間の命はつなぎとめられた。だが失態だった。それがザエルの額をとらえていれば，仮にシッショが爆炎に消えることはあれ，森の王を沈めることができたのだ。

  「好機が訪れたら，僕のことは気にせず使ってほしい」

  アルジはその約束を違え，同時に裂掌獣ザエルを倒す全ての手立てを失った。

  落胆している暇はない。アルジはダメージを負ったザエルが逃げてくれることを祈ったが，現実は怒り狂わせるだけだった。

  抜けない槍をあきらめたシッショはアルジの背後を指差し後退する。だが精神的な疲労が二人の足を鈍らせる。ザエルはまだ万全の腕が一本残っている。自身を覆っていた木をふきとばし，身震いすると雄叫びをあげながら二人に迫った。その腕と牙は精度を引き換えに更に速度を上げ，あらゆる障害を弾きながらあっという間に背後につく。

  爪を振るたびに爆炎が上がる。こいつは今後のことは考えていない。目の前の敵さえ仕留められれば。それだけを考えている。

  ザエルと一対一で対峙していたシッショのほうが疲労は激しかった。足がもつれるように倒れる。ふりかえるアルジ。立ち止まるのが一瞬遅れた。かけめぐる数々の後悔。身代わりにつきとばすか。その時間はない。シッショの背中に必殺の爪が迫った。

  ゴッ。

  鈍い音とともにザエルがのたうち回る。その背中から黒い影が飛び出し，二人の前に立った。

  <br>
  <br>

  「シッショをいじめるやつはころす」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
