#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 050

  シンキの部屋で豆をすり潰したスープが振る舞われた。アルジは，それを食器ですくってクビワに飲ませてやる。あれだけ大食いのクビワが，自分で手を伸ばして飲むことはしない。だがそれよりも，シンキはアルジの腕が食器を吸いつけていることに驚いた。アルジの腕には，ミミが作った特殊なシートが巻いてある。これには小さな輪がたくさんついている。それと対になる爪がついたテープを任意の道具に貼ると，爪が輪にひっかかることで色々な物を持つことができるのだ。簡単にいえば面ファスナーである。すごーい，と言いながらシンキはアルジの腕から意味もなく食器を脱着して遊んだ。

  小腹を満たしたクビワの身体がこわばっていたので，背中をさすり，げっぷを出させてやった。トイレと食事という大仕事をなしとげたのか，満足した様子でクビワは目を閉じ眠りはじめた。

  「ほんとに赤ちゃんみたいだね」起こさないようにシンキが小声で言う。

  「起きてるときも半分寝てるような感じで，少し熱もあるみたいなんです」アルジの言葉を受け，シンキはクビワの額，次いで首に手を当てる。「うーん，たしかにちょっとあったかいかも。朝になったらショムさんに見せたほうがいいかもしれないね」

  それからアルジは怪我の具合など，シンキと軽い世間話をしたあと，お礼を言ってシンキの部屋を出た。シンキは笑顔でじゃあね，と手を振った。

  里の人達は聖人ばかりなのだろうか。深夜にも関わらず快く食事を提供し，しかも気配りを忘れないシンキの優しさにアルジは震えた。

  いったん横になってしまうと，腰の具合から今度こそ起きあがれなくなってしまう。アルジは壁際に腰をおろし，浅い睡眠をとった。やがて朝になり，二人はショムの元を訪れた。クビワは腹側をショムに向けないので，体温や背中ごしの触診などを行う。

  「うーん，少し微熱があるほかに異状は見当たらないけど」「シッショさんが何か言っているのを聞いたことはありませんか」「そうですね…あ」

  ショムは何かを思い出したように言った。「シッショさんが，あれが来るとクビワが落ち着かなくなる，って相談しに来たことがあります。そのときはシッショさんひどい腰痛になって」

  腰痛。アルジと同じめにあったのだ。だがあれとは。考えられるのはザエルとの戦いで見せたもうひとつのクビワだが。

  「二，三日くらいでおさまるみたいだから，今回はアルジさんに我慢してもらうしかないかもしれませんね」「はあ。では，湿布を大量に下さい」「ふふっ。わかりました。そうだ，クビワさんのお通じのほうはどうですか」「ええと，クビワさんがこうなってまだ半日くらいなので」「じゃあオムツをしましょうか」「はい，お願いします」

  そんな調子であった。どんな調子かというと，オムツをしたクビワを常時抱えて日々を過ごし，本来のクビワに戻るのを待つことになったのだ。クビワが不快感を示したらショムをたずねるように言われた。基本的にクビワは寝ているが，たまにアルジに呼びかけてくる。いつも寂しがっているようだった。

  夕方，ショムの許可をもらってクビワを風呂に入れることにした。いつもは洗われる側だが，今日は洗う側である。腕が短いので髪をお湯で流し，身体の垢を落としてやる程度だが，クビワはさっぱりした様子だ。湯船に浸かっている間も，安心したような，穏やかな顔をしていた。

  「クビワさん，気持ちいいですか」「アルジ」「はい」「クビワってよんで」「クビワ，気持ちいい？」「うん，きもちいい」

  食事をとり，ショムにオムツを替えてもらうと，その晩はいつでも対応できるよう病室で眠ることにした。二人ですっぽりと毛布をかぶり，しばらくの後。

  「アルジ」耳元でクビワがささやいた。「何ですか」「もりにはクビワのなかまがいる」

  思わず跳ね起きそうになった。平静を装い返事をする。「クビワの仲間？」「にんげんがいっぱいころした。だからなかまがにんげんをいっぱいころした。にんげんはもういないけど，でもまだにんげんをうらんでる」

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
