#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 051

  マッパは湿原の先に広がる不毛の針山について語った。養分のない土に，イバラのような枝をもつやせた木が生えるのみで，痺れる雨が降る。痺れる，の詳細は不明だが，その雨に触れると身体がしびれたときのようになるのだそうだ。針山を超えないかぎりその先には行けないという。正確には迂回することが可能なのだが，そちらにはケライを瀕死に追いこんだ大樹がぽつぽつと生えているため，うかつに足を踏み入れられないのだ。

  というわけで，以前マッパがかわした約束について，アルジは報告を求められた。裂掌獣ザエルの討伐と，大樹の生態の解明である。まさか大樹が手つかずだと思わなかったマッパはアルジを怒鳴りつけ，今から行くと宣言した。

  だがアルジの腰は悪い。それはクビワの調子が変化するのを見越し，アルジに面倒を押しつけたシッショの責任でもあるのだが，「そんなもん伸ばせば治る」とアルジの腰を抱え鯖折りを仕掛けた。

  あまりの激痛に声を失い，アルジの存在がうっすらと薄くなってゆく。その場にいたミミが激怒し，二人の間を引き離す。「そんなことして悪化したらどうするんですか!」「お前は加工屋なんだからもっと丈夫な腰に替えてやればいい」「人間は機械じゃありません」「こいつはもう半分機械みたいなもんだろ」「まあ!なんて失礼なことを!信じられない!」この二人は会うたびに漫才のような喧嘩をする。

  「では私が残りの報告書について目処がたったら出発する，ということでいいですか」アルジは腰をさすりながらうめくように言った。「だめだ。すぐ出発の準備をしろ」「報告書を書かずに出発することはできません」「じゃあ今すぐ書き終えろ」「無理です。一週間はかかります」「なんで文字を埋めるだけでそんなに時間がかかるんだ」「意味のある文章にするには最低でもそれくらいの時間がかかります。ではマッパさんは今回の調査についてすぐに報告書が書けるんですか」「わからん。あと話題をそらすな」「そらしてません。マッパさんができるなら私もできるよう努力します。ですがマッパさんでもできないことを押しつけられたらみんな死んでしまいます。崖から飛び降りろとか，炎の中を歩けとか」

  アルジは最後を冗談で言ったつもりだった。だがマッパは「ふむ，」と言って考える素振りをした。どうやら，マッパはふつうの人間にとって何が無茶なのかを本当にわかっていないようだった。それゆえに要らぬ対立をこれまで生んできたのだろう。何をすると人間が壊れるのか，その基準を正しく教えてやれば，マッパは厳しくはあるものの，ものわかりのいい人物になると予想される。なぜなら，マッパは人の命を第一に考えるからだ。たとえば足の遅い人物を怠慢だと考えるマッパに対し，この人物がマッパのように走ると筋肉が断裂して死ぬ，と教えれば，無理に走らせようとはしなくなるだろう。なぜマッパのこうした性格がこれまで明らかにならなかったのか定かではない。「あんたとは違う」「殺す気か」といった批判は受けても，「使うと壊れる」ということを明確に指摘した者がこれまでいなかったのかもしれない。

  とりあえずアルジは裂掌獣に関する報告書の目処がつき次第，謎の大樹を調査することになった。だがそこへ，首から垂らした包帯で腕を吊るしたケライが現れた。

  「おはようございます」

  ケライはマッパを見た。「なぜこの人は裸なん」「全裸じゃない」

  <br>
  <br>

  マッパへのケライの紹介もそこそこに，危機的状況がアルジを襲うことになった。ケライの腕が限界に達し，しばらく使えなくなってしまったのである。このままではいつまでたっても目処がつかない。そんなアルジの不安など露知らず，ケライはマッパの正面にしゃがみこんで，興味津々にピアスをながめていた。

  「マッパさんはこんなところに装飾品着けて痛くないんですか。腫れてますけど」「腫れてる？そうかな」「私の倍以上あります」「たぶん，長い時間着けてるから大きくなっただけだ」「触ってもいいですか」「うーむ，少しだけな」「ちょっとお二人とも何してるんですか」ミミが真っ赤な顔で割って入る。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
