#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 053

  裂掌獣ザエルの報告書は，ケライ，ボッチらの協力で仕上がった。今後はショムの分析結果が報告書に追加されていくだろう。

  ようやくマッパはアルジを連れて謎の木の調査に向かえることになったわけだが，肝心のケライを連れていくことをアルジは拒んだ。本人は気にしていないようでいても，全身をズタズタに切り裂かれたのである。現場に行けば，そのときの恐怖が蘇るはずだ。そこで，マッパ，アルジ，シッショ，クビワの四人で調査にむかい，マッパとアルジが木を，シッショとクビワが以前の調査で遭遇した新種の生物を担当することになった。

  以前ケライが加わっていた頃とキャンプの場所は異なっていた。万一のときに信号弾が届くようにするためだ。だがそこは若干風が強く，静寂のなかで眠るというのは難しそうだった。

  「あの木ですか」そこから平地におりると，遠くにブロッコリーのような巨木が立っているのが見えた。「そうだ」多少変わった見た目ではあるが，とくにかわった様子もないし，実は動物がカムフラージュしている，といったふうでもない。わかっているのは，夜に青い光を放ち，甘い香りがする。そして興味を持ったケライが串刺しの罠におちたということだ。

  「とりあえず昼の間にできることをやっておきましょうか」「そうだな」「私が落ちたら拾い上げてください」「間に合えばな」間に合うのか。とにかくマッパとアルジは木の付近を調べはじめた。といってもマッパは歩き回り，山から吹き下りてくる風の心地良さを感じているだけである。

  命綱で互いを結ぶこともせず，自由に歩き回って危険ではないのか。だがアルジはケライの報告書からいくつかの予測をたてていた。「マッパさーん」遠くのマッパに大声で話しかける。「なんだー。何か見つけたかー」やや時間があって返事がかえってくる。

  「マッパさんってぇー」「おぉー」「どうしてぇー」そのとき強い風が吹いた。「なんだってー」「マッパさんはぁー」「おぉー」再び風が吹いた。

  こんな下らないコントをしていてはらちがあかない。そのためアルジはマッパのもとに駆けてゆく。すると，

  「とまれっ!」

  急に怒りに満ちた叫び声があった。あわててアルジが尻もちをつくようにして足を止める。見ると，足元の土がわずかにへこんでいる。隠された落とし穴だ。あと一歩踏み出していたらアルジの身体がバラバラになっていた。

  マッパがアルジの元に走ってくる。「大丈夫か」「ありがとうございます」「お前のような無能を連れてくるべきじゃなかったな」

  「まさにその点なんですが」アルジは腕を引き上げ立たせてもらいながら話を続けた。「なんでマッパさんは落ちずに済んでるんですか」「あ？」「この湿原にはあの木がいくつもあるはずなのに，どうしてこれまで落ちないのか不思議で」

  それを聞いたマッパは腕組みをすると，自信満々に答える。「わからん」

  その回答にアルジの口元はひきつり，落胆する。だがそれに続いてマッパから出た，

  「ただなんとなく『ここ落ちそうだな』ってのがわかる」という言葉がアルジの考えと結びついた。

  「やっぱり」「何がやっぱりなんだ？」「私たちには区別がつかないですが，マッパさんにはわかるような違いがあるってことなんです。ええと，料理人がわずかな味の違いもわかるとか，そういうやつです」「それが何の意味があるのかわからんのだが」「マッパさんにしかわからない違いが何なのかを私たちが理解できれば，安全にこの付近を調べられるようになるんですよ」「お前らにはわからんのか？」「残念ながら」「本当に残念なやつらだな」

  しかめっ面で返事をすると，マッパから笑みがこぼれた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
