#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 056

  マッパが大樹に向かってキャンプを出てから，アルジは手持ち無沙汰になった。そこで獣車の隣につなげたダモスに干し草を与えながら，その足元の大きく抉れた土をならしていると，

  視界の隅で信号弾が上がるのが見えた。緊急の移動手段を求める合図だ。シッショ達に何かあったのか。アルジは里に向かってジブーを呼ぶ信号弾を放ち，最小限の道具を持って駆け出した。ジブーは鼻がいい。マーキングされた布を首に巻いていれば，キャンプから離れていても追いついてくれるはずだ。

  胸騒ぎがした。信号弾が放たれた場所はかなりの距離がある。もし重傷だったら。もしマッパを大樹に送らず，信号弾に気付いていたら。しかも自身の足に負った傷は浅くない。まともに戦うことは不可能だ。いわば，ジブーがどれだけ速くアルジの元へ来て，自分が時間稼ぎをできるかにかかっている。

  シッショ達が向かったのは湿原から分かれた先の湿地だった。そこは日照量はさほどでもないものの，肥沃な泥土のおかげで丈の長い水草が繁茂している。もし設備が整えば，作物を育てることも可能だろう。実際，その下見も兼ねてシッショ達はここを調査しに来たはずだ。だがその可能性は一発の信号弾がかき消した。

  バシャバシャと水がはね返るのも構わず，草をかきわけて進むと，新たな信号弾が上がった。先の場所とは違う。移動している。いや，こちらが救出に来るのを確信して放ったのだ。自身の後退した場所を知らせるために。危機にあってもこれほど冷静な行動をとれるのは，

  「シッショさん」 草むらから伸びる槍。それが立つ場所にシッショはいた。そして，布が敷かれた上にクビワが横たわっている。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
