#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 060

  それから何ということもなく，メンバーは解散し，各自の部屋へ戻っていった。いくらマッパといえど，あの状況でオヤブンを説得することはできないだろう。アルジは音をたてないようシッショの部屋へ向かった。シッショが落ち着けば，そのザエルの情報をもっと得られると考えたためだ。

  だがアルジは自身の傲慢さを激しく後悔した。シッショの部屋に近づくと，ドア越しに嗚咽が漏れるのを聞いた。最も愛する者が，一時的にせよ命を失ったのだ。今後どうなるかだってわからない。そんな悲嘆に暮れる相手に，自分は取り調べをしようと考えていたのである。

  恥じた。アルジは自室に帰ると，ベッドに飛び込み，ひたすら恥じ，何度も心の中で謝った。そしてなおクビワを瀕死に追い込んだやつが何をしたのか，それを知りたいと思う心がふつふつと湧きだし，どれだけ頭を打ちつけようとその思いが消えないことに悶えた。

  ドアをノックする音があった。ケライだった。ショムが作っていたはずのマフラーを首に巻いている。プレゼントされたのだろう。その様子にアルジの負の思いがすぐに和らいでいくのを感じた。

  「上からすごい音がするので来たんですが，何かあったんですか。あの黒い虫の類でも出ましたか」

  「里は寒いからあれは出ないよ」先までの混乱が嘘のような平静な会話だった。すると，クビワがポケットからハンカチを取り出して，アルジの頭に触れた。「ここケガしてますけど」

  不意にアルジはケライを抱きしめていた。突然のことにケライが驚く。「あの，触らないでください」いつものように拒む。だがアルジは放さない。

  「ごめん」そう謝るアルジの声は震えていた。「お願いだから，私の話を聞いてほしい」

  「アルジさん…泣いてるんですか」その問いに返事はなかった。

  「話を聞きますから，離してくれませんか」

  その言葉からしばらくし，ようやく解放されたケライは，明かりの消えたラウンジでアルジと話すことにした。

  この地に真夜は無い。地平をなぞる陽は冷ややかな光をのばし，ラウンジの床を青白く照らしている。ケライは一枚の毛布をアルジとともにまとい，湯気ののぼるカップをながめながらアルジの口が開くのを待った。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
