#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 062

  翌日，アルジはマッパの調査に加わりたい旨を伝えたが，あっさりと断られた。

  「嫌だよ，めんどくさい」

  謎の大樹を調査した件で信用を失ったのだ。この過酷な地で自分以外の身を守ることまで手は回らない。しかも里から離れるほど，怪我をしたときに助けられなくなる。今後マッパが針山の先まで進むことを考えたとき，わずかな好奇心で慎重さを失うような者を連れていくことはできなかった。

  悪いことは重なるものだ。ふいにアルジは肩をつかまれると，ふりむいたところに拳が飛んできた。その勢いで椅子から転げ落ちると，何かが胸を押し潰す。

  「おい，何やってるんだ!」マッパが声をあげる。

  「クビワがみんなの楽しみを台無しにしたってどういうことだよ」アルジにのしかかり，胸ぐらをつかむ毛むくじゃらの腕。シッショだった。ああ，とアルジは察した。ケライが何かの拍子にシッショに話したのだろう。

  さらに，シッショの背中越しにアルジを罵る声が聞こえてくる。「楽しみを台無しにしたのはお前のほうじゃないのか」ラウンジの天井とシッショの姿しか見えないが，声の主はまぎれもない，ボッチだ。

  騒然とした様子にマッパだけが状況を把握できない。アルジに憎しみの目を向けるシッショ，ボッチに加え，複雑な表情のシンキまでもがそこにいた。アルジは全てをわかっている。この里で一番協調性がないのは自分なのだ。

  かつてよく見た光景だ。

  「言葉のとおりですよ。クビワの怪我がみんなの楽しみを台無しにしたんです」シッショに絞めあげられ，呼吸もままならないなか，アルジはシッショをにらみつけて言った。「なんだと」あまりの怒りにシッショがアルジの頭を床に叩きつける。

  「おいやめろっ」マッパが止めに入ろうとする。だがそれをアルジの言葉が遮った。

  「クビワが怪我せずに，安全に帰ってこれたら，もっと里は賑やかだった。だから，クビワを傷つけ，みんなの楽しみを台無しにしたザエルが憎いんです」

  その言葉にシッショがハッとし，力が抜ける。マッパが二人の間に入り，ようやくシッショはアルジの上から離れた。アルジは袖を口に当てて何度も咳をする。ボッチはアルジの言葉を聞いてからうつむいたままだ。事実，こんな里の雰囲気では，自分が作った人形をシンキに渡す機会などない。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
