#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 062

  翌朝，アルジはラウンジでくつろぐマッパに会った。そこでマッパの調査に加わりたい旨を伝えたが，あっさりと断られた。

  「嫌だよ，めんどくさい」

  謎の大樹を調査した件で信用を失ったのだ。この過酷な地で自分以外の身を守ることまで手は回らない。しかも里から離れるほど，怪我をしたときに助けられなくなる。今後マッパが針山の先まで進むことを考えたとき，わずかな好奇心で慎重さを失うような者を連れていくことはできなかった。

  悪いことは重なるものだ。ふいにアルジは肩をつかまれると，ふりむいたところに拳が飛んできた。その勢いで椅子から転げ落ちると，何かが胸を押し潰す。

  「おい，何やってるんだ!」マッパが声をあげる。

  「クビワがみんなの楽しみを台無しにしたってどういうことだよ」アルジにのしかかり，胸ぐらをつかむ毛むくじゃらの腕。シッショだった。ああ，とアルジは察した。ケライが何かの拍子にシッショに話したのだろう。

  さらに，シッショの背中越しにアルジを罵る声が聞こえてくる。「楽しみを台無しにしたのはお前のほうじゃないのか」ラウンジの天井とシッショの姿しか見えないが，声の主はまぎれもない，ボッチだ。

  騒然とした様子にマッパだけが状況を把握できない。アルジに憎しみの目を向けるシッショ，ボッチに加え，複雑な表情のシンキまでもがそこにいた。アルジは全てをわかっている。この里で一番協調性がないのは自分なのだ。

  昔，アルジがよく見た光景だ。

  「言葉のとおりですよ。クビワの怪我がみんなの楽しみを台無しにしたんです」シッショに絞めあげられ，呼吸もままならないなか，アルジはシッショをにらみつけて言った。「なんだと」あまりの怒りにシッショがアルジの頭を床に叩きつける。

  「おいやめろっ」マッパが止めに入ろうとする。だがそれをアルジの言葉が遮った。

  「クビワが怪我せずに，安全に帰ってこれたら，もっと里は賑やかだった。だから，クビワを傷つけ，みんなの楽しみを台無しにしたザエルが憎いんです」

  その言葉にシッショがハッとし，力が抜ける。マッパが二人の間に入り，ようやくシッショはアルジの上から離れた。アルジは袖を口に当てて何度も咳をする。ボッチはアルジの言葉を聞いてからうつむいたままだ。事実，こんな里の雰囲気では，自分が作った人形をシンキに渡す機会などない。

  勝手に縄張りに入り込み，返り討ちにあって，しかもそれで楽しみが台無しになった，と文句を言われているのだから，当のモンスターにとってはとんだ迷惑だ。とはいえ，ザエルらしきモンスターが生息する場所は，里の人々が命をつなぐための資源に満ちている可能性がある。いわば縄張り争いが起きたといってもいい。まあ，このモンスターにとって幸いなのは，この里でそれに立ち向かおうとしていたのがアルジだけということだ。威勢はいいが勝ち目はない。マッパであれば戦えるかもしれないが，こんな瑣末な諍いに興味はない。先に進むことだけを考えている。この地で長く生活するために苦労するより，里に資源があるうちに紫針竜を倒す方法を見つけるほうが賢い。だいたいマッパはこの地で自活できるとは思っていない。資源が尽きるまでにその方法が見つからなければ朽ちるのみ。そして残念なのは，モンスター一頭にチームが壊滅させられるような軟弱な戦力のなかで，マッパの考えを実行できるのもマッパだけだということである。

  アルジはその場にいることなどとてもできず，何も言わずにラウンジを去った。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
