#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 064

  当初はクビワの症状に類似した情報を医学書に求めたアルジだったが，臓器の知識をいくら得たところでたどり着かないことに気付き，怪我の症状であれば応急処置の本に書かれているのではないかと思い至った。そこで申し訳なく思いながらもケライにお願いし，そうした本を探してもらうことにした。ケライはアルジの言葉を聞くと，無言で手の平を机に叩きつけて立ち上がり，本棚に向かった。

  しばらくして「運ぶの手伝ってください」とアルジを呼ぶと，アルジの腕に次々と本を載せていき，アルジが落としそうになるのも構わずすたすたと席に戻った。着席するときに，どすん，と大きな音がした。

  応急処置の本は医学書よりも薄いものが多かった。といっても，タイトルを読めないアルジは医学のカテゴリからぶ厚い本を選んで持ってきただけだが。

  静かな書庫で，しばらくペンをはしらせる音と，紙をめくる音だけが響いた。

  ふと，身体のただれたイラストが並ぶ項で，無傷の身体が描かれているのが目についた。次のページでは負傷者とは異なる人物，おそらく応急処置の実施者，が胸に両手をあてている。この手の位置は心臓マッサージか？他の本をめくると，いくつかの本で同じような書かれ方をしている項目がある。

  「あの，ケライさん」アルジは斜向かいのケライに声をかけた。ケライはその言葉を無視するようにしばらくペンを動かし，顔を上げる。「なんですか」語気が強い。文を書く作業を中断されれば誰でも不満をおぼえるだろう。

  「これ，なんて書いてあるのか読んでいただけないでしょうか」そう言ってアルジは本を逆さまにしてケライの方に差し出す。ケライは少し首をのばして書かれた言葉を見る。「ネッショウです」

  「ネッショウ？」「熱傷。火傷のことです」「火傷？どうして火傷の応急処置なのに，無傷の人の絵があるの」「無傷の人とは」

  アルジは該当する部分を何冊か開き，ケライの隣に座ると自分の考えを説明し，そこで書かれている文章をケライに読んでもらえるよう頼んだ。ケライはそれを聞き，軽く咳払いすると，仕方なく読み始めた。そのなかで，閃きとともに，アルジのアイデアがパズルのように組み上がっていく。

  無傷のまま相手を倒す。

  時，そして心臓を止める。

  「ありがとう，ケライ。ミミさんに相談してくる」そう言ってアルジは本もそのままに書庫を飛び出した。雑多に積まれた本を眺め，ケライはまた溜め息をついた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
