#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 065

  医務室への扉は閉鎖されていなかったが，そこにミミの姿はなかった。中ではキバとツメがショムと遊んでいる。もはやショムは他人が入ってきても，その顔がにやけるのを隠そうとはしない。

  「あの，ミミさんは」そう聞くと，ショムは尻尾を振るキバの首元をなでながら「仮眠をとりに戻ったんじゃないかしら」と笑顔で答えた。

  「それより頬が腫れてるけど大丈夫？ひどいアザ…，額もケガしてるみたいだけど」「いえ，大丈夫です。いつものことですから。ありがとうございます」そう言って出ようとすると，「待って，アルジさん」と呼びとめられた。

  「アルジさんが採取してきたあの卵，アルジさんの言った通りでしたよ」

  その言葉にアルジは驚いた。怪我人の治療や日々の激務をこなすなかで，ちゃんと資料の分析も行っていたのだ。いつ寝ているのか，それを考えると恐ろしく，聞かないことにした。

  「キバちゃんとツメちゃんが協力してくれたおかげでわかったんだよねー」そう言ってキバの腕を取り，アルジに手を振るようなそぶりをさせる。キバはそれに応じるように吠えた。腹に響くほどの大声にアルジはうろたえる。どれだけ小柄でもこいつはあの裂掌獣ザエルなのだ。

  「では，ザエルはあの卵を食べている，と」

  「食べているかどうかは確証がないけど，可能性はかなり高いでしょうね。それに含まれる物質に，裂掌獣が体内で生成する成分が混ざると爆発的な反応が起きるの」

  「キバやツメに食べさせなかったんですか？」「こんな小さいのにあんなの食べさせられるわけないでしょ。おなか壊しちゃうもんねー」そう言いながらショムはキバを揺らす。

  「え，ええと，わかりました。ではその爆発を武器や，設備とかに活かすことはできますか？」「うーん，どうでしょうね。ミミさんは反応の仕組みを理解したはずだから，応用できるかもしれないけど」その言葉を聞いて，ミミが寝ているというのが益々じれったく思った。とはいえこれだけ里のために尽くしている不可欠なメンバーに無理強いはできない。

  アルジは改めて礼を言って退室したあと，ラウンジに戻ろうとしたところで，本をそのままにしていたことを思い出し，書庫に向かった。

  書庫は綺麗に片づけられていた。謝らなくては。そう思い，ケライを探すためラウンジへ向かう。すると，人々の賑わう声が聞こえてきた。

  「ほら，あと一皿だよ!がんばって!」「ぐ…」「やっぱ大食いじゃ勝てないかー」「まけない。ぜったい，かつ」

  聞き覚えのあるやりとりだった。昼のあたたかな陽気のなかで，片手を垂らしたクビワと，片手に包帯を巻いたケライが大食い合戦をしていたのだ。というより，クビワが勝手に挑んだのだろう。それよりも，

  「クビワ，もう動いて大丈夫なの？」アルジが戻ってきた様子に，ケライとクビワをのぞく，その場にいた全員がハッとなる。

  「アルジ…」シッショがつぶやく。「クビワ。おかえり」アルジはクビワの横に立ち，声をかけた。「アルジ…あいさつは，あと。いま，こいつ，たおすから」「腕は大丈夫なの？」「うるさい…だまってろ…」今回もかなり劣勢のようだ。

  「ケライ，ごめんね。本片付けてくれてありがとう」今度はケライのほうに声をかける。「いいです。今度手伝ってもらいますから。資料集めも含めて」多少腹も膨れて不満もおさまっているようだが，まだしこりが残っているようだ。

  「シッショさん，ボッチさん，ひどいこと言ってすみませんでした」最後に朝のトラブルを引き起こした二人に謝る。「そんな，ひどいことをしたのは僕のほうだ。僕はクビワのことになると自分を見失ってしまって。怪我もさせてしまった。本当にすまない」「俺も勘違いして悪かった」

  「それよりもクビワはもう大丈夫なんですか」「見てのとおりだよ。まだ身体に麻痺が残ってるみたいだけど，すぐによくなると思う。本当によかった。本当に…」そう言ってシッショの目がうるむ。

  するとその背中をボッチが思いっきりはたいて言った。「まあ，そういうことだから，調査範囲の縮小なんてナシだ!今までの分を取り返すくらい働こうぜ!」

  クビワの復活によって，沈んでいた里の雰囲気は一気によみがえった。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
