#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 067

  マッパはボッチ，オヤブンとともに今後のミーティングを行っている。ミミに相談するはずだったアルジは手持ち無沙汰になったためラウンジで義足の手入れをしていた。

  「あ，アルジさん。今ヒマ？」そこへシンキがやってきて，自分の代わりに作業を依頼してきた。シンキ自身はショムとともにミミの具合を診る手伝いをしなければならないからだ。

  「そんなに具合が悪いんですか」「ううん。心配しなくていいよ。それより，さっきは不気味な顔なんて言っちゃってごめんね。あたし思ったことすぐ口にしちゃうタイプで」

  シンキは思ったことを口にするタイプと言いながら，それが相手の心を傷つける事態にはならない。一方アルジは思ったことを抑えていようが，相手を平気で傷つける。「そうだ，シンキさん」「なに？」「腕編みってご存知ですか？」「腕編み？」

  アルジは以前シンキの部屋を訪れた際，シンキが裁縫好きなのを知った。シンキは怪我の後遺症でうまく指を動かせないが，腕編みならばいくつかのものを作ることができる。「そんなのがあるの？」「はい，こんど時間があるときにやってみませんか」「いいよ!最近細かいことやってないから頭がなまっちゃってさ」「頭がなまるって何ですか」シンキの巧みな会話にのることで，アルジは自分が話し上手になったかのような錯覚を体験した。

  <br>

  アルジに課されたのは里からみて裏にある山からいくつかの薬草を摘んでくることだった。途中でキセイが過ごす獣舎を通りすぎる。ふだん見せたことのないような笑顔で，キセイはペット達やザエルの子と遊んでいた。こうして築いた信頼関係が，はるかに大きな敵にも屈しない勇敢さにつながっているのだ。アルジは初めてザエルと戦ったときのゴリの頼もしさを思い出していた。

  シンキからの依頼は漠然としたものだったが，その意味が理解できた。

  そこには畑があった。種のうちは里の温泉で生まれる熱を活かし，凍らずに育てることができているのだろう。やがて芽が出てある程度まで育てば，多少の寒さにも耐えられるようになる。アルジはこの地の生物にばかり気をとられていたが，それらを活かす工夫に関しては，この豊かな畑を生み出したであろうシンキらの足元にも及ばない。里の人々から学ぶべきことは尽きない。

  積もった雪をはらい，U字形の握り鋏を口にくわえると，シンキに言われた形の薬草を切ってカゴに入れてゆく。腕が使えないため，腰に激しい負担がかかる。痛みを耐えてカゴが一杯になる頃には夕方になっていた。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
