#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 069

  ミミは里のなかではしっかりした穏やかな性格で通っているが，それほど強い心を持っているわけではないし，「ミミなら大丈夫」という先入観を持たれていることに不満も持っている。できて当然，ではなく，何かを作るたびに，心から感謝してもらいたいと思っている。シッショの文章がヘタであることをからかいながら書き方を指導することもしないボッチや，好き勝手に資源を持ち出しておきながら何ら収穫もなく帰ってくるマッパにも苛立っている。それらはかつて自分へいわれのない非難をぶつけてきた人々を思い出させる。

  本来はもっと自由に感情を露にしたいが，それで今までの関係が壊れるのは良くないことだ。また里に波風をたてるのも誰の得にもならない。だからふだんは自分の内で耐えているが，それが身体の不調なときに重なって限界を超えると寝込んでしまう。そのことを知り，話を聞いてくれるのはシンキだけである。

  アルジがミミに文字入力の装置と義手について催促してこないのは幸いである，とともに後ろめたさも感じている。アルジの腕は肘から先がないので，ふつうに義手を作っても長い棒のような役割にしかならない。曲げられないからだ。それでも身体のバランスを取りやすくなるので十分なのだが，素晴らしい義手を作ると約束してしまった以上，構想ばかりがふくらんで実現が伴わず，自分を苦しめることになってしまっている。ただ，今後アルジはボッチ団の一員として再び調査に参加することになる。それまでに何らかのものを完成させなければならない。

  当のアルジは，その頃シッショとともに，オヤブンの許可を得て武器庫で自分に合う得物を物色していた。以前シッショがザエルを倒すために武器を持ち出した際は，数日の謹慎で済んだ。あまりに重い処分ではクビワが誤解して里を滅ぼすことになりかねないと判断されたためだろう。まあそんなこともあって，本来ならシッショは武器庫に近づけないはずだが，ボッチ団で活動するアルジのために，今回は特別に許されている。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
