#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 070

  毎晩の練習で疲れたアルジは，その日の昼頃に起き，やや寝ぼけながらラウンジへ降りていった。外からボッチの大声が聞こえてくる。調査の準備が大詰めなのだろう。シッショらは思い立ったら旅立つほどにフットワークが軽いが，あれはマッパの作ったキャンプに必需品も置かれているためだ。かたやボッチらが向かうのはマッパ未踏の地であり，大がかりになるのは仕方ない。

  ふとアルジは，ラウンジでゆっくり食事をとるミミと目が合った。話したくてしょうがない衝動とともに，シンキの言葉がよぎる。

  「おはようございます」ややかすれた声でミミが挨拶をした。「おはようございます，ミミさん。身体は大丈夫ですか。無理しないでくださいね」アルジは社交辞令の返事をする。「はい，おかげさまでだいぶ良くなりました。それよりアルジさんこそ頬が腫れてますが」「いえ，これは転んでできたものなので，大丈夫です」負傷した際に転んでいるので嘘は言っていない。

  近くまで来て棒立ちになるアルジを見て，ミミはふっと笑う。「お話ししたいことがあるんでしょ？」その言葉にアルジの強張った顔がゆるんでしまう。「はい，やっぱりわかりますか」「顔に書いてありますよ。どうですか，一緒に」

  ミミに促されるままアルジは二人で食事をとる。相手の体調は回復しているのか。それがわからないアルジは，私が一人で食べられるのもミミさんのおかげです，等，あたりさわりのない世間話で様子をうかがう。ただ，ミミもアルジが他に聞きたいことがあるのをわかっているようだった。

  「ごめんなさいミミさん」アルジは急に謝った。「え，どうしたんですか」当然の返事だ。

  「やっぱり私は我慢できない。だから聞きます。シッショさんとクビワが会ったモンスターのこと」

  てっきりアルジに義手の催促をされるのかと身構えていたミミは呆気にとられる。「ミミさんはクビワの治療に関わったから，私の考えが正しいかどうかを聞いてほしいんです」何日も待った。もう限界だった。そしてそれはミミが危惧したものではなかった。アルジの要求をミミはすんなり受け入れた。

  ミミはクビワの症状を知っている。だがシッショの証言は知らない。「時を止める」と言っていたことも。ゆえに，アルジはシッショの話をできる限り正確に再現した。ザエルの攻撃を軽々と避けていたクビワの身体が急に停止したこと。その身体は凍ったようだったこと。心臓が止まり，蘇生処置をしたこと。にもかかわらず目立った外傷がないこと。

  そして意識を取り戻したクビワは，多少の麻痺が残ったものの，それも今はほぼなくなり，後遺症もなく元気であること。

  そもそも触れずに相手の動きを止められるのか。そうアルジが聞いた直後，

  「止まれ!!」

  腹まで震えるほどの轟音だった。思わずアルジは硬直する。

  大声の主はミミである。それは当然ながら広場まで響きわたり，心配したボッチ達がラウンジをのぞきこんだ。ミミは外に向かって「なんでもありません」と笑顔で答え，アルジに向き直って続けた。

  「こんなふうに，声でも簡単に相手の動きを止められます。場合によっては相手を心停止に追いこむことも不可能じゃありませんし，外傷や，回復した際の後遺症もありません。でも証言によると，シッショさんはそんな声は聞いていませんよね，って，ちょっとアルジさん。なんですかその顔。ふふっ」

  腫れた頬とは不釣り合いな，子供のように輝いた瞳でアルジはミミの言葉を聞き，恍惚とした表情を浮かべていた。ミミはそんな顔を見て思わずふきだしてしまった。しかも「私，ミミさんと会えてよかった」等と意味不明なことを言うものだから，笑いをこらえきれないミミに身体をはたかれることになった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
