#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 075

  水がぶちまけられる。賢い。相手はこちらが何らかの対策をとっていることを見抜いている。それはそうだろう。アルジの異形の足はもはや生物に由来していないのだから。だがアルジの義足が水にまみれてしまえば，その効力も失われる。アルジを追い詰めるための水ならたくさんある。ここはそのために選ばれた場所なのだ。

  雷掌獣はその体格を活かし，水しぶきで自分よりも小さいアルジの目をくらます。濁ったカーテンの後ろから爪を伸ばし，必殺に依らずとも相手の命を奪えることを示す。だがアルジはこれまでその動きを嫌というほど見てきた。幾度も夢に見た。起きていても離れることのない日々さえもあった。今自分が相対しているのはそれよりも小さい。その腕は，夢に見た拳よりも伸びることはない。シッショの言うとおりだ。クビワならば容易に避けられるだろう。

  ゆえに，アルジが待つのは必殺の放たれるその瞬間だった。何らかの予備動作がある。必ず。シッショが見逃したものが。

  「アルジっ」危機に陥るたびにシッショが呼ぶ声がする。だがそれは水のはねる音にかき消され，伝わらない。悪臭玉の補助はもはや利かない。すでに相手はそのニオイを知り，無害なものであることを知っているからだ。仮にニオイの中身を変えたとしても，すぐにわかるだろう。ゆえに通じない。

  ふいにアルジの足が小石を踏み，体勢が揺らいだ。足がもつれ，尻餅をつきそうになる。まずい。身体が水面に接したらおしまいだ。

  なんとか踏みとどまり，こらえるその身体に，容赦なく雷掌獣の腕が襲いかかった。爪が身体をかすめる。まさに間一髪のところで避けたその腕が，激しく水面に叩きつけられた。勢いの反動か，その動きが一瞬止まる。違う。それは反動じゃない。これは。

  何かの弾けるような音。

  飛び散るしぶきにシッショたちの視界がふさがれた。

  「アルジっ」シッショとクビワが叫ぶ。

  <br>

  静寂。シッショとクビワだけでなく，周囲に生える草一本一本までが事のなりゆきを見守っているようだった。

  やがて霧のような水が晴れてきた。その中にアルジはいた。だが立ったまま身動きひとつしない。髪から雫が垂れている。

  だが雷掌獣は。雷掌獣はどうだ。シッショが視線を向ける。

  その頭部は大きく抉れ，黒い球がめりこんでいた。球から伸びる鎖はアルジの肩につながっている。

  勝った。アルジが勝ったのだ。体力の保たない貧弱なアルジは，雷掌獣の雷撃を放つまでかわし続けるのは不可能だった。ゆえにあえて転ぶような隙を見せ，相手を油断させる賭けに出た。そして賭けに勝った。雷掌獣はこの貧弱な獲物を仕留めるべく拳から雷撃を繰り出した。だがそれこそがアルジの罠だった。裂掌獣とクビワとの戦いから，大技が隙になると読んでいた。予想通りだ。雷撃を放った雷掌獣の身体は一瞬硬直した。その無防備な頭部に合わせるように，アルジは身体を大きくひねって回転させた。肩から伸びた鉄球は加速し，強い遠心力を得て頭部に命中した。クビワを一撃で沈めた雷掌獣の命もまた，一撃で絶たれたのだ。

  ただし，優れた足がなければアルジの命が絶たれていた。ミミがアルジを守ったのだ。シッショが何かを叫び，走ってくる。アルジは倒れた雷掌獣のそばにしゃがみこみ，巨躯をながめながら，どう素材を持ち帰ろうか考えていた。

  大技は隙を生む。

  <br>

  「アルジっ!!」

  その声にふとアルジは，大きなクチバシが身体に食い込んでいるのを知った。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
