#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 078

  本当は夜こっそり里へ帰り，リーダーであるシッショに全ての報告を任せようと，こざかしいことをアルジは考えていた。だが，まっさきにミミに礼を言う，そのためだけに，堂々と帰還した。

  里には，シンキ，ミミらとともに，オヤブンも待ち構えていた。当然だ。ボッチ団の調査を先送りして，雷掌獣の討伐に向かったのだから。アルジ達はさぞかし多くの収穫を持ち帰ったことだろう。そんな無言の圧力だった。

  広場に入り，空腹を訴えたクビワは早々にラウンジへと向かった。ああ，こら。クビワ，まだ挨拶と報告が済んでないだろ，とシッショはオヤブンに苦笑いで会釈し，なんとそのままクビワについて行ってしまった。

  アルジだけがその場に残された。ミミの後ろから抱きつき，これ以上泣かせまいと不審の目を向けるシンキ。先送りの交渉を丸投げされ，腕組みをしながら成果の言葉を待つボッチ。困った様子のミミ。何を言っても怒るオヤブン。

  挙動不審に視線を泳がせるアルジ。求められる情報，そこからのやり取りを粗末な頭脳で描き，なんとか自身へのダメージが少なくなるような言葉を選ぼうとする。

  「シッショ，クビワ，アルジ。調査任務からただいま帰還しました」揺れる目でオヤブンを見る。「おかえり。その様子だと失敗したみたいだが」オヤブンはすぐに答えた。「まあ，怪我がなかったのは幸いだな」

  とでも言うと思ったか？

  そんな最悪のシナリオも浮かんだ。だが次の言葉がオヤブンの口からは出てこない。アルジが報告しろ，という無言の合図だ。

  「雷掌獣の討伐には成功しました」やや顔を伏せるように言う。その言葉にアルジをのぞく四人が顔を見合わせる。すごいじゃないか。では，なぜアルジの様子は自信がなさそうなのだ？

  「ですが，新たなモンスターの襲撃を受けたため，素材の回収はできませんでした」

  途端に溜め息があがる。だから湿地など後回しにすべきだったんだ。ボッチは心の中でつぶやく。だが，「湿地に生息する生物のほとんどはそのモンスターに捕食され，姿を消したと考えられます」という言葉で空気は一変した。それほど強力なモンスターがいるのなら，湿地から北を目指すルートを開拓することは極めて困難になる。

  「それを示す証拠はあるかね。それ，というのは今報告された雷掌獣討伐，モンスターの襲撃，およびそのモンスターによる湿地の攪乱，という意味だが」オヤブンが追及する。本来ならオヤブンの私室で行うべき子細に入っているのだが。オヤブンはアルジを信じていないというわけではないが，これまでの身勝手な行動もあり，言葉だけで納得するほどは信用していない。

  回答如何によってはアルジは大勢の前で叱責されることになる。その状況に，場の緊張が高まる。アルジは覚悟した。

  「物的なものは，何も。申し訳ありません」

  オヤブンの顔が険しくなった直後，四人の後ろから，「とりあえず，簡単な報告はここまでにしませんか」という声が聞こえた。はじめはそこにいなかったショムだ。「詳しいことはあとでもいいでしょう。アルジさん，おかえりなさい。ゆっくり身体を休めてくださいね」

  激しい動悸の続くアルジと，それをほっとした顔で見るミミ。オヤブンは「そうだな。詳しいことは報告書に書いてくれたまえ」と言ってラウンジに戻っていった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
