#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 079

  この章はストーリーに多少展開があるものの，辛気臭い。読まなくてもストーリーの理解に影響はないので，それが嫌な読者は飛ばしてほしい。

  ジブーに乗って雪山を駆け下りながら，アルジは自分がとり返しのつかないことをしていると思い，同時に，妙な興奮も覚えていた。

  どうして私はこんなことをしているのか？

  なぜ私は何度も救われた命を，みすみす捨てようとしているのか？

  いや，捨てるつもりはない。心の上ではそうだ。だが，下の方では，捨ててもかまわない，そう思っている。心の底から昇ってくる。

  帰還した翌朝までは普段通りだったはずだ。普段通りに食事をとり，トレーニングをしてから，ラウンジでシッショとともに報告書を書くつもりだった。だが，ふいに，なぜか，獣舎に足が向いた。何の気はない。キバとツメと遊ぶキセイを見にいくだけだ。それだけだ。キセイと目を合わせ，無口なキセイに朝の挨拶をするだけだ。それだけ。

  そこにキセイはいなかった。ゴリ，ワンワ，キバ，ツメもいなかった。ただジブーだけが後ろ足で首をかき，あくびをしていた。そんな。まさか。いや，知っている。朝の散歩。この時間だけ，ジブーは誰も見ていない。やめろ。だが足は勝手に進む。

  アルジはジブーの首を撫で，背中にまたがると，一気に走らせた。

  自分が里を出るのを誰か見たかもしれない。だが見つけたところで，誰に伝えたところで，ジブーには誰も追いつけない。

  脱走？表向きは。

  表？裏などない。いや，ある。言い分はある。あの鳥。自分と雷掌獣の戦いに水を差した鳥。アルジが昨日重脚鳥グリュンプリドと暫定的に名づけた鳥。あれを倒す。馬鹿な。倒せるわけがない。かなわないでも一矢報いるまで。無駄だ。死ねば調査隊員として敗北と同じだ。言い訳なんかいらない。正直に言え。

  そうだ。私は嫌になった。何をしてもオヤブンに認められることはない。会うたびに文句を言われる。私が口先だけの無能だからだ。規律を破るからだ。生意気だからだ。反抗的だからだ。身勝手だからだ。だから言葉で傷つけ，縛ろうとする。貶しておとなしくさせようとする。私は馬鹿だから，何度言っても聞かないから，どれだけ言っても外に出ようとする私のことだから，どれだけ傷つけようが，食事でもして一晩たてばケロッと直ると思っている。

  違う。私は全部覚えている。

  きっとお前は言うだろう。「そんなこと言ったっけ？」

  言った!言ったのだ!!

  だって，覚えて，直さなきゃ，同じことでまた怒られるからだ。殴られるからだ。拳で。鞭で。桶の水で。だから覚えた。直そうとした。でも直したはずなのに怒られた。全然できてない。前と言っていることが違うよ。私が直したから？私は直さなきゃいけないの？直しちゃいけないの？

  いうとおりにしろって なに？

  やめて。ごめんなさい。いうとおりにするから。いわれたとおりに，いいこにするから。

  だからもう ぶたないで。おねがい，○○○○○。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
