#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 083

  「非常識だ。キミ達は何を考えている」

  オヤブンの私室。その入口にもたれかかったアルジは頭の先から血まみれだった。すでに血は止まっているが，地面に捨てられた人形のように，力なく息をしている。その身体は奇妙に歪み，背骨や骨盤に異常があるのが明らかだった。すぐに治療をしなければ，本当に悲劇的なことになる。だが内開きのドアはそのアルジ自身が塞いでいる。小さなオヤブンが無理に動かそうとするのは危険だ。かといって外から人を入れようものなら，アルジの容態は悪化するどころでは済まない。アルジをどかせるのはケライのみ。アルジを人質として，三人を部屋に閉じこめている状況だった。

  「アルジさん」ケライが促す。苦痛に襲われながらも，アルジの意識ははっきりしている。「オヤブンさん，このたびは，勝手なまねをし，皆さんに迷惑をかけ，この体たらく，本当に，申し訳ありませんでした」アルジは小さく息を吐きながら，オヤブンに詫びると，なんとか肩から首をくたっと垂らして謝罪する素振りをとった。もはや顔を上げることもできないので，ケライが支えて頭を戻してやる。放置して首へ不要な負荷がかかるのを避けるためだ。

  「それで，怪我をおして謝罪すれば罪を償ったことになるのか。冗談じゃない。非常識だ。早く治療に向かいたまえ。処分は追って伝える。今すぐ出ていくのだ」本来なら勝手な脱走は最大級の罪である。調査隊の規律を乱すものとして，最低でも懲罰房におかれるレベルのものだった。

  「退室する前に，質問があるのですが，よろしいですか」ケライが口を開いた。「質問だと。一体なんだっていうんだ。そんな悠長に構えている余裕などないだろう。早くアルジくんを医務室に運ぶのだ。これは命令だ」「質問にお答えしていただけるまで運びません」「命令に背くのか」「質問にお答えください」

  オヤブンはふんっと鼻を鳴らすと座り直した。「いいだろう。言ってみたまえ。私が答えたらすぐ出ていくのだ。いいな」

  「ありがとうございます」とケライは礼を言って，その質問を明かした。

  「オヤブンさんは，これまで怪我をした隊員にお見舞いをしたことがありますか」

  即答して問題を片づけ，二人を追い出し，部屋にこびりついた血を拭くつもりだったオヤブンは予想外の質問にうろたえる。それまでの態度が一変し，視線が泳ぐ。まるで，オヤブンと接するときのアルジのようだ。

  「あー…うむ」

  返事のないまま，無言の時間が続く。ケライが何も言わないので，というか返事を待っているだけなのだが，沈黙に耐えかねたオヤブンが怒鳴るように言った。「それがなんだというんだ。そんな質問をするために怪我人をこんなところまで連れてきたというのか」

  「そんな質問」ケライは無表情でつぶやいた。

  「私はアルジさんの身勝手な行動といわれているものは，オヤブンさんの叱責に原因があると考えています」

  「なに？」さらに予想外の展開に，オヤブンは苛立った。「キミはこんなやつをかばってボクに文句を言うつもりか。無礼にもほどがある。ボクはアルジくんが勝手な行動で他の隊員に迷惑をかけているからそれを注意しているだけだ。何を勘違いしている」

  「こんなやつ」ケライは無表情のまま再びつぶやく。

  「これまでアルジさんが里の外へ一人で行こうとしたのは三度あります。いずれもオヤブンさんの叱責に随伴した行動です。一度目は私とアルジさんが初めてオヤブンさんとお会いしたとき。二度目は」「そんな御託は聞きたくない」「二度目は裂掌獣ザエルにシンキさん達が大怪我を負わされた後，そして三度目が今回です」「聞きたくないと言っているだろう。質問が済んだのに出ていかないとは，キミは約束さえも守れない人間なのか」「一度目はアルジさんを里に受け入れるのを躊躇し，追い出すかのような脅しをしました」「黙りたまえ」「二度目はアルジさんが両足を失い，そのことで叱られ，それでも資料を持って交渉に望んだのに拒絶されました」「黙れと言っているじゃないか」「三度目はボッチさん達の許可を取り付け雷掌獣の調査に向かい，無傷で帰還したにも関わらず成果がないと非難しました」

  「だまれ!」オヤブンは声を荒げた。「黙れと言っているのになぜ黙らない。とんだ言いがかりだ。だいたい悪いのは全部アルジくんじゃないか。なんの身分証もない人間を受けいれられるわけがないだろう。両足を無くしたのは不注意じゃないか。裂掌獣の資料だって不備があった。雷掌獣にしたってボッチくんの調査を後回しにしたんだから成果を求めるのは当然だろう。だいたいね，ちょっと叱られたくらいでへこたれるようじゃ困るんだよ。この地は危険で満ちているんだ。それくらい何でもないと耐えられるようでなきゃこの先だってやっていけんよ」

  「オヤブンさんがそんな叱責をしなければアルジさんは身勝手な行動をしなかったのではないかと言っているんですが。それに」「だったらミスをしても注意をするなというのか？そんな甘やかせるわけないだろう!」「それに，これまでの発言で，オヤブンさんは隊員を叱責することで，その隊員の命が失われるかもしれない，その危険性を考慮していなかったことが推察されます。自身の言葉が隊員に与える影響を軽視し，その結果隊員が失われることになろうと，それを隊員本人の責任とするような態度は，権威と責任を持つ組織の長の行動として疑問が残ります」

  「ボクに指図するのか!」オヤブンは度重なるケライの言葉に耐えきれず，真っ赤な顔を震わせて怒鳴る。

  「アルジさんは」そう言ってケライはしゃがみ，アルジの頬に優しく触れた。「全ての所持品を失ったにも関わらず，腕を失ってなお雪灯籠を単騎で撃破し，その素材を持ち帰りました。それがなければ，裂掌獣にシンキさんが襲われ，藍穿花の罠に落ちて私が傷ついたとき，私たち二人は助からなかったかもしれません。私たちを助けるために雪灯籠の捕獲計画を率先して実施し，任務の際，自身を投げ出してキセイさんを助け，かわりに足を失ったのに，誰を責めることもなく，義肢を身につけて現場に復帰しました。それだけではありません。裂掌獣との初遭遇で，シンキさんやボッチさんを助けるため，丸腰で裂掌獣の注意を引き，一人の死者も出さずに撤退させることに成功しました。それからも優れた洞察力で裂掌獣や雷掌獣の特性を見抜き，シッショさん，クビワさんとともに討伐する戦闘能力の高さも持ちあわせています。一人では報告書が書けない，その自分の実力のなさを素直に認め，他の人に教わろうとする謙虚さも持っています」

  「これだけの優秀な隊員を，適切でない叱責で追い詰めるのは，組織の長として誠実な態度とはいえないのではないでしょうか」そう言い終えてケライは立ち上がった。

  「言いたいことは済んだだろう。出ていきたまえ。ボクは今の状態のキミ達を里から追い出すほど残酷じゃない。だからキミ達を処分するのはアルジくんの怪我が治ってからにする。せいぜい，調査隊としての最後の時間を楽しむといい。言っていることはわかるな？ケライくん」

  「私たちを解雇するということですね」「そうだ。キミはいちいち専門書のような話し方をするから人の話を理解していないんじゃないかと思っていたが，それなりに分別はあるようだな」

  ケライは慎重にアルジをドアから離し，開いてからアルジを廊下に引き出すと，「短い間ですが，お世話になりました」と言って軽く頭を下げながら閉めた。

  「ケライ」ドアの外でアルジが小さくつぶやいた。「ありがとう。でも，ごめん」

  「私は」ケライはそう言いかけ，アルジを歩行器に固定するため身体を持ち上げたが，抱き締めたままなぜかすぐには離さなかった。自分があれだけの演説をぶったのはなぜか考えているようでもあった。やがてアルジを歩行器に掴まらせると，思い出したかのように言った。「不誠実な人が嫌いです」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
