#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 083

  「非常識だ。キミ達は何を考えている」

  オヤブンの私室。その入口にもたれかかったアルジは頭の先から血まみれだった。すでに血は止まっているが，地面に捨てられた人形のように，力なく息をしている。その身体は奇妙に歪み，背骨や骨盤に異常があるのが明らかだった。すぐに治療をしなければ，本当に悲劇的なことになる。だが内開きのドアはそのアルジ自身が塞いでいる。小さなオヤブンが無理に動かそうとするのは危険だ。かといって外から人を入れようものなら，アルジの容態は悪化するどころでは済まない。アルジをどかせるのはケライのみ。アルジを人質として，三人を部屋に閉じこめている状況だった。

  「アルジさん」ケライが促す。苦痛に襲われながらも，アルジの意識ははっきりしている。「オヤブンさん，このたびは，勝手なまねをし，皆さんに迷惑をかけ，この体たらく，本当に，申し訳ありませんでした」アルジは小さく息を吐きながら，オヤブンに詫びると，なんとか肩から首をくたっと垂らして謝罪する素振りをとった。もはや顔を上げることもできないので，ケライが支えて頭を戻してやる。放置して首へ不要な負荷がかかるのを避けるためだ。

  「それで，怪我をおして謝罪すれば罪を償ったことになるのか。冗談じゃない。非常識だ。早く治療に向かいたまえ。処分は追って伝える。今すぐ出ていくのだ」本来なら勝手な脱走は最大級の罪である。調査隊の規律を乱すものとして，最低でも懲罰房におかれるレベルのものだった。

  「退室する前に，質問があるのですが，よろしいですか」ケライが口を開いた。「質問だと。一体なんだっていうんだ。そんな悠長に構えている余裕などないだろう。早くアルジくんを医務室に運ぶのだ。これは命令だ」「質問にお答えしていただけるまで運びません」「命令に背くのか」「質問にお答えください」

  オヤブンはふんっと鼻を鳴らすと座り直した。「いいだろう。言ってみたまえ。私が答えたら出ていくのだ。いいな」

  「ありがとうございます」とケライは礼を言って，その質問とやらを明かした。

  「オヤブンさんは，これまで怪我をした隊員にお見舞いをしたことがありますか」

  即答して問題を片づけ，二人を追い出し，部屋にこびりついた血を拭くつもりだったオヤブンは予想外の質問にうろたえる。それまでの態度が一変し，視線が泳ぐ。まるで，オヤブンと接するときのアルジのようだ。

  「あぁ…うむ」

  返事のないまま，無言の時間が続く。ケライが何も言わないので，というか返事を待っているだけなのだが，沈黙に耐えかねたオヤブンが怒鳴るように言った。「それがなんだというんだ。そんな質問をするために怪我人をこんなところまで連れてきたというのか」

  「そんな質問」ケライは無表情でつぶやいた。

  「私はアルジさんの身勝手な行動といわれているものは，オヤブンさんの叱責に原因があると考えています」

  「なに？」さらに予想外の展開に，オヤブンは苛立った。「キミはこんなやつをかばってボクに文句を言うつもりか。無礼にもほどがある。ボクはアルジくんが勝手な行動で他の隊員に迷惑をかけているからそれを注意しているだけだ。何を勘違いしている」

  「こんなやつ」ケライは無表情のまま再びつぶやく。

  「これまでアルジさんが里の外へ一人で行こうとしたのは三度あります。いずれもオヤブンさんの叱責に随伴した行動です。一度目は私とアルジさんが初めてオヤブンさんとお会いしたとき。二度目は」「そんな御託は聞きたくない」「二度目は裂掌獣ザエルにシンキさん達が大怪我を負わされた後，そして三度目が今回です」「聞きたくないと言っているだろう。質問が済んだのに出ていかないとは，キミは約束さえも守れない人間なのか」「一度目はアルジさんを里に受け入れるのを躊躇し，追い出すかのような脅しをしました」「黙りたまえ」「二度目はアルジさんが両足を失い，そのことで叱られ，それでも資料を持って交渉に望んだのに拒否されました」「黙れと言っているじゃないか」「三度目はボッチさん達の許可を取り付け雷掌獣の調査に向かい，無傷で帰還したにも関わらず成果がないと非難しました」

  「だまれ!」オヤブンは声を荒げた。「黙れと言っているのになぜ黙らない。とんだ言いがかりだ。だいたい悪いのは全部アルジくんじゃないか。なんの資格もない人間を受けいれられるわけがないだろう。両足を無くしたのは不注意じゃないか。資料だって不備があった。ボッチくんの調査を後回しにしたんだから成果を求めるのは当然だろう。」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
