#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 084

  「どういうことなのか，言える範囲でいいから教えてくれないかしら」

  カーテンで閉ざされた治療室。その外で，ショムはケライの話を聞いていた。ボッチらが言うには，重傷のアルジをオヤブンの私室に連れていき，そこで口論となった。ショムが呼ばれたのはその後のことだ。怪我人を放っておいて口論に及ぶ，しかもその主がふだんは大人しいケライであることが信じられなかった。

  ケライは手の甲を擦りながら，うつむいたまま黙っている。「責めているわけじゃないの。ただ，二人に何があったのか知りたくて」「ボッチさんの言ったとおりです」

  「ええと，うーん，どうしようかな。少し座って話しましょうか。いま飲み物持ってくるから」だがケライは首を横に振る。ショムは腰に手を当てて溜め息をつく。

  「オヤブンさんへの謝罪を優先した理由は言えます？」「わかりません」「ケライさんがそれを伝えたとき，アルジさんは何て言っていましたか」「私が行くなら，行くと」「そうなのね…」

  やはりオヤブンへ喧嘩を売ったのはケライのほうなのだ。これまでと違い，アルジが仕掛けたものではない。

  「あの」自分の爪を触りながらケライが聞く。「アルジさん，治りますか」

  ショムはケライをひっぱたきたくなるのをこらえ，こめかみに指を当てて自身を落ち着かせた。

  症状を悪化させたのはあなたでしょう!それを自分の気が済んだからって他人に丸投げしておいて，治りますか？ですって？人の命を何だと思ってるの!

  そう頭の中でケライを叱り，現実に行っても何の意味もないことを確認し，深呼吸をする。

  「死ぬことはないと思います。おそらく。けれど，頚椎か，脊椎の神経が傷ついているかもしれないの。その場合は，身体の不随とか，後遺症が残るかもしれません」後遺症，という言葉にケライの身体が硬直する。

  「すみません」ケライの言葉に，謝っても遅い，と思いながらもショムは答える。「謝るならアルジさんが意識を取り戻してから，本人にね」ケライは視線をそらしたまま頷いた。

  ショムは口を抑えてあくびを噛んだ。「私は少し寝るから，ケライさんも無理しちゃだめですよ。待っていればアルジさんが早く目覚めるわけじゃないんだから」その言葉に再びケライは頷いた。

  <br>

  それからしばらく経った。

  ケライが廊下の隅に座り込み，顔を伏せているとドアの開く音がした。アルジが目を覚ましたのかと思い音のした方を見ると，微笑むシンキの姿があった。

  「や」シンキは手を挙げて挨拶をする。そのままケライの隣にやってきて布を敷いて座ると，袋から取り出したマフラーをケライの頭から被せた。

  「ね，すごい？あたしが作ったんだ。アルジさんに教えてもらったんだよ」

  「アルジさんに」鼻から下をマフラーで覆ったまま，もごもごと答える。

  「そそ。不器用なあたしでも作れるんだ。こんどケライもやってみようよ」

  ケライはその言葉に返事をしなかった。普段なら「はい」「いいえ」くらいは答えるのだが。よほど堪えているらしい。シンキは，ケライも動揺するのだ，と内心驚きながらも，アルジが失踪してからずっとケライはおかしかった。殺気のような気配があった。そして，その理由も何となくわかっていた。

  「アルジさんを守りたかったんだよね」

  アルジが失踪した日，あわただしかった里のなかで，ただ一人ケライだけが平静を貫いていた。だがミミから，前日に起きたオヤブンとアルジの出来事を聞いて豹変した。キセイが怯えるのも構わず，なかば脅すようにビュンの扱いを学ぶと，行き先だけを告げて里を発ったのだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
