#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 084

  「どういうことなのか，言える範囲でいいから教えてくれないかしら」

  カーテンで閉ざされた治療室。その外で，ショムはケライの話を聞いていた。ボッチらが言うには，重傷のアルジをオヤブンの私室に連れていき，そこで口論となった。ショムが呼ばれたのはその後のことだ。怪我人を放っておいて口論に及ぶ，しかもその主がふだんは大人しいケライであることが信じられなかった。

  ケライは手の甲を擦りながら，うつむいたまま黙っている。「責めているわけじゃないの。ただ，二人に何があったのか知りたくて」「ボッチさんの言ったとおりです」

  「ええと，うーん，どうしようかな。少し座って話しましょうか。いま飲み物持ってくるから」だがケライは首を横に振る。ショムは腰に手を当てて溜め息をつく。

  「オヤブンさんへの謝罪を優先した理由は言えます？」「わかりません」「ケライさんがそれを伝えたとき，アルジさんは何て言っていましたか」「私が行くなら，行くと」「そうなのね…」

  やはりオヤブンへ喧嘩を売ったのはケライのほうなのだ。でも，なぜ。

  「あの」自分の爪を触りながらケライが聞く。「アルジさん，治りますか」

  「!」ショムはたまらず怒りの表情をあらわにした。だがそれも一瞬だった。ひっぱたきたくなるのをなんとかこらえ，こめかみに指を当てて自身を落ち着かせる。

  症状を悪化させたのはあなたでしょう!それを自分の気が済んだからって他人に丸投げしておいて，治りますか？ですって？人の命を何だと思ってるの!

  そう頭の中でケライを叱った。改めて現実に行っても何の意味もないことを確認し，深呼吸をする。

  「できるだけのことはしています。でも今は何ともいえません。ケライさんが帰ってきてすぐに私のところに連れてこられればよかったんですけど」つらく当たらないよう心がけながら，我慢できずショムはケライの行動に釘を刺す。シンキの全身火傷やケライの刺し傷を治療したときも大仕事だったが，今回も負けていない。もしくはそれ以上だ。

  「すみません」ケライはうつむいたまま詫びる。謝ってどうにかなるわけではないのだが，責めたところでどうなるわけでもないし，それを裁く法の担い手はここにはいない。そしてショムは知らないが，すでに二人はオヤブンによる裁きを受けている。

  「アルジさん，最後に何か言ってましたか？」ショムが尋ねた。その言葉で，ケライは目を左右に動かし，記憶をたどった。「ありがとう，でも，ごめん。と言っていました」

  そうか。仮に，万が一の事態になったとしても，最後の言葉がかわせたのなら。いやいや。今そんなことを考えてはいけない。私の力を信じろ。ショムは自分を奮い立たせた。

  「謝るならアルジさんが意識を取り戻してから，本人にね」

  ケライは頷いた。

  ショムは口を抑えてあくびを噛んだ。「私は少し休むから，ケライさんも無理しちゃだめですよ。待っていればアルジさんが早く目覚めるわけじゃないんだから」再びケライは頷いた。

  <br>

  それからどれほどの時間が流れたか。

  ケライが廊下の隅に座り込み，顔を伏せていると，差し込む光とともに，人の気配がした。はっとして視線を上げるとアルジが座ったまま，こちらを見つめている。

  「おはようございます」反射的に挨拶をした。

  「ケライ。今までありがとう」「はい」「じゃあね」「…はい」

  <br>

  「あ，ダメです」

  ケライは思わず声を出した。その響きに，空気が変わっているのに気付く。あれは幻影だったのか。それとも。

  誰かが寄り添って自分の頭をなでている。首元が暖かい。太いマフラーが巻かれている。ケライが我に返ったことを，相手もわかったようだった。

  「ケライ，だいじょうぶ？」シンキだった。二人の様子を見に来たとき，落ち込んだ様子の，といっても伏せているのでそう見えるだけかもしれないが，ケライを見つけると，その隣に座り，時折うなされるケライが落ち着くまで寄り添っていたのだった。

  「大丈夫，とは」「アルジさんがいつ目を覚ましてもいいように，ケライが元気じゃないとね」「アルジさんにはさっき会いました」「え？」「夢の中だと思いますが」「アルジさん，何て言ってた？」「今までありがとう，じゃあねって」

  「ちょっと」思わず，励ます側のシンキが目を潤ませてしまう。「ひどいよシンキ，それじゃアルジさん死んじゃったみたいじゃない」何度も目を指でぬぐう。「アルジさん死んだんですか？」「いや，だからまだ生きてるって。それなのにケライがアルジさんと最後の挨拶したみたいなこと言うから」「最後の，あいさつ」「だからそれは夢だから。気にしちゃダメだよ。アルジさん応援しよ。ほら，頑張れアルジさんっ」シンキはそう言いながらケライの冷たい手を包み，上下に振る。

  「頑張れ，アルジさん」「そうそう」「死んだらダメです」「そう」「まだ話したいことがあるんです」「うん」「一緒に行きたいところもあります」「うん」「一緒に食べたいものもあります」「…」「まだ謝っていないことも」「…」「まだお礼を言っていないことも」

  ふだんは心を見せないケライがどれほどアルジを思っているのか，それを少しでも伝えられていたら。ここに来て泉のようにあふれだす言葉に，シンキはこらえきれず，ケライのマフラーに顔をうずめた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
