#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 085

  この章ではストーリーの進展はない。ゆえに，延々と続く地の文，それを嫌う読者は飛ばしてほしい。

  ケライはシンキの通訳で，事の経緯をショムに説明することができた。アルジが自分の不安定さに苦しんでいることはショムも知っていたが，オヤブンがそれほどのダメージを与えているとは思わなかったようだ。アルジはよほどの出来事，またはタイミングが重ならないかぎり，弱みを晒すことはしない。ふつう誰でもそうだろう。弱みを見せれば侮られるだけだ。今回のトラブルは，オヤブンの支配下にある里という環境でなければ生きられず，逃げられないという，不満を蓄積させやすい特異な状況ゆえに生まれたともいえる。それでもオヤブンがリーダーとして振舞える人物であればこの事件は起きなかったかもしれないが，なんとしても現状を守ろうとするであろうオヤブンの性格は，興味のままに突っ走ろうとするアルジの性格とそりが合わなかった。

  いや，本来はアルジが人間としてもっと大人の振る舞いができればこんなことにはならなかったはずだ。オヤブンとトラブルを起こすのはアルジだけなのだから。たとえばクビワやシッショは，はじめから言うことを聞かない，という姿勢を頑なに貫くことで折り合いをつけている。資源の管理をしているのはショムなのだから，ショムにさえ嫌われなければたいてい自由に活動できる。それをオヤブンの小言をいちいち気にして対応したがゆえに，自分の首を絞めることになってしまった。そりゃあ里の運営に影響を与えるほど勝手に振る舞えば咎められるだろう。だがその境界線がどこにあるのかを意識していれば，ルールを無視した身勝手な行動として槍玉にあげられることもない。

  アルジは自分ならできる，変えられると自身の能力を過信していなかったか。里ののんびりした雰囲気に焦り，急に物事を進めようとしすぎてはいなかったか。開拓はマッパに任せ，自分達は里の周辺で安全に暮らしていればこんなことにならなかったのではないか。

  そうかもしれない。オヤブンに疎まれることなく，里で平和に暮らしていればよかったのかもしれない。とはいえ，その代償として南との連絡がないまま資源が尽き，全滅するかもしれない。そもそも分別のあるような人間だったらこんな僻地に来ることもなかったはずなので，遅かれ早かれこんな問題が起きるのは避けられなかっただろう。

  仮にアルジのように何らかの行動を起こしたとして，それが例えば紫針竜の討伐につながるかといえば，それはわからない。里で待っていれば，南から新たな支援がやってくるかといえば，それもわからない。人事を尽くして天命を待つのか，果報を寝て待つのか，どのような結果になるかはわからないのだから，後悔のない方を選べばいいことだ。少なくともこの里では前者がアルジで，後者がオヤブンである。まあ，相性は最悪である。

  <br>

  ショムとケライの会話を聞くなかで，ふとシンキは，夜のキャンプでミミとアルジが話しているのを思い出した。翌日はボッチ団にとって最悪の事件が起きたから，あまり思い出したくもないだろうが，あの夜，もしかしたらアルジはミミを口説いていたのでなく，何か深刻な相談をしていたのではないか。そう思った。ふだんミミは自分に課される仕事に愚痴をこぼしてばかりだが，アルジにかんしては進んで技能をふるう。それは，アルジの悩み，苦しみの重さを知り，それを解いてあげたいと思ったからなのではないか。これまでミミからそうした話を聞いたことはないが，問いただす必要がありそうだ。

  もしミミだけがアルジの悩みを知り，誰にも言わないでいたのなら，ミミは何らかの予兆を感じていたはずだ。それを内緒にしていたことが罪というわけではないが，アルジの脱走を止められる機会をそこで逸したことになる。もちろんミミを責めるつもりはないが，ミミは責任感が強いので，自分を責めないように気を配らなければならない。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
