#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 086

  アルジの化け物じみた生命力はどこから来るのだろうか。ひとつは運動能力が高く，とっさの受け身で頭部を守るということが考えられるし，マッパがあちこちに作ったキャンプで最低限の治療が行えるよう設備が整えられているというのもある。ショムの医療技術も超人的である。だが一番の理由は，おそらくオヤブンにある。

  以前マッパが言ったように，オヤブンは竜人族である。人間，獣人に比べて特別な響きを感じるだろう。実際，竜人はその数こそ少ないものの，その長命と莫大な資本で知られ，誇り高い。まあ，ありていに言えば支配階級であり，人間などは使い捨ての道具としてしか考えていない者も多い。だが，その長命と引き換えに病弱で，それゆえ好奇心で一心不乱に何かに打ち込むとか，新たな知識を仕入れて自分の認識を改めるといったことが苦手である。新しいことには批判的で，古い考えに縛られやすい。それが一概に悪いというわけではないが，気力や活力の赴くまま，自分の知らない新たな世界に飛び出してゆく人間に，羨望と嫉妬という複雑な印象を抱いている。

  そのなかでオヤブンは異端である。豊富な資本という意味では他の竜人と変わらないが，財産を使って，体力のない自分の代わりに誰かが人助けや新たな発見をすることを求める。オヤブン自身もそういったことに興味はあるが，持続できるだけの力がないので，それをできる人にやってもらいたいのだ。調査隊を組織したのもそういう理由であり，こういうことをする竜人は極めて珍しい。報告書をしきりに求めるのも，新たな発見や出来事を手軽に知りたいからである。

  里や調査隊の施設，とくに医療設備が場違いなほど充実しているのかというのも，そうしたオヤブンの性格に由来するものである。オヤブンが求めることをしてくれるのは人間もしくは獣人しかいないので，その命や健康を何よりも大事にしているからだ。命が失われれば，もはやその人が発見できたはずのものを知ることができなくなる。だから必死に守ろうとするし，そのためのコストは惜しまない。たまに竜人らしいプライドの高さは現れるものの，オヤブン自身，自分の足りないところを理解し，配慮しているつもりだった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
