#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 087

  この章でもストーリーに進展はないので，時間を進めたい読者は次の章へ進んでほしい。

  ショムにとってアルジの治療が大仕事になっているのはケライが原因である。そもそもなぜオヤブンが見舞いに訪れないのかというと，血を見ると卒倒するほどの臆病だからだ。そんな相手に血まみれのアルジを放り込み，しかも密室状態で口論になったものだから，オヤブンが受けた心の傷は想像するに余りあるほど深い。ゆえにショムはオヤブンが何か訴えるたびに，落ち着くまでじっくり時間をかけ対応する必要があった。こういうときだけは無駄に体力があるのがオヤブンの厄介なところだった。ショムにかかる身体的な負担は大きく，しかも十分な休憩もとれないまま，再度自身を消毒してアルジの治療に戻らなければならない。ミミの補助によってなんとか維持できているものの，ミミ自身も包帯の交換などで痛々しい身体を見なければならない。それはつらい。しかもその対象がアルジなものだから，冷静でいつづけるのさえ大変だ。アルジの意識がなく，苦痛を訴えることがないのがせめてもの救いである。

  ケライが大人しい，というか無口なのをいいことに，ボッチは里のガタガタな状況を非難しようとするし，それをシンキは守ろうとするが，ボッチを敵対させてはいけないので，その絶妙なさじ加減を保つのは困難である。かたやシッショとクビワは我関せず，というか，シッショも心配しているもののケライがオヤブンを怒らせたことは面倒なことになったと思っているし，クビワは「なげればジブーよりはやくはこべた」と皆を混乱させることしか言わないのでなるべくケライ達から避けておかねばならない。キセイは里のピリピリした雰囲気がペットに伝わるのを防ぐため，その対応に追われている。あいにくマッパは里にいない。というかあの性格では混乱を助長させるだけなので里にいないほうがよい。

  怪我人によって里が暗い空気に包まれるのも問題だが，険悪になるのはもっとまずい。当然アルジとケライが解雇されたことはケライの口から語られているが，これだけ相手を怒らせたのでは，里にいられるようシンキ達が頼みこんでも受け入れられないだろう。おそらくその際に鍵になるのはショムであるが，ショムは自分の身体がこれほどボロボロなのはケライがオヤブンに喧嘩を売ったことが原因だと思っているので，仲介役を引き受けるとは考えにくい。あとは，アルジとケライが里に残る道はオヤブンへの全てをかけた謝罪であるが，ケライはオヤブンが変わらないかぎりまた同じことが起きると思っているので拒否している。まあ，オヤブンはアルジを目の敵にしているから，今後もことあるごとにアルジを貶すだろう。

  実力行使でオヤブンを追い落とすことはできないかといえば，まあ後のことを考えなければできる。実際，誰一人としてオヤブンを支持していない。だが一方でオヤブンを追い出したいほど不満を持っているのもアルジとケライくらいしかいない。気にくわないから自分がリーダーになりました，といったところでクビワくらいしかついてこない。何よりオヤブンの地位を剥奪した場合，南へ帰れなくなる。「隊長としての素質がないので私たちが解雇しました」と言おうものなら，他の竜人に「ではお前達には生きる資格がないからその命を解雇します」と速やかに処刑されるからだ。

  オヤブンとアルジ，ケライが歩み寄れるのが一番だ。それは皆が思っていることだろう。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
