#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 088

  閉鎖された環境は，悪魔の声を聞きやすくする。

  その日も治療室の前でケライは長椅子に腰かけ，何をすることもなく時間を過ごしていた。里の隊員でなくなったケライには，自室と鍵のかかっていない場所，すなわちラウンジとこの場所程度しか居場所が残されていないのだ。好きな本も読むことはできず，自分が以前まとめたメモを読み直し，気付いたところに筆を入れる程度である。顔には出さないが，とても寂しい思いをしているだろう。

  そのとき，治療室からミミが出てきて，珍しくケライの横に座った。普段は疲れはててそのまま自室に向かうことがほとんどなのだが。

  「ケライさん」とミミは呼びかけた。「はい」と返事がかえってくる。

  「アルジさんだけでもこの里に残ってもらえるよう，オヤブンさんに謝ってくれませんか」

  その言葉を発した瞬間，ミミの全身をおぞましい寒気がはしった。もう帰れない感じがした。

  「オヤブンさんとショムさんに相談しました。ケライさんが謝ってくれれば，アルジさんは里においてこれからも治療が行えるそうです。それに，今までのように責めることもしないと」

  その言葉にケライが顔を上げ，ミミを見る。「本当ですか」「ええ。嘘じゃありません」

  嘘ではない。だが。

  「アルジさんの義足や義手を作ったり，その他の面倒も私なら見ることができます。それに，アルジさんは私だけに悩みを打ち明けてくれます」それも間違いではない。

  「アルジさんは，ケライさんに悩みを相談したことがありますか」

  ケライは記憶をたどる。「ありません，たぶん」

  「ケライさん。アルジさんのこれからのこと，私に任せてくれませんか。そうすれば，必ずアルジさんを助けます。約束します」

  ミミの言葉を受け，ケライは考えた。確かに自分はアルジの心が傷ついてもそれを癒すことはできないし，失われた手足の代わりになることもできない。自分が謝ることで，それらを解決できるなら。

  ミミは動悸が治まらなかった。鼓動がケライに聞こえるのではないかと思うほどだった。

  それは恐ろしい計画だった。

  誰が言い出したわけでもないものだった。限界を感じたショムは，オヤブンの身の回りをケライに任せようとした。また，アルジを人質とすることで，オヤブンはケライに負わされた屈辱を晴らそうとした。そしてミミはアルジを独り占めできる。誰ひとり里から失われることなく，問題は解決する。竜人族が悠久の昔から培ってきた，人間を苦しめる方法は星の数ほどある。それらを好きなだけ駆使し，ケライの心身をボロボロにしようと，ケライはアルジを守ろうと耐えるだろう。それを想像すると，オヤブンの心に秘められていた竜人の血が騒ぎ出すように感じた。

  初めてそれを聞いたとき，ミミの身体は半分に割れるような気がした。だが，時間が経つにつれ，どす黒く粘ついた糸が，残りの半身を覆いつくしていった。ミミはその提案を受け入れた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
