#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 089

  わかりました。その言葉にミミの力が一気に抜け，思わずケライにもたれかかってしまった。

  「すみません」ミミが身体を離す。「大丈夫ですか。無理しないでください」何も知らないケライは，自分を悪魔に差し出そうとする者にいたわりの言葉をかけた。

  「じゃあ，オヤブンさんが待っているので，オヤブンさんの部屋に行ってください」「こんな時間にですか」「はい，オヤブンさんも早くケライさんと和解したいのでしょう」なぜ自分の心はこれほど乱れているのに，こんな嘘がぺらぺらと出てくるのか，不思議で仕方なかった。だがこれでいい。もうケライと会うこともないのだから。

  <br>

  ケライは，わかりました，と言い立ち上がると，ミミにお辞儀をした。改めて小柄な人だなとミミは思った。こんな小さな身体で，支配者たる竜人の暴力から，大切な人を守ろうとしたのだ。

  「ミミさん，今までお世話になりました。アルジさんのこと，お願いします」

  おそらく自分が里を離れると思っているのだろう。別れの挨拶だった。

  「アルジさんが元気になってくれるなら，私，しあわせ，です」

  幸せ…？ケライはアルジに二度と会えなくなるのに，なぜそんな気持ちでいられるのか。そうだ。ケライはミミを信頼しているからだ。ミミならばアルジを元気にできると信じている。だから，自分が会えなくなっても幸せ…なのだ。

  「…はい。まかせてください」思わぬ言葉にミミはうわずった声を出してしまう。

  再びケライは頭を下げると，ラウンジへ続くドアに向かっていった。

  終わりだ。ふっとミミの内にそんな言葉が浮かんだ。

  <br>
  <br>

  「待って!」

  それはケライがドアに手をかけたときだった。背後から響く声に振り向くと，その身体がミミにきつく抱きしめられた。

  「だめ，行っちゃダメ。ダメ…です…」ミミの身体と声がぶるぶると震えている。いったい何が起きたのかわからず，ケライは混乱する。

  「あの，ミミさん，離してくれないとオヤブンさんのところに行けません」「だめです，行ったら…」そう言ってミミは嗚咽を漏らし始めた。「ミミさん，泣いてるんですか。どうして」「ごめんなさい，ケライさん，ごめんなさい…私，なんてことを…」

  それから，ごめんなさいとひたすら繰り返しながら，ミミはケライを抱いたまましばらく涙を流した。ケライは肩越しにミミの涙と熱を感じた。

  <br>

  オヤブンの部屋をノックする音があった。予定していた時間よりもかなり遅い。だが大した問題ではない。オヤブンは自分の玩具をどうやって遊ぶか，壊すか，そればかりを考えていたのだ。

  オヤブンが返事をすると，ケライが入ってくる。うまくいったか。と，その後に目を赤くしたミミが続いた。オヤブンとショムは怪訝な表情でミミを眺める。ミミはケライの前に立って，向かいあう二人に目を合わせた。

  何らかの問題が生じたに違いない。オヤブンとショムはさとった。

  「ケライくん。ミミくんから話はあったと思うが…」

  「そのことですが，私の方からお話があります」ミミがオヤブンとケライの間に割って入った。ひどい鼻声だった。「…なんだね」

  ミミは姿勢を正し，軽く咳をしてなんとか声の調子を取り戻すと，オヤブンの目を見て毅然とした態度で言った。

  「私たちは，罪のない人にひどいことをしようとしています」

  事前にミミは説得の場面を模していくつかの言葉を用意していた。だがそれらの言葉は出てこなかった。溢れる罪の意識が涙となってミミの目を押し出そうとする。それは忍耐の限界を容易にのりこえ，大粒となってミミの頬を流れ落ちた。

  向かいあった二人はハッとする。

  部屋を支配していた黒い空気が，一滴の涙で晴れあがるように見えた。

  「お願いします。二人…とも，考え直してくだ…さい」それを言い切り，ミミは声をころして泣き始めた。次の言葉があるようなのだが，しゃくるばかりでいっこうに出てこない。

  「わたし，たち，は，ひどい…うぅ…ひどい，こと…うぅっ」ケライを抱きしめ，その小さい身体を守るようにして泣き続けた。もはやケライの上着はミミの涙でびしょびしょだった。

  だがミミは相手の分も代わりに泣く力があるのだろうか。ショムとオヤブンが持っていたケライへの憎しみはみるみるうちに消えていくように感じた。二人は目を合わせ，自分達が正気を取り戻したことを確認しあった。

  もしあのときミミが止めていなかったら，一旦動き出した歯車は誰にも止められなくなっていただろう。しかしミミは，里が黒く染まる前に勇気を出し，悪魔のささやきを振り払って訴えた。もしオヤブンが生きて南へ帰れたら，この出来事は人生における重要な転換点のひとつとして記憶に残りつづけることだろう。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
