#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 090

  間もなく全員へ，アルジとケライを再び里に受け入れることになったと通知がなされた。状況に振り回されるボッチは険しい顔だ。だがぼんやりしている時間はない。早朝から，マッパが要求する資材を獣車に積み込む仕事にとりかかった。針山で設営する拠点の目処がついたためだ。二台の獣車はフル稼動で里と予定地を行き来している。かたやアルジは呑気に眠っている。峠を越え，意識が戻るのを待つだけだった。アルジが怪我をしてからというもの，里の状況は激変につぐ激変を経て，ようやく落ち着きを取り戻しつつあった。

  ボッチが仕事を始めてしばらくして，シンキが朝食をとるためにラウンジに下りてくると，ふだんケライが座っていた場所に異様なものを見つけた。

  一見すると，大柄なケライに小柄なケライが収まり，二人羽織のようになっていた。具体的にはミミの膝上にケライが座っているのだが，奇妙なことに，なぜかケライの唇がミミに吸われている。その様子は見ているこちらが赤くなるほど濃厚で，激しい。ミミからの一方的なアプローチのようだった。ケライの両足は挟まれ，両腕にはミミの腕が巻き付けられているため，身動きできない。そのまま，残ったミミの手で顔を固定され，なすがままだ。呆然とするシンキに気付いたケライはミミの口から逃れようとするが，目を向けるのが精一杯である。二人にそんな関係はなかったはずだが。ケライが起きてきたところをミミに捕まったのだろうか。だがなぜこのような状況になっているのか。

  ふとシンキはミミのトレードマークである，普段は垂れ下がった大きな耳がピンと立っているのに気付いた。

  あー，あれか。

  シンキは思い至ることがあった。ミミは極度のストレスや激しい感情を長時間経ると，その後安全が確保された環境で信頼できる相手に深い愛情表現を示すことがある。それが獣人に由来するものかは不明だが，以前はキセイがその被害を受け，そのとき受けた恐怖から人見知りに拍車がかかるようになった。いつも怖そうなボッチや快活なシンキに比べればまだミミの方が接しやすいものの，またいつあのような目にあうか怯えている。

  かなりの潔癖であるボッチがこの状況を見たら卒倒しかねない。とはいえこの二人を動かすのは難しい。シンキは広場に飛び出し，ボッチに軽い挨拶だけすると書庫に向かった。その後ラウンジと書庫を何往復かして，本の山で二人を覆った。これなら，ケライが今までのように読書にいそしんでいるように見えるだろう。

  「シンキ，こっちを手伝えよ」仕事をさぼっていると勘違いしたボッチがシンキのところにやってくる。汗だくのシンキは「あ，ごめん。まだ朝たべてないんだ」と詫びると，急いで食事をとって広場へ駆けた。ボッチを混乱から防ぐためとはいえあまりにも非情であった。本の山に囲まれたシンキは唯一の助けを失い，ミミにそれから長い間拘束されることになった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
