#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 092

  「おい，お前に聞きたいことがある」そう言ってマッパはアルジに歩み寄った。「アルジさん，大丈夫ですか？ずっと意識がなくて」その後ろをあわててショムがついてくる。

  その言葉に，アルジはこちらを向かずに答えた。首に巻かれたギプスのせいで首を動かせないのだ。「ええと，マッパさん，と，ショムさん，ですか」

  「お前と戦った鳥が里に近付いてる。お前の話を聞かせてもらうぞ」そう言ってマッパは乱暴にアルジを肩にかついだ。激痛にアルジが声をあげる。「何やってるんですか!やめなさい!」ショムはマッパの強引さを責めるが，一切聞かず，アルジをかついだまま出口のドアを開いた。

  <br>

  「アルジさん」

  部屋の外にはミミとケライが立っていた。「ミミさん？」アルジの顔はマッパの背中に向けられているため，声だけで顔を見られない。「アルジさん，意識が戻ったんですか」

  「ケライ，そこにいるの？ケライの匂いがする」身体をもぞもぞと動かして，尻で挨拶するような形になる。

  「はい」ケライの声だ。

  「ケライ…」

  マッパは二人を無視し，足を進める。その後ろを三人がついてくる。顔を上げられないアルジは足元を見ることしかできないが，間違いない。あの足はケライのものだ。ケライ。早く顔が見たい。

  やがてラウンジへ帰ってきたマッパは，またしても雑にアルジを下ろした。「痛っ」「乱暴はやめてください!」ミミがそう言ってアルジをかばうように抱く。アルジは痛みがひどいのか，肩で息をしていた。

  マッパはドスン，と音をたてて椅子に座り，他の者も席につくよう顎でうながした。ミミはアルジを膝の上に座らせ，痛みがやわらぐよう背中をさする。その隣にはケライが座った。

  「ケライ」視線の端でアルジはケライの姿を捉え，無事な様子に安心する。「アルジさん」ケライも珍しくアルジの呼びかけに素直に応じた。

  「再会の挨拶はそこまでだ。時間がない。アルジ，お前を半殺しにした鳥について知っていることを話せ」

  「鳥。狡舞鳥グリュンプリドのことですか」

  それを聞いたボッチは，黙ったまま手元の資料ではじめに巨脚鳥と書かれていた部分に斜線を引き，改名を示す記号と命名者であるアルジの名前を入れた。二度目の接触でアルジは改名に値する何らかの情報を得たのだ。

  「名前のことは知らんが多分そうだろう。早く言え」「その前に，いくつか質問があるんですが」「駄目だ。鳥のことだけ答えろ。それ以外のことは許さん」

  今日が何日か，里の状況はどうなのか，何もわからない状況で起き抜けに痛めつけられたアルジはかわいそうだ。だが今は急を要する事態である。

  「状況がわからないので答えられません」「じゃあ状況がわかるように歯を一本ずつへしおってやろうか」「いい加減にしてください!」ミミが大声で非難する。だがそれですらアルジの骨に響き，痛みがはしった。

  「どうしてそんなに焦っているんですか。何が起きてるんですか」合間に浅い呼吸をはさみながら，アルジはなんとか声を出した。痛みで深く息を吸えないのがつらい。

  「そいつが里を襲うことになるかもしれない」

  ああ，そういうことか。だがそれはあまりにも危険な状態なのではないか。もしかしたら自分が寝ているあいだに，里はとんでもないことになってしまったのではないか。アルジは心配した。

  「だからそいつがこっちを見つける前に倒さなくてはならん。早く知っていることを言え。次に口ごたえしたら本当に歯を折る」

  その言葉にミミはひきつった。アルジを両手で抱き，マッパから距離をとろうとする。長々と話せる体力はない。最低限の声で最大限の情報を与えるには。

  「クビワさんなら倒し方を知っています。呼んでください」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
