#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 093

  クビワがラウンジに姿を現したとき，アルジがはじめに感じたのはその美しさだった。自分が離脱しているあいだも，クビワは当然のように，日々の鍛錬を欠かさなかった。たゆまぬトレーニングに加え，キバやツメといった自由闊達な野生と共に過ごすと，これほどまでに整った肉体に仕上がるのか。その肌は透き通るほど瑞々しく，酸素をたっぷり含んだ筋肉が動くたびに，餅のようなやわらかさであることを伝えてくる。

  アルジは身体の負担を避けるため，ラウンジのソファに座ってミミによりかかっていたのだが，クビワに思わず見とれてしまった。それを勘違いしたのか，ミミは身体をよける。支えを失ったアルジは倒れ，痛みに声をあげた。

  だがクビワの端正の整った身体つきはマッパも魅了したようだ。「ほう，よく鍛えているな」とつぶやいた。

  「アルジ，おきろ。クビワさまがきてやったぞ」

  アルジが話し出す前に，マッパが問う。「アルジならお前がデカい鳥を倒せると言った。どうやって倒すんだ」

  「でかいトリ？」「水の原っぱで会ったあの鳥のことだよ」シッショがわかるように説明した。シッショは先のミーティングにも当初から参加していたのだが，会議には興味も知識もないため発言しなかった。それに，知っていることはボッチに渡した資料に全て書いてある。それはマッパがロクでもない資料と馬鹿にしたものだ。間接的に自分を侮辱されたシッショは内心で不満を抱えていた。

  「ああ，あれか。どうやってたおすんだ？」

  マッパはその答えにきょとんとする。

  やがて自分が騙されたことがわかり，ソファのアルジを睨みつけた。

  「待ってください。クビワを呼んだのには理由があるんです」

  だがそれは言い訳にしか取られない。怒りを込めた足音で迫ると，かばうミミをはねのけ，首のギプスを掴んで床に叩きつけた。シンキらの悲鳴があがる。

  「やめろ!」ボッチがあわてて二人を引き離そうとするが，マッパはボッチをつきとばす。バランスを崩したボッチはテーブルをなぎ倒すようにして豪快に倒れこんだ。「ボッチ!」後頭部を抑えるボッチにシンキが駆け寄る。

  「俺はな，嘘をつかれるのが一番嫌いなんだ」そうアルジの胸を押し潰しながらマッパは言う。

  だがアルジはつとめて冷静にふるまった。「私を殺したら，誰も，倒せなく，なります。いいんですか」「なに？」

  迷いのないアルジの言葉にマッパの力がゆるむ。すると，ふいにマッパの首が何かに引っ張られ，その身体がくるくると宙を舞う。そしてボッチよりもはるかに強い力で壁に叩きつけられた。

  「なにやってるんだおまえら」

  クビワがあきれるのももっともだった。クビワがやってきてから，マッパはアルジに喧嘩を売り，ボッチをつきとばし，そしてケライの釣竿で壁にぶつけられた。

  「マッパさんやめて!アルジさんが何か言ってます!」ショムが叫んだ。その声に，怪我を負ったボッチとは対照的に無傷のマッパが立ち上がる。だが視線はケライに向けられ，俺に勝負を挑むとはいい度胸だとでも言わんばかりだ。

  「ショムさん，アルジさんの傷口がひらいて」アルジを抱きかかえたミミが赤い手で心配そうに言う。

  まずい。収拾をつけなければ。

  <br>

  「人の話を聞けっ!」

  <br>

  アルジが渾身の力で叫んだ。その声にようやくラウンジが静寂を取り戻す。

  だがアルジは苦しそうに息をするばかりだ。マッパは無表情で身体の埃を払うと，腰を下ろしたままのボッチに手をさしのべ，「悪かったな」と謝る。ボッチは「いえ」とだけ言ってその手をつかみ，立ち上がった。

  冷たい視線がマッパに向けられる。それで傷つくような人物ではないが，いずれにせよ何かを知っているアルジからこれ以上聞き出すのは不可能だった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
