#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 094

  この章ではストーリーに進展はない。翌日に時間を進めたい読者は飛ばしてほしい。

  それから治療室に運ばれたアルジはしばらく怪我の痛みに苦しんだが，やがてそれが和らいだのか，ようやく眠りにつくことができた。治療室の外ではケライが座っている。まるで時間が巻き戻されたようだ。ケライの顔に光が差し，治療室からミミが顔を出した。中からケライを手まねきする。

  ケライが入るのは初めてだ。ベッドの上ではアルジが身体を横に曲げて眠っている。時おり口につけられたマスクから，空気の流れる音がした。

  「背中をケガしているので，あおむけに寝られないんです」ミミが小声でささやく。「さっき背中の傷口が開いたんですか」ケライは普段のような大きさで声を発したため，ミミは慌てた。「アルジさんを起こさないよう，小さい声でしゃべりましょうね」「はい」

  処置が済んだからだろうか，ミミは室内の明かりを消した。「私は今から寝ます。もしアルジさんが苦しそうだったら，身体を優しくなでてあげてください。たぶん，ケライさんがしてあげるのが一番落ち着くから」「はい」「あと，もし呼び鈴が鳴ったら，隣室のショムさんをすぐに呼んでください」「はい」ショムはいつでも緊急事態に対処できるよう準備しているのか。これでは怪我人の対処に参って当然だ。

  「あ，言い忘れた」部屋を出る前に，思い出したようにミミが振り返った。「ケライさんも疲れたら休んでくださいね。無理はダメですよ」「はい」

  <br>

  二人きりになってもケライは何をすることもなくアルジを見ていた。視界の対象が治療室のドアからアルジの寝顔に変わっただけだ。

  「ケライ」

  ふいにマスク越しにアルジが話したように聞こえた。「はい」ケライが返事をする。だがその目は閉じられている。気のせいか。

  「ケライ」また呼びかける声があった。「はい」ケライも再び返事をする。

  ゆっくりアルジの目が開く。

  「ケライ。会いたかった。ずっと」感極まったのか，アルジの目がにじむ。と，その目頭にケライの指が伸び，ぐっと抑えた。

  「人前で泣いたら負けです，アルジさん。侮られますよ」「…はい」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
