#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 095

  アルジの容態は悪い。ようやく意識が戻るほど回復したのに，マッパが無理をさせたからだ。体力も落ちているし，今度はどうなるかわからない。

  そんな居心地の悪さを文字通り肌で感じながらマッパは昼食をとり，夕方を待って里の外へ出ようと思っていた。すると，何枚かの紙を携えたケライに呼びとめられ，

  「アルジさんからの連絡です。昨日，言えなかったことを，もし目覚めなかったら代わりに伝えてほしいと」言ってきた。

  ケライは，目覚めない，の意味を，寝る，と誤解したようだが，それは里の将来やマッパにとって好都合でもある。

  マッパが紙を受け取ろうと手を伸ばしたが，ケライは隠した。中身を見られたくないようだ。「私が説明します」「時間の無駄だ。読むから渡せ」「だめです。読めません」「…わかった。じゃあ言え」

  短い押し問答のあと，二人はテーブルに向かいあって座った。マッパは具体的に何が書かれているのか気になるが，頑なに隠そうとするのであきらめた。ただ，そんなくだらないやりとりも，冒頭の「狡舞鳥を餌付けする」，という一言で終わる。

  「餌付け？その鳥を里で飼うってのか？」マッパの目が変わった。

  「飼うとは言っていません」「まあいい。つづけろ」

  なぜアルジは，当初クビワが狡舞鳥の倒し方を知っていると思ったのか。それは初めて狡舞鳥に接触し，そこから逃亡した際「なんでにげた？」と言ったからだ。そのときはクビワが戦えなかったのを残念に思っていたのだとアルジは考えていた。

  だが昨日の「どうやってたおすんだ？」の問いで，クビワがもともと狡舞鳥を倒す気がないのがわかった。クビワは怪我人を投げて飛ばそうと考えるような人物である。敵をどうやって倒すのか聞かれれば「なぐる」と答えるだろうし，もし初めから敵わないとわかれば，アルジたちが逃げることを不思議にも思わないはずだ。

  ということは，狡舞鳥はアルジが勝手に敵視していただけで，相手はそう思っておらず，クビワはそのことをわかっていた可能性がある。あれほど巨大なモンスターだが，クビワにとってはダモスや小動物などと変わらないかもしれないのだ。

  だとすると。「ここだと演説を聞いているようでつまらんな。少し待っていろ」そう言ってマッパはラウンジを出て行った。

  しばらくして，大声とともにマッパに抱きあげられたミミが入ってくる。「ちょっ，どこさわってるんですか!やめてください!」

  マッパは乱暴にミミを椅子に下ろし，痛がるミミを無視してケライを見ながら言った。「こいつにも話せ」「何をですか」「わからんのか？鳥の餌付けだ」

  「鳥の餌付け？」尻をさすりながらミミが二人を見る。「アルジを半殺しにした鳥を餌付けできるってこいつが言うんでな。お前の意見を聞きたい」「ケライさんがそんなことを？」「アルジさんです」「アルジさんが？いつですか」「昨日ミミさんが寝た後です。もし自分が目覚めなかったら，代わりに伝えてほしいと」「そんな…」ミミの目に涙が浮かぶ。朝に手当てしたときは落ち着いていたように見えたのに。

  「誰でもいい。早く話せ。時間が惜しい」二人の会話がコントのようで苛立ったマッパはケライを急かす。だがそんな薄情な様子にミミが怒りの目を向ける。「誰のせいだと思ってるんですか。怪我人にひどいことをしたのはあなたの」「過ぎたことだ。非難は問題が済んでからにしろ」「…人でなし」「おい，今わざと聞こえるように言ったな？」「事実を言ったまでです。人でなし。薄情者。変質者。時間が惜しいならこんなことに反応している暇はないのでは」「暇がないから怒らせていいってのか。里の連中はとんだ無能ばかりだな」「モンスターを唯一知っている人に重傷を負わせておいて，よくそんなこと言えますね」「あ？人の落ち度を追及して得意気だな，それで勝ったつもりか」「どうしてなんでも勝ち負けに結びつけようとするんですか，そんなことだから…」

  それを眺めるケライは，まさにクビワの言う「なにやってんだおまえら」な状態であった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
