#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 095

  アルジの容態は悪い。ようやく意識が戻るほど回復したのに，マッパが無理をさせたからだ。体力も落ちているし，今度はどうなるかわからない。

  そんな居心地の悪さを文字通り肌で感じながら昼食をとり，夕方を待って里の外へ出ようと思っていたところを，何枚かの紙を携えたケライに呼びとめられた。

  「アルジさんからの連絡です。昨日，言えなかったことを，もし目覚めなかったら代わりに伝えてほしいと」

  ケライは，目覚めない，の意味を，寝る，と誤解したようだが，それは里の将来やマッパにとって好都合であった。

  マッパが受け取ろうと手をのばすのを，ケライが隠す。「私が説明します」「時間の無駄だ。読むから渡せ」「だめです。読めません」「…わかった。じゃあ言え」

  短い押し問答のあと，二人はテーブルに向かいあって座った。マッパは具体的に何が書かれているのか気になるが，頑なに隠そうとするのであきらめた。だが，冒頭の「狡舞鳥を餌付けする」，という一言でマッパの目が変わる。

  「餌付け？その鳥を里で飼うってのか？」「飼うとは言っていません」「まあいい。つづけろ」

  なぜアルジは，当初クビワが狡舞鳥の倒し方を知っていると思ったのか。それは初めて狡舞鳥に接触し，そこから逃亡した際に「なんでにげた？」と言ったからだ。そのときはクビワが戦えなかったのを残念に思っていたからだ，と考えていた。

  だが昨日の「どうやってたおすんだ？」の問いで，クビワはもともと狡舞鳥を倒す気がないのがわかった。怪我人を投げて飛ばそうと考えるような人物である。敵をどうやって倒すのか聞かれれば「なぐる」と答えるだろうし，もし初めから敵わないとわかれば，アルジたちが逃げることを不思議にも思わないはずだ。

  ということは，狡舞鳥はアルジが勝手に敵視していただけで，相手はそう思っておらず，クビワはそのことをわかっていた可能性がある。あれほど巨大なモンスターだが，クビワにとってはダモスや小動物などと変わらないかもしれないのだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
