#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 100

  「待て。全ての箱に番号を振ろう」

  シートで目隠しがされたケライの部屋。その外に，シッショとボッチがなぜか半裸のまま立っている。

  一人での調査が不可能だと考えたシッショは，書類仕事にそこそこ詳しいボッチに助けを依頼したのだ。とはいえ，ボッチが加わるには二つの問題がある。ひとつはボッチにもスパイの疑いがあるため，ケライの部屋で工作活動ができないよう対処しなければならないこと。もうひとつは，ボッチがトイレなどで席を外すたびに持ち物検査をするのは面倒にもほどがあること。これを解決する手っ取り早い方法が，はじめから何も身につけない，というものだった。まあ，裸になったところで隠す場所などいくらでもあるのだが，そうした相手ならシッショも経験しているから対処できる。

  とはいえ，マッパに加えてシッショとボッチまで服を着ないというのは里の公衆衛生を著しく下げることになる。そこで，二人が主に作業するケライの部屋だけでも目隠しをしようということになったのだ。それが済んで，早速調査を始めようというところで先のボッチの言葉が出た。

  ケライの部屋はそのガサツな性格がはっきりとわかるほど，机付近のわずかなスペースをのぞいて書類と本で埋めつくされていた。ヘタに動けば山が崩れる。調査だけなら全ての書類をかき出して調べればよい。だがそれには大きな問題がある。ぐちゃぐちゃなように見えて，おそらくケライはどこにどんなものがあるのか何となく覚えている。ケライの作業量に比して収納が少なすぎるため，このような状況になっているだけなのだ。ゆえに，その位置を崩してしまったら，これまでのケライの調査が全て水泡に帰すことになってしまう。もしそのことをボッチが指摘しなければ，ケライが解放されても里にとって甚大な被害が出ていただろう。名誉のために言っておくが，ボッチはケライがこんな部屋にした気持ちはわかるけれども，ボッチ本人は極めて几帳面，悪く言えば神経質なので，その部屋は綺麗に片づけられている。

  ボッチに従い，室内のレイアウトと共に部屋の中にある山にいくつもの番号を振り，順番に調べることになった。なお，ミミの部屋はケライの部屋を通りすぎた先にあったのだが，こんな様子の二人を見るわけにはいかないので，調査が終わるまではシンキの部屋で過ごすことになった。二人が作業をする近くであわただしくパタパタと駆ける音がすれば，それはミミのものである。

  <br>

  ケライは本当に良く調べ，分析の方面でショムを助けていたようだった。ふだんはラウンジで無口なまま本を読んでいるだけのようにみえて，誰よりも勉強をしていた。ベッドに散らばる資料がそれを物語っている。疲れて机で寝た夜も珍しくないだろう。

  健気だ。ふいにボッチはそう思って首を振った。

  ただシッショにとっては，これだけケライが調べていることは好ましくないことだった。ケライをスパイであると裏づける根拠にもなってしまうからだ。早く，透かしのない紙が見つかってほしい。そしてその所在がケライと何の関係もないとわかってほしい。早く，里に害しかもたらさないこの無駄な仕事から解放してほしい。

  公にはシッショとボッチがケライのスパイ疑惑を調査しているとは知られていない。それを知るのはシッショ，ボッチとミミだけだ。だが異常な事態にあることはクビワをのぞく誰もがわかっている。何かが起きているのだと。その不信が広がる前に急いで決着をつけなくてはならなかった。

  シッショはそれからほとんど寝ることもなく，昼夜を賭して調べつづけた。それにも関わらず，資料の山はいっこうに減る気配がない。この部屋に無ければ，他の部屋，そして加工場，武器庫，医務室，治療室，そして書庫が控えている。

  焦った。焦ってどうにかなるものでもない。そんなことはわかっている。そんなあたりまえのことを指摘するような者なら，その手をこちらに引き込み，この不毛な作業を通して己の苦悩を理解してもらいたいほどだった。そしてそんな者にかぎって，こちらが引く手をはねのけ，逃げまわるのだ。自分にとって何の得にもならないからだ。そうだ。誰の得にもならない。こんなこと。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
