#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 101

  その日もキセイはクビワと楽しく遊んでいた。

  数日前，シッショがケライの部屋を捜索するようになってから，クビワは暇な時間ができた。そこで，退屈そうにしていたクビワをつかまえ，キバやツメと一緒に雪山を駆けるようになったのだ。当然ながらゴリとワンワもついてくるため，さながらモンスターの群れのようでもある。

  キセイはクビワらの足には到底着いていけないため，ミミに用意してもらったおんぶヒモでクビワに背負われている。自分では経験したことのない速さにキセイは大喜びで，クビワも満足だった。キバとツメの腕も発達し，立ったクビワほどの大きさもある。とはいえまだまだ子供であり，甘えん坊なところは変わらないが，もう医務室に入ることはないだろう。

  <br>

  太陽がやや西に傾く頃，真っ白な丘陵でクビワは火打ち石の鳴るような音を聞いた。立ち止まり，クビワは耳をすませる。「キセイ，きこえる？」キセイは長い耳をピンと立て，ひょこひょこと動かす。こういうところは獣人の強みだ。まあ，それ以上の聴覚と嗅覚をクビワは持っているが。「あっち」キセイはクビワの柔らかい頬を引っ張り，指差した。

  真っ白い中に，黒くうごめく影があった。素早く不規則な動きは明らかに草食獣のものではない。

  キセイが警戒し，クビワの胸をわしづかみにする。「わあ，くすぐったいぞ」辺境最強の戦士を自称するクビワはこの程度では動じない。だが，腰に下げた籠手を腕にはめ，いつでも戦えるようにした。

  「よくみえないな。もっとちかづいてもいいか？いやならここにおいてく」

  残酷な問いである。近付けば危険も増す。かといって断れば置き去りにされる。答えようがないのでキセイが黙っていると，クビワは相手が了承したと勝手に判断し，その影に歩み寄っていった。やや遅れて他の獣達もついてくる。キセイは縮こまってクビワの背中に身体を隠し，笛を口にくわえた。

  カチカチという音は大きくなる。クビワは音の主がその獣であることがわかり，立ち止まった。「キセイ，みてみろ，トリだぞ。おおきなトリだ」

  キセイは肩越しにおそるおそる前を見た。

  大きくすべらかなクチバシと，油に濡れたようなツヤのある羽根。ピンと張った足。クビワの言う通り，大きなトリであった。その鳥もこちらを確認したのか，カチカチとクチバシを鳴らしながら駆け寄ってくる。威嚇や警戒を見せる様子は全くない。

  クビワが調子に乗って口をかちかち鳴らすのを，キセイは手で塞いだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
