#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 104

  再度の拘束から一日たってケライは解放され，アルジを軟禁する治療室の鍵も解除された。ケライの肉体的・精神的疲労は激しかったが，ミミが文字通りつきっきりで看病することで徐々に回復していった。それにはケライの旺盛な食欲もあるだろう。それに同調するようにアルジの治療も順調に進み，ケライのお見舞いと会話を楽しんだようだった。

  シッショは結局アルジとケライをスパイとは認めなかった。疑惑の人物を解放することでどのような影響が里に及ぶかはわからない。ただ，自分の直感に従った。オヤブンには，書庫で見つけた紙のなかに透かしのないものがあった，今後調査隊への資源を納入する際は厳密にルールを守るように，さもなくば不要に里の隊員が傷つくことになると警告も含めた報告をした。これらの報告はシッショの知る全てが含まれているわけではない。だが嘘をついているわけでもない。全てが完璧でないことはオヤブンもわかっているため，この報告を了承した。

  問題はケライへの補償である。無実の人間を何日間も拘束したのだ。だが，これについてケライは変わった条件を提示した。今後アルジに何らかの罰を加える際は自分を経由すること，というものだった。これまでアルジが起こしたトラブルはほぼ全てケライの関知しないところで生じていた。まあほぼオヤブンとのあいだに生じたものだが。かたやアルジはケライに絶対の忠誠を誓っている。報告書を書けといえば書くし，薬を飲めといえば飲むし，寝ろといえば寝る。ゆえに，今後無用の混乱を里に生じさせないためには，アルジをケライの統制下におくべきだと進言したのだ。この条件は，ショムの説得もあり，容易に受け入れられた。二人とも，以前ケライを陥れようとした借りがあり，しかも当時ケライがそのことを責めなかったため，今回はあまり強気に出られなかったというのもある。

  <br>

  アルジの長所のひとつは驚異的な回復力である。外傷については雪灯籠のシートのおかげもあるが，義足と杖で歩けるほどになった。そんな日，リハビリを行うアルジのもとにケライがやってきて，

  「私はアルジさんを本気で殴ります」

  と言ってきた。

  「痛いのは嫌だな」というアルジに対し，「多分，痛いです。本気ですから」と言った。

  ケライの後ろにはミミもおり，ふっとばされるアルジを受け止める役として来たという。状況のわからないショムのためにケライが説明する。

  理由は簡単である。ケライが拘束される原因となった紙は，アルジが書庫からくすねたものだったからだ。

  いくら何も書かれていないとはいえ，本棚におかれているものを筆記用に使用するなどケライにはありえないことだった。そして，その紙を持ってきたのはまぎれもないアルジであった。

  「事実ですか？」というミミの問いにアルジはうなずく。なぜそんなことをしたのかという問いに対しては紙の場所がわからなかったから，という子供じみた回答をした。当初は心配していたショムもあまりの拙い発想に天を仰いだ。もはや誰もアルジに同情などしない。

  「私が殴ったら明日までに手引きを暗記してください。いいですね」という問いに，アルジは文字が読めないとは言えず，「はい」とだけ答えた。

  <br>

  念のためアルジにはショムの手でマウスピースがかまされる。「ではいきます」

  ケライの合図にアルジは目をきつく閉じて歯をくいしばるが，なかなか拳が飛んでこなかった。何かのサプライズかと淡い期待もした。

  たまらず周囲を確認するためわずかに目を開けると，

  その顔を目がけ綺麗にハイキックが炸裂し，アルジは一瞬で失神した。

  刹那，アルジが思ったのは，カカトでなくてよかった，というものだった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
