#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 106

  ケライのスパイ疑惑は，表向きは書庫の器物破損による罰ということになり，その責任の一端を担ったアルジをケライが直々に成敗したことで解決した。真実ではないが全くのデタラメというわけではない。それが許されることかどうかは別だ。シッショが全てを明らかにして組織が疑心暗鬼で崩壊してもよい，というなら真実を明かすのもよいだろう。なぜなら他人にとっては里の存亡などどうでもいいことだからだ。そして，一難去ってまた一難というか，平穏を知らない里に新たな問題が生じた。

  狡舞鳥が里の近辺で確認されたのである。確認されたというより，狡舞鳥が広場に姿を現したのだ。不思議なことにその顔は金属製の兜で覆われており，背中にはなんとキセイを乗せていた。兜から伸びた手綱をつかみ，その姿はあたかも伝説でうたわれた疾鳥騎士のようである。いや，本人はそのつもりなのだろう。強くて優しい騎士はみんなの憧れなのだ。

  その奇妙な様子に里の全員が広場に集まる。前に出ようとするシンキらをボッチが手で制す。半分以上の者は見るのも初めてだろう。その鋭く太い爪で砂をかきあげるたび，アルジの背筋が冷たくなる。

  「キセイ，どういうことか説明してくれない？」ようやくシンキが口を開いた。だがそれでは質問が複雑すぎる。

  「ええと，私から説明していいですか」ミミが手を挙げてそう言った。「みなさんは先に広間に入ってください。キセイさんはその子，ええと…」「コッコ」「コッコさんを獣舎につないでから広間に来てください。いいですか？」キセイがミミの言葉にうなずき，カッカッとノドを鳴らして狡舞鳥を促した。

  本当にキセイはモンスターと話せるのだろうか。アルジは無口なキセイが持つ能力の秘密が知りたくてしょうがなかった。

  <br>

  ミミはある晩，キセイからペットの兜を作るよう要求された。明日までに作ってほしい，という無茶な要求だった。だがキバとツメさえも容易に飼い馴らしたキセイである。きっと何か重要なことなのだろうとミミは確信し，作成を請け負うことにした。

  キセイは本気だった。加工場に行き，眠い目をこすりながらミミの質問に真剣に答えた。さらに地面にそのペットの頭の大きさ，全身の姿などを描きながら詳細に説明した。やがて頭の中で完成させたミミはキセイを寝るよう促し，夜を徹して兜の試作品を作った。

  翌朝加工場を走ってやってきたキセイは，できあがった兜のすばらしさに飛び上がって喜んだ。そして目を輝かせながら兜にペイントを施した。その模様を獣人で知らない者はいない。奴隷として生まれながらその才覚を活かし，ついには騎士の座にまでのぼりつめた英雄のなかの英雄，伝説の疾鳥騎士を示す紋章である。

  兜をクビワに背負わせ，獣の一団は狡舞鳥に会いに雪山に行った。歩くキセイにはついていくだけで大仕事だったが，その日も狡舞鳥はそこにいた。大きなリュックの中身をぶちまけ，狡舞鳥にエサを食べさせている最中，難なくクビワが兜をかぶせて紐で固定した。

  それからキセイは狡舞鳥の手綱をひき，皆を秘密基地へと招待した。秘密基地といっても大層なものではない。里にほど近い，吹き抜けのある洞窟である。内部は二層に分かれていて，はしごで上へ昇れるようになっていた。ペットのなかには里のような賑やかな場所を嫌うものも多い。ゆえに，緊張した状態になったときは，暴れ出さないようここで面倒を見るのだ。

  クビワは二階に置かれたベッドにたまらず飛びこんだ。ビュンから抜けた羽毛を集め，掃除して作ったふかふかのベッドだ。人付き合いが苦手なキセイは，それでも快適に過ごすための心得を身につけている。

  キセイはそこで狡舞鳥が自分に慣れるまで共に過ごした。特殊な生態を持っていても，鳥の一種である。そうキセイは見抜いていた。真っ先に兜を作ったのもそのためだ。この兜はかっこいいための道具でなく，目隠しのためである。いわば狡舞鳥の拘束具だ。また，クチバシの部分は丸く加工され，柔らかいクッションで覆われている。このため，仮に誰かをつつくことになっても大怪我にはならないというわけだ。

  それでも何が起きるかは予想できない。ゆえに，背に乗ってそれなりに自由に操れるようになるまで，皆から隠していたわけだ。まあ，不思議なほどあっという間に乗りこなせるようになったので，狡舞鳥はキセイを便利なパートナーとして認めたのかもしれない。それなりに言うことさえ聞いていれば，何もせずともエサにありつけるからだ。こんな楽な暮らしはないだろう。

  その間，ミミは獣舎で狡舞鳥のための檻を作って準備していた。シッショ達が格闘している間も，里は動きつづけていたのだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
