#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 107

  この章でストーリーは進行しない。翌日に進めたい読者は飛ばしてほしい。

  アルジはようやく治療室から解放されたとともに，自分の居場所がなくなっていることを知った。ドアに鍵がかかっていたのだ。そして知らされた。ケライの部屋が資料で埋まっていることがわかり，その一部をうつすため，隣にあるアルジの部屋を明け渡すことになったのだと。もとからアルジは一文無しでこの地に訪れた。ゆえに部屋にほとんど物は置かれていない。撤去するのは容易だった。既にかつてアルジの部屋だった場所には何箱もの資料が置かれ，鍵がなければ入ることもできなくなっていた。

  これを提案したのはボッチである。空き部屋もあるにはあるが，雑多な物が放置されているし，掃除も必要だ。しかも遠くまで移動させるのは面倒だし，ケライにとっても不便だろう。ということで，アルジの部屋が没収されたのである。

  確かにアルジはラウンジで寝ることも多かったし，部屋が殺風景だから必要ないと判断されたのも仕方ないのだろうが，これはかなり堪えた。こらえてはいたが，本当に泣きそうになった。アルジはかなり自分の居場所を気にするほうである。自分の居場所があるからこれまで安心して無茶できたのだが，それを奪われてしまったことで深く傷ついた。つらかった。

  マッパを筆頭に，この里では割り当てられた部屋をほとんど使わない者もざらなので，ボッチとしてはアルジも同じような人物だと思ったのかもしれないが，全く逆だった。むしろアルジこそ自分の部屋が不可欠だったのだ。

  ただこうした仕打ちを受けたときにちゃんと自分の意見を言えないのはアルジの悪い癖である。許可もなく部屋を奪ったんだから新たな部屋を綺麗な状態で提供するのは当然である，とか言って怒るだけでよいのだが，居場所が奪われた，というショックがあまりにも大きく，自分を失ってしまったのだろう。これだけ頑張っても自分は何の相談もなく部屋を追い出されるような軽い存在でしかないのかと思い虚しくなったのかもしれない。自分で場所を確保しなければすぐに死ぬような状況，たとえば遭難，ならばいかようにでも立ち回れるのに，不思議なものである。

  ボッチにそれを告げられ「わかりました」と一言答えたアルジは，ふらふらと書庫へ向かい，誰もいないテーブルに突っ伏した。書庫は申請しなければ夜に閉鎖する。だがこれから毎日申請する気はおきない。

  自分の部屋のドアノブを回し，引いた瞬間に鍵がかかっている，ガチャンというその音と感触が忘れられず，それを思い出すたびに，自分が世界から拒絶されていると感じた。ようやく落ち着きつつあった，自分を壊そうとする衝動が再び黒い沼から腕を出し，全身を引きずりこむようだった。

  「お前抜きな」「どうして？」「友達じゃないから」

  それとは違う。だが頭から離れない。

  上着を頭からかぶった。自分の呼吸がひきつるのを抑えられなかった。いじけていれば誰かが助けてくれるなんて全く思っていない。

  ただ，悲しいだけだ。

  <br>

  「アルジさん」自分の両肩にあたたかい手が乗るのを上着越しに感じた。ケライは冷え性だからこんなにあたたかくない。「何ですか」突っ伏したまま，目をこすりながら答える。「ボッチさんを叱ってきました。説明不足でアルジさんを悲しませたって」「悲しんでません」「ふふっ」

  ようやくアルジは顔をあげ，上着で顔を拭いて着直した。泣いてない。ケライの教えは守る。

  声の主はミミであった。隣の席につき，アルジに言う。「ケライさんの部屋が満杯なので，アルジさんの部屋を使ったらどうかってボッチさんが提案したとき，じゃあアルジさんは私の部屋で受け入れます，ということになったんです」

  「ミミさんの部屋？」「はい。私の部屋は特別大きいので，寝床も二つありますし，アルジさんの怪我が痛んでもすぐに対応できます。それに，義足の手入れ，とかも。どうですか」

  そんな。迷惑です。そう言おうとした。だがアルジは相手の好意を素直に受け入れてしまうほど頭が悪かった。というか，とっさのときにいつもアルジが助けを求めるのはミミなのだ。

  「迷惑じゃありませんか。私は部屋に一日中いることもありますし，夜に起き出すこともよくあるんです」「気にしないでください。さみしくなったらいつでもお話聞いてあげますよ？」その言葉を聞きアルジは赤くなった。

  そうしてアルジはミミの提案を聞き，ミミの部屋で過ごすことになった。

  <br>

  「靴を脱いであがってくださいね」「おじゃまします」

  案内されたミミの部屋は本当に大きかった。シンキの部屋に案内されたときにも大きいと感じたが，こちらはそれよりもはるかに大きい。しかもいくつもの小部屋がある。

  ベッドも布団も絨毯もふかふかで，暖房も完備だ。なにより，

  「すごくいい匂いがします」「落ち着くようにお香を焚いてるんですよ。どうですか」「はい。なんか，楽園に来たような，いい気分です」「楽園なんて，大げさですよ」

  そういってミミは引き出しから何かを取り出し，装飾の華やかな食器を持ち出した。間違いない。お茶だ。「飲みますか？」アルジは何度もうなずく。その様子にミミは笑みを浮かべ，湯をわかしはじめた。

  むしろアルジがこれまでいた場所が部屋という名の物置だったのではないかと思えてくる。シンキの部屋で驚いたふかふかの絨毯にボッチが食いつかなかったのも，隊員の部屋には常備されているためかもしれない。いや，そもそもアルジとケライは後からやってきたのだから仕方ないのかもしれないが。しかし茶とは。そんな贅沢が許されるのだろうか。

  それは余熱をもった上品なカップにかぐわしい香りとともに注がれ，「どうぞ」という言葉とともに差し出される。「いただきます」と持つ手が震え，ミミに「アルジさんってほんと面白いですね」と笑われてしまった。

  口いっぱいに広がり，鼻へ通ってゆく豊かな香り。とてもなつかしい感じだった。

  「おいしい」「それはよかった」喜んでもらえてミミも満足のようだ。

  「すごく，おいしい，クー先生」

  「クーせんせい？」不思議な言葉にミミが聞き返し，アルジがハッとする。「いえ，何でもないです」

  <br>

  その日は徹夜になることもなく，アルジはミミに合わせ眠ることにした。アルジは奥のベッドということだったが，なんと髪をおろしたミミまで入ってきた。ベッドは大きいから二人が寝るくらい何でもないのだが，そういう問題ではない。慌てるアルジに「手前の寝床はケライさんのなんですよ」と笑顔で言う。ミミと一緒に寝るのははるか昔，森へ続くキャンプ以来だった。ただ，ざこ寝に近かったあのときとは違う。

  反発力を完全に失ったマットレスと羊皮紙をも彷彿とさせる硬い毛布。それがこれまでアルジが使用していたベッドだった。だがここは違う。まず枕がある。それだけではない。自分の身体も沈みこむような柔らかさ，それでいてしっかりと身体を支えるマットレスに，清潔感あふれるシーツ。着ているのかわからないほど軽く，保温性に優れる羽毛布団。そしてほのかに甘い香りでぬくもりを醸し出すミミ。

  「あ，あの」アルジは思わず声が上ずってしまった。「ん？」ミミが答える。「緊張してしまって…」「布団が合いませんか？」「いえ，そういうわけじゃなくて。…こんないい思いしていいのかって」

  なぜアルジはこれだけの幸福を素直に喜べないのだろうか。何が絶え間ない罪悪感を負わせるのだろうか。

  ふっとミミの表情が曇り，アルジを抱き寄せた。「…!」薄い布越しに，ミミの柔らかさと体温が伝わってくる。

  ああ，あったかい。

  アルジの真っ赤な耳元に，ミミは唇を近づけ，ささやいた。

  「いいんですよ。だって私たち，そのために生まれてきたんですから」

  そう言ってアルジの髪をやさしくなでるうち，その鼓動も落ち着いていくのがミミに伝わった。

  「つらいことも，一人で背負わなくていいんです。だって，そのために私たちがいるんですから」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
