#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 108

  この章でもストーリーに進展はない。翌日に時間を進めたい読者は飛ばしてほしい。

  「靴を脱いであがってくださいね」「おじゃまします」

  案内されたミミの部屋は本当に大きかった。シンキの部屋に案内されたときにも大きいと感じたが，こちらはそれよりもはるかに大きい。しかもいくつもの小部屋がある。

  ベッドも布団も絨毯もふかふかで，暖房も完備だ。なにより，

  「すごくいい匂いがします」「落ち着くようにお香を焚いてるんですよ。どうですか」「はい。なんか，楽園に来たような，いい気分です」「楽園なんて，大げさですよ」

  そういってミミは引き出しから何かを取り出し，装飾の華やかな食器を持ち出した。間違いない。お茶だ。「飲みますか？」アルジは何度もうなずく。その様子にミミは笑みを浮かべ，湯をわかしはじめた。

  むしろアルジがこれまでいた場所が部屋という名の物置だったのではないかと思えてくる。シンキの部屋で驚いたふかふかの絨毯にボッチが食いつかなかったのも，隊員の部屋には常備されているためかもしれない。いや，そもそもアルジとケライは後からやってきたのだから仕方ないのかもしれないが。しかし茶とは。そんな贅沢が許されるのだろうか。

  それは余熱をもった上品なカップにかぐわしい香りとともに注がれ，「どうぞ」という言葉とともに差し出される。「いただきます」と持つ手が震え，ミミに「アルジさんってほんと面白いですね」と笑われてしまった。

  口いっぱいに広がり，鼻へ通ってゆく豊かな香り。とてもなつかしい感じだった。

  「おいしい」「それはよかった」喜んでもらえてミミも満足のようだ。

  「おいしいです，クー先生」

  「クーせんせい？」聞きなれない言葉にミミが疑問に思う。アルジはハッとしてごまかした。「いえ，何でもないです」

  <br>

  その日は徹夜になることもなく，アルジはミミに合わせ眠ることにした。アルジは奥のベッドということだったが，なんと髪をおろしたミミまで入ってきた。ベッドは大きいから二人が寝るくらい何でもないのだが，そういう問題ではない。慌てるアルジに「手前の寝床はケライさんのなんですよ」と笑顔で言う。ケライもここで寝ることがあるのか。それほど部屋が満杯なのか。

  ミミと一緒に寝るのははるか昔，あのキャンプ以来だった。ただ，ざこ寝に近かったあのときとは違う。

  反発力を完全に失ったマットレスと羊皮紙をも彷彿とさせる硬い毛布。それがこれまでアルジが使用していたベッドだった。だがここは違う。まず枕がある。それだけではない。どこまでも沈みこむような柔らかさ，それでいてしっかりと身体を支えるマットレスに，清潔感あふれるシーツ。着ているのかわからないほど軽く，保温性に優れる羽毛布団。そしてほのかに甘い香りでぬくもりを醸し出すミミ。

  「あ，あの」アルジは思わず声が上ずってしまった。「ん？」ミミが答える。「緊張してしまって…」「布団が合いませんか？あとは枕とか」「いえ，そういうわけじゃなくて。…こんないい思いしていいのかって」

  これだけ幸福に満たされるたび，同じくらい，トゲトゲしいものが心にわきあがってくる。自分でもわかっていながら，素直に喜べないのだ。

  ふっとミミの表情が曇り，アルジを抱き寄せた。「…!」

  薄い布越しに，ミミの柔らかさと体温が伝わってくる。

  あたたかい。

  「いいんですよ。だって私たち，そのために生まれてきたんですから」

  そう言ってアルジの髪をやさしくなでるうち，徐々に鼓動も落ち着いていく。それはミミにも伝わった。

  「つらいことも，一人で背負わなくていいんです。私たちがついてるんですから」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
