#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 113

  湿地で大型の獣を仕留めたクビワとシッショは，その獲物を湿原へ続くキャンプへと持ち帰っていた。それはシッショが初めて湿地を訪れたときに見たモンスターだ。はじめにシッショが伝えた情報をもとに，それは泥盤獣タルポラと名づけられていた。生物の減った湿地の奥で，その姿を再びとらえることができたのだ。

  ただ，クビワを連れてきたのは間違いだった。気が立ったそれを敵とみなしたクビワが屠ってしまったのだ。ゆえに，他の個体が見つからないかぎり，その生態を知ることはほとんどできない。シッショ自身が見たものを，他の隊員がどれだけうまく聞き出せるかが重要だろう。

  泥盤獣はその名のとおり，泥の中で生活し，時々顔を出して呼吸するようだ。クビワが近づくと背中を向け，その泥が幾層も積み重なった壁のようなそれを見せつけた。なおも接近するクビワに，泥盤獣は後ろ向きのまま猛スピードで迫ってきた。背中で押し潰す気だったようだ。だが相手が悪かった。素早く横に回りこんだクビワに柔らかい腹を貫かれ，あっという間に倒されたのだ。

  仕方なく，シッショはその亡骸を持ち帰るようクビワに頼んだ。クビワはそれを軽々と頭上にかかげ，水が垂れてくるのを不快に思いながらもキャンプまで運んだ。

  <br>

  獣車に積み込めるよう解体するシッショの横で，クビワが焼けた肉をほおばりながら聞いてきた。

  「なあ，シッショ」「なに？」「さっき兄チャのニオイしなかったか？」

  「へ？」驚いてシッショの動きが止まる。「クビワの兄チャ？」「うん」「でも兄チャって死んだはずじゃ」「うん」クビワが悲しそうな顔をする。シッショは急いでクビワに抱きつき，背中をなでた。「ああもう，ごめんねクビワ。思い出させてごめん。でもさっき兄チャのにおいがしたんだね」シッショになでられ，落ち着いたクビワは顔を振ってからいつもの笑顔を見せた。

  「うん，兄チャのニオイした」「どこで？」「のはら」

  のはら。クビワは湿地のことは「みずべ」という。誰かに場所の名前を教わったとき，間違えて覚えたのだろう。だからのはらは別の場所だ。それはおそらく，湿地の先に広がるデコボコの荒れ地を指していた。

  シッショ達は泥盤獣を発見する直前，湿地を抜けてそこへ到達した。湿地を抜けたのだ。だがそこを通って北へ行くのは大変そうだった。戦って勝てるようなものではないからだ。かつて草原だったのかもしれないが，今はあちこちが隆起し，黄土色の土が顔をのぞかせている。原因は荒れ地全体で起きる地震活動だろう。もしかすると湿地の生物が減っているのは，その地震を恐れ避難したためかもしれない。まあ，ヘタに地面が抜けて落下したら助けられないので，一旦そこを進むのはあきらめ，抜けられる道がないかうろうろしたわけだ。

  ところがクビワの兄がいるとなれば様子は変わる。というか大発見である。この北の大陸で，調査隊以外の人間がいることになるのだ。急いで帰って報告しなくては。シッショは手早く荷物を積み込み，満腹で眠るクビワをどうにか獣車に乗せると，里へ向かってダモスの足を進めた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
