#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 113

  風の流れを頬に感じ，アルジは目を覚ました。

  寒い。なんだこの寒さは。そしてこの身体にねばつくものは。ふっと身体を起こし，すべりそうになるのをこらえる。

  太陽は大きく傾いている。夜が迫っている。だが自分の知っている太陽ではない。空の明るさに比して，その位置が高くありすぎるような。

  あれ？

  空？

  これほど空とは自分に近いものだっただろうか。まるで自分が岸辺にあって，その先に水面ではなく薄青の空が続いているような。

  アルジの支離滅裂な思考が次第に収束してゆく。

  そして状況を把握するにつれ，寒さとは異なる身体の震えがやってきた。これほど自分の手足がないことを感謝したときはない。もし手足がその先まで健在であったなら，自分の意思とは関係なしに，震えのあまり身体が暴れ出し，その身体すべてを失うことになっていただろう。

  アルジは空の上にあった。針山を覆う雲海の上。ねばつく物体でかろうじて何かにへばりついているが，それは表面がツルツルとして，すべりやすい。何だ。何があった。私は雨に捕まり，空へ吸い込まれた。そこから先の記憶はない。死んだ，と思った。だが生きている。この感覚。ここはあの世でないことはわかる。そもそも自分のような罪人が死んで天になど行けるものか。私の行く先は地の底でしかない。

  目を閉じて，これまで収集した情報を整理する。そして思い至り，目を開く。

  自分が乗っている黒い円盤は何だ？周囲を見回す。ふと，風の吹く方向に突起が出ているのがわかった。いや，突起ではない。

  亀だ。その顔はまぎれもない亀の顔だった。空を飛ぶ亀。おとぎ話のようである。毛で覆われた尻尾はなく，大きな前足と平たい身体で風を受けながら，優雅に空を舞っている。それだけならいいが，自分はその上にいるのだ。

  助けてくれたのか？そんな何のためにもならないことをするものか。

  アルジのひねくれた予想は正しかった。この亀は時折首を動かしながら何かシャリシャリと音をたてる。それが風のなかにまざってアルジの耳に届いた。そうか。こいつは雲を食うのだ。だが何のために。いや，あの音はなんだ。

  そしてあるとき，アルジは急に視界が晴れるように感じた。それとともに，アルジの現実に沿うように雲が姿を変えてゆく。それは幾重もの羽衣のように形を変え，正体を現した。マッパに感謝した。こんな感動を再び味わえるときが来ようとは。

  <br>

  自分が雲と錯覚していたものは，針山を覆うほどの巨大なクラゲであった。

  天を覆うほどの布，天巾 (てんきん) アールケナン。無防備に空に閉じこめられておきながら，アルジは自身のネーミングセンスが冴えわたるのを満足に思った。

  おそらくクラゲといっても複数の個体が群をなしたものだろう。そのうち，触手にあたるものに自分は捉えられてしまったのだ。本来ならそのまま全身を吸収され，義肢のみが地面に落ちていたところだったが，偶然にもこの亀の捕食行動に救われた。おおかたそんなところではないか。

  それにしてもこの高度で形が崩れないとは，この天巾という生物はどういう仕組みをしているのか。特殊な保水構造に違いない。里に持ち帰りたい。

  いや，そんな悠長なことは言っていられない。この亀がこのまま何昼夜と空を飛び続ければ，自分は確実に死んでしまうからだ。どこかに着地してほしい。それだけを祈り，アルジは体力や体温を奪われないよう身体を丸めて必死に心を落ち着けようとした。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
