#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 113

  「ボッチ，起きて」

  その声にボッチが目を覚ますと，目の前にシンキの顔があった。驚いて飛びのくが，いつものようなからかう様子ではないし，体内時計はまだ朝を告げてはいない。

  「ちょっと来て」そう言ってシンキはテントの外に頭を引っこめた。テントの中にいるのはボッチだけだ。良い知らせでないことは明らかだ。

  <br>

  崖際にミミと，その服にしがみつくキセイの姿があった。ボッチがやってくるのに気づき，顔を向ける。二人とも心配そうだ。

  「何があった」その言葉にミミは「ちょっとあれを」と言って下を指差す。

  「なんだこりゃ」

  それは夜の暗い河，その中州に自分たちが取り残されてしまったようであった。この地に真の夜闇がないのは幸いであるが，崖下が見えないほどの暗闇に覆われている。霧か何かは判然としないが，それがわずかな風にたゆたう他は，何も見通せない。あの緑の低地，美味なる肉も。

  「これ，何だろね」そう言って崖下に手をのばそうとするシンキに「触るな!」と思わずボッチが大声を出してしまった。びくっとシンキの身体が震える。ボッチはすぐ「すまん，大きな声出して」と謝ったが，何かの歯車がずれたのか，シンキは「ごめんね」とだけ言ってテントに戻ってしまった。「ちょっと見てきますね」と言ってミミは腰にへばりつくキセイを伴ってテントの中に入っていく。ボッチは煮え切らない気持ちで崖際に座りこんだ。

  シンキの癒えない心の傷。それもあるだろう。身体が自由に動かせない焦り。それもあるだろう。それで皆に迷惑をかけている。それもあるだろう。でも皆のことを考えるとじっとしていられない。いや，ボッチはシンキを足手まといだと思ったことはない。ボッチはシンキがそばにいるだけで，どんな困難でも突破できるような自信がわいてくる。ただ，シンキは自分に対しときどき何か怯えるような，不思議な目をする。ボッチはシンキを傷つけることなんて絶対しない。だから怯える必要なんてない。いまの大声だって傷つけるつもりで言ったんじゃない。それはシンキだってわかっているはずだ。だが，何か，…。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
