#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 115

  アルジを失ったマッパは敵襲と捉え，ケライに目を配りながら針山の麓にあるキャンプまで退却した。アルジの身に何が起きたかは先の通りだが，この二人はそのことなど知る由もない。

  安全が確かめられたケライは，針山に捜索に戻ろうとする。地面に血痕はなかった。どこかではぐれたかもしれない。ただもし，音もなく丸呑みにするような何か，雪灯籠のようなモンスターがいるとすれば，被害はさらに大きくなるだけだ。マッパはケライをキャンプから出すことはできなかった。

  「落ち着け。はぐれただけかもしれん」根拠はない。「知ってます」こちらも根拠はない。

  「だから早く助けに行かなくては」そういってなおも出ようとするケライの腕を引っ張る。強い力にクビワが痛がる。だがそんなことでマッパは怯んだりなどしない。腕が抜ければ挿すだけだ。「どこにいるかもわからんのに無茶だ」「山のどこかにいるはずです」「迷ってのたれ死ぬだけだ」「では命綱をつけてください」「そういう問題じゃなくてだな。クビワのような化け物じみた嗅覚や聴覚もなしに，あてもなく探したって意味がないって言ってるんだ!」「クビワさんは化け物ではありません」バカかこいつ？

  「アルジとお前が入れ違いになったらどうする」「アルジさんは私を探そうとします」「そうだろうな。どちらかがここで待たない限り永久に二人は会えないことになる」「ではアルジさんがここに来たら待つように言ってください」「お前が待つんだ」「なぜですか」「アルジが戻ってくるまでに，針山の報告を書く義務がある」

  その言葉にようやくケライは落ち着いた。かと思ったら，キャンプ内の荷物から紙とペンを取り出すと猛烈な勢いで書き始めた。書き終わりました。探してきます。そうするつもりなのだ。

  なんでこんな変なやつらを連れてきてしまったのか。だが連れていくと言ったのは自分の責任だ。そして大事な隊員を失うことになった。いや，まだ可能性は残っているが。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
