#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 117

  アルジの重みか己自身の体温が低下したためか定かではないが，アルジを乗せた空飛ぶ亀，黒鼈甲 (くろべっこう) ルンマと名づけたもの，は高度を次第に落とし，やがて険しい山々に入りこむと，わずかに突き出した平坦な場所に激突した。その表現は正しい。着地する寸前に手足を縮め，地面に叩きつけられたのだ。だが甲羅は弾力があるようで，少し跳ねたもののすぐに静止した。

  かたや準備をしていなかったアルジはしこたま身体をぶつけ，冷えきった身体にこごえながらもあたりを見回した。

  全身にへばりついた天巾の残骸をはがしながら，どこまで来たのか，里はどこか，情報をさぐる。すると背後から地鳴りとともに何かが近づく音がした。

  アルジの後ろからすさまじい勢いで蒸気が噴き出した。直前にフックをのばし，下にぶらさがってやりすごす。こんなときに義手は便利だ。寒さで手がかじかんでいたらこんな芸当はできない。

  一方，その熱風をまともにくらった黒鼈甲が上空に投げ出された。だがそんな事態になるのは予想済みだったようだ。素早く身体を広げ，新たな風を受けながら再びすいすいと上空へ昇っていった。

  熱と風を急速に得るためわざわざここに降りたったのだろうか。計算された行動に驚くばかりだ。それにくらべ，とっさの判断でぶらさがったはいいが，腕の関節を持たないアルジは上に登るのも一苦労だった。

  蒸気の存在で，初めてアルジはこの山が中腹にいくつもの穴を持っていることがわかった。自分が立つこの場所は，あたかも屋上に向かって尖った高層建築のバルコニーのようでもあり，周囲に同じような山が立ち並んでいる。長い時間をかけて浸食されにくい物質だけが残り，このような奇妙な山々を作っているのかもしれない。ただこの穴はいったい何だろう。中からは何かが腐ったような強烈な悪臭がただよってくる。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
