#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 119

  アルジの前に姿を現したのは，灰色がかった身体をもつタコだった。二本の腕が他よりも長く，それはイカのようでもある。だが胴体は長くない。

  この世界には，空を覆うほどの浮遊するクラゲや，悪臭の山を根城とするカニや，群れで狩りをするタコがいる。そしてこのタコは，木の上で姿を隠し，持っている毒針で相手を仕留める。まあ，身体に命中していないので毒があるかどうかは定かではないが。

  『アルジ，そのバケモノは木の間を飛び移れるのか？』

  シッショとともに裂掌獣に挑んだあの日，シッショが言った言葉が浮かんだ。こいつだったのだろう。長い二本の腕で枝を自在に飛び移り，子供の裂掌獣であれば倒すこともできるはずだ。かたや大人の裂掌獣ともなれば，その硬い甲殻で針をものともせずこいつをエサにするに違いない。

  虚凧 (うつろだこ) ディディンナ。アルジはそう名づけた。蛸でなく凧としたのは森を自在に飛ぶ様子を想像したためだ。姿を隠す捉えどころのなさも名前から感じられ，通称としてはなかなか良いのではないか。いや，そんなことはどうでもいい。今は迫るこの個体と，背後に隠れているであろう別個体にどう対処するか，その方がはるかに重要なのだ。

  アルジが通称を考えるクセがあるのは，それが楽しい，というのもあるが，特徴をとらえて整理し，同時に，これだけの事態にありながらそんなことを考える自分を嘲ることで，冷静さを取り戻すねらいがある。頭に血がのぼっていたり，追いつめられているときほど，そんなアルジを「滑稽だな」とバカにするもう一人の自分を感じる。そうするとたかぶった熱は急速に冷めてゆく。ふだんは卑屈なアルジの考えが戦いのなかで研ぎ澄まされてゆくのは，そうした悪癖に由来するところがある，のかもしれない。

  <br>

  それは何本もの足を這わせ，アルジに近づいてくる。

  <br>

  ドッ。

  <br>

  アルジの射出した鉄球が虚凧の身体を四散させた。紫に染まる河原をよそにアルジは身を翻し，スイッチで鎖を巻き取りながら河原を駆けてゆく。

  何が起きたのだ。

  それは瞬きほどの駆け引きだったかもしれない。義手から鉄球を打ち出すためには，逆の腕でスイッチを起動させる必要がある。そのために伸ばした腕を，虚凧は攻撃だと誤解し，即座に反対の腕側へ退いた。だが，それこそがアルジの仕掛けた罠であった。まんまと鉄球の射程に入ってしまったのだ。あとは基本通りの動きで義手の鉄球を射出するだけだった。

  アルジには相手が自身の側面に回り込むことはないという確信があった。上着をかぶって沈黙する相手が何をしてくるのか，虚凧にはわからないからだ。この世界，飛び道具を持つ敵は少ない。ゆえに，攻撃から距離を取るように後退すれば，ほとんどの攻撃を回避できる。それをアルジは読んだ。虚凧は狡猾さと慎重さをあわせ持つ。だが，慎重であるがゆえに，アルジに考える時間を与えすぎてしまったのだ。

  とはいえ，はたから見れば虚凧が自分から当たりに行ったようにしか見えない。他に仲間がいたところで，何が起きたかすぐにはわからないだろう。

  <br>

  本来は遮蔽物の多い森に逃げ込むべきなのだろうが，それは敵の懐に飛び込むようなものだ。とはいえ河原をどこまで逃げても敵からは丸見えである。むこうには一撃でこちらの命を奪う武器がある。先にアルジが上着をかぶったのは守りを固めるように見せかけたハッタリであり，仮に当たれば容易に貫かれる。アルジの手足がまともなものではない，すなわち，裂掌獣の腕のような硬質のものであると相手に知られれば，向こうは確実に急所を狙ってくるだろう。

  願いとかそういうものは好きではないのだが。そう思いながらアルジは不意に立ち止まり，胸を叩いて何かを吐いた。

  喉の焼けるような不快感とともに，何かが口から垂れ下がる。胃袋に収めていた信号弾である。歯に結びつけていた糸をちぎり，目盛を合わせてから打ち上げた。

  道具を身体に収める方法は，ここに来る前マッパに教わったものだ。マッパは緊急時の薬品や非常食とともに下腹部に収めているが，アルジにはとても真似できないため，腹の中に入れていた。まさかこんなところで役に立つとは。

  ただしこの信号弾は当然里には届かない。他の隊員が気づいてくれるのを願うしかない。

  シャッ。

  それは仲間からの信号弾の音ではない。首元を空気がかすめたもの。それが生じさせた音である。

  虚凧はアルジの異状を見逃さず放った。命中する必要などない。皮膚を少しでも抉ればいい。毒が体内を侵し，アルジの命は容易に奪われる。その事実は，森に，自分たちの領域に，アルジを立ち入らせるのに十分であった。

  河原を逃げて立ち止まったところを狙い撃ちするか。森でじわじわと追いつめて仕留めるか。虚凧の狩りは始まったばかりである。

  当のアルジは，森の木や草をかきわけながら，仮に手足のない自分が死んだところで肉なんかほとんどないんだ，ざまあみろ，と思っていた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
