#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 120

  針山の頂上から見えるのは，広大な湖である。その先には煙を吹く山がそびえているが，船を持たないマッパとケライが辿り着くのは不可能だ。

  寝ずに報告を書き終えたケライは，やや強引にマッパを引き連れて再び針山へ入った。昨日アルジとはぐれた場所に到着し，周囲を捜索する。ケライまでも失わないよう，マッパはほぐした釣り糸をケライに結びつけ，なるべく離れすぎないように気を遣うが，ケライ自身はそんなことおかまいなしに，あちこちを歩き回ってゆく。人間の痕跡，もしくはモンスターの痕跡，それがないか必死に探す。

  ケライが跳毬獣と名づけたもの，もしくはアルジが毛鞠獣と名づけたもののフンとおぼしき物体が溜まった場所がある。跳毬獣は群れで生活し，共同のトイレを持つようだ。だがこのモンスターが暮らす証拠はあちこちにあるものの，肝心のアルジの痕跡は全くない。まあ，事実を知っている者からすれば，空にさらわれたのだから足跡すらなくて当然なのだが。

  「ケライ，来い」ふいにマッパが呼んだ。その言葉にケライが駆け寄ると，強い力で抱き寄せられる。反射的に引きはがそうとするが，力の差は歴然だ。何をしようというのか，と，マッパが顔を近づけて「静かにしろ」と小声で言った。

  「血のにおいがする」その言葉にケライの身体が強張る。マッパはケライに回した腕の力を緩めず，ゆっくりと嗅覚の導きに従う。視界を邪魔するいばらのような木々をよけながら進むと，何か黒い塊があった。

  マッパはケライから腕を離し，塊のそばにしゃがみこむ。これがニオイの元だ。

  それは割れた亀の甲羅である。甲羅の中から肉がのぞき，小さな虫の群れがごちそうを懸命に運んで，解体を進めていた。平らな甲羅に，その後ろ足はヒレのようであり，ウミガメを想像させる。だが両前足が途中から切断されたかのようになっているため，その先がどのような形だったのかわからない。

  死体のようすから自分たちが昨日針山を訪れる前にやられたようだ。マッパは嫌な想像をする。亀の甲羅を割るような力を持つ強力なモンスターがこの森に潜んでいるということか？もしかするとそれが昨日，アルジを。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
