#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 121

  針山でいくつもの甲高い音が飛び交う。跳毬獣が互いに警告を発しているのだ。だがマッパとケライを襲った敵がはるか上空から接近したのなら，もっと早くから鳴き声が聞こえていたはずだ。つまり，この敵は針山に根城を持ち，低空から一気に襲いかかってくると考えられる。

  イバラの木は空を覆い，敵の姿を隠す。かたや相手はこの場所を知りつくしている。マッパとケライは極めて不利な状況であった。縄張りから外へ出なくては。もしくは。

  「ケライ。釣り竿を使って俺をあいつに当てろ」「あいつとは誰ですか」「さっき攻撃してきたやつだ」「見えません」「ある程度の位置は跳毬獣の鳴き声でわかるはずだ。当てられなくてもいいからお前が考えられる最良の方法でやれ。いいな」「はい」

  するとケライは首の後ろに釣り針を引っかけると，豪快に振り回しはじめた。マッパの身体があちこちの木にぶつけられ，枝をへしおりながら，次第に高さを増してゆく。ケライは以前のケンカを通して，マッパがこの程度で怪我しないことは知っているが，それにしても乱暴である。

  竿を大きく振りながら，ケライは跳毬獣の群れが発する鳴き声に耳を済ませる。敵はくるくると空を舞うマッパに怯んだ。かわりに棒立ちのケライに狙いを定めたようだ。釣り竿から伸びる糸が見えていないのかもしれない。

  鳴き声はそこかしこから聞こえてくる。はじめは四方八方から発せられるようにも思えたが，やがて一定のパターンがあることがわかってきた。やはり跳毬獣には見えているようだ。マッパを使って時間稼ぎをしたのも功を奏した。ケライが糸を巻き取り始める。マッパとの距離が近づくにつれ，回転速度がぐんぐん上昇する。

  大きな影。それが見えた瞬間，激しい勢いで木に叩きつけられた。直後，何かの折れるような鈍い音が聞こえる。音のした方を見ると，黒く，大きなコウモリと，その首に両腕を回してしがみつくマッパの姿があった。

  「ヒモを渡せ」マッパが叫ぶ。ケライはコートを脱いで，その下にあるカバンから折りたたんだ紐を取り出してマッパに投げた。伸縮性に富んだ紐で，暴れようとするそれをマッパが手際よく縛りあげてゆく。まるで，捕獲するとはこういうことだ，とお手本を示すようだ。

  マッパはモンスターの両翼と口を結び，相手の身動きがとれなくなったのを確認するとようやく離れた。胴体の毛に跳毬獣の爪をいくつもひっかけている。やはりこいつは跳毬獣をエサとしているようだ。

  さらに，こいつの両足は人間の手のように何かを掴みやすい構造をしている。跳毬獣の爪は鋭く，両足に持って使いこなせれば猛禽類の足のように強力な武器となる。エサを食し，そこから爪を奪って新たなエサを得るのだろうか。跳毬獣からすれば，死して後，仲間の命を奪うために自分の身体が悪用されるのだ。なんとも憐れである。

  調査隊にとって幸運だったのは，このモンスターに遭遇したのが超人のマッパだったということである。とはいえ，空を飛ぶ相手と一対一でやりあっていればかなり手こずっていたはずだ。棒立ちのケライが自身を囮としたおかげで，強力なモンスターを生きたまま捕獲できたのである。

  よくやった。そうケライを褒めようと振り向いた瞬間。

  ケライの身体は天からのびる雨とともに空と結ばれていた。一切の動きをせず，その小さな身体が地面から離れてゆく。

  「ケライっ」

  マッパが急いでケライに飛びつく。すると，さすがに二人分の重みには耐えきれなかったのか，水飴のような糸が切れた。マッパはケライをかばうように地面に倒れ込む。そしてすぐにケライにコートをかぶせ，空を見上げた。そして悟った。アルジをさらったのがあいつだと。だが何だ。この空には何が潜んでいるんだ。

  マッパはケライの脈を取り，胸に耳を当てる。気絶したように反応はないが，心臓はちゃんと動いているし，息もある。とりあえず安心だ。ただ一刻も早くここからケライを退避させなければならない。マッパはケライを抱え，麓のキャンプへ向かった。その背後で，捕獲したばかりのモンスターが，空から降るいくつもの糸によって空に運ばれていった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
