#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 123

  光が失われてゆく。世界とのつながりが閉じてゆく。耳に残るのは，わずかに，あのねちねちとした，粘つくような，虚凧の迫る音。だが身体はこわばったままだ。全身をはりめぐらせていた感覚の線が，するすると，身体の中心に回収されていくのがわかる。身体の末端から，細胞がひとつひとつ，永久の眠りについていく。

  <br>

  ボッチ達は虚凧を追い払った後，森に設営したテントまでアルジを運んだ。その体温は著しく低い。ミミは迷わずアルジの服を脱がすと，自身の衣服の下にその身体を抱いてから毛布で二人を包んだ。そして真っ赤な顔で目を反らすボッチに薬湯を温めるよう告げ，シンキに指定した物を粉末にするよう指示する。シンキは血行を促進するハーブと食料をすり鉢で混ぜ始めた。

  その間，自分は息を吸ってはアルジの肺に温かな空気を送り込んだ。代わりにアルジの口からひんやりした空気が吐き出される。ボッチが湯気ののぼる薬湯を持ってきた。ミミは空気を送る合間に，温かい薬湯を口に含み，飲ませる。徐々にアルジの口から漏れる空気が生温く変わってきた。心音も確認できるほどに回復してくる。

  <br>

  首元まで退いた熱の束がそこで止まった。

  やがて再び熱が沸き出す。それは湯気のように，再び頭に向かってゆっくりと立ちのぼっていった。あご。下唇。うなじ。耳たぶ。鼻筋。そしてその熱が目元に至り，うっすらとまぶたが開かれた。

  耳元で誰かが話すのが聞こえる。内容ははっきりしない。ただ，温かい空気が肺を満たし，柔らかく穏やかなものに包まれているような心地良さがある。

  <br>

  「アルジさん，目を覚ましましたよ」ミミが小声で言う。

  「ほんと!？はぁー，よかったぁ」命を取り留めたことがわかり，シンキはアルジに負けないほど力が抜けてしまった。「帰ったら反省文だな。千枚で許してやる」ボッチも安心したのか，いつも通りの意地悪を言う。「ちょっとそれひどいよー」

  「アルジさんの様子はどう？」「そうですね。中で硬くなったので，落ち着いていると思います。無理に身体を動かすのはよくないので，今晩はここに泊まれるといいのですが」

  「キセイ，ちょっといいか」ボッチはテントの外でコッコの羽根を漉くキセイに声をかけた。キセイはボッチの方を見たまま棒立ちになっている。お前が来い，という合図だ。ボッチはテントを出てキセイにいくつか話をし，キセイは何度か頷いた。

  ボッチがテントに戻ってくる。「やつらが今晩襲撃してこないよう，俺たちが交代で見張ることにする」「あたしも手伝うよ」シンキが言った。「わかった。じゃあ夜の当番表を作ろう」

  その晩，兜を開け，久々に野に放たれたコッコは最強の番犬として自由に森を駆け回った。ミミはボッチ団に守られ，アルジを暖めつづけながら，薬湯の投与と，呼吸の補助を行った。また，シンキの作った粉末と水を混ぜあわせて与えた。アルジはまだ完全に意識を取り戻すほどは回復していなかったが，空腹だったのか，それを全てたいらげた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
