#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 124

  その夜ボッチたちが過ごしたテントは，森を進んで開けた場所に設営されている。先日，霧に退路を断たれたと考えたボッチは森へ入った。そこへキセイがコッコに乗ってやってきて，無言で護衛を務めたのだった。そうしてこの場所を見つけ，新たな休憩地点とした。ただしこの場所を見つけたのもコッコなので，さほどボッチの手柄があるわけではない。とはいえボッチが森の探索を始めることなく，他の隊員とともに霧近くのテントで待機しつづけていたら，アルジの信号弾に気づくこともなかったかもしれない。ボッチはある意味アルジの命の恩人である。アルジはかつて身を賭して，まあ本人は裂掌獣と戦いたかっただけなのだが，とにかくボッチ団全員の命を救った。今回のことについてボッチが借りを返したと思っているかどうかは定かではない。ただ少なくとも，アルジを救うきっかけになったのは間違いない。

  信号弾を放った場所がボッチたちの気づく範囲内だったのは大きな幸運だ。だがそれだけでは助からなかった。慎重なボッチがアルジの影響を受け足を踏み出せるようになり，またアルジ自身も，ボッチたちの影響を受け，助けを求められるようになった。偶然の糸をたぐりよせられる力が隊員に備わりつつあるといえるだろう。

  さて残るのはボッチ団がどのようにして里へ帰るかという問題だが，さほど難しいものではない。

  なんと，川を覆っていた霧は朝とともに晴れてしまったのだ。また，夜のうちにミミが霧を採取し密閉していたのだが，そのビンを染めていた闇も朝には消えてしまった。この霧は夜のうちだけ張るようであり，昼のうちに川を渡れば問題はないようだ。それを知ったシンキたちは，これまで心配したのが損とでも言うように笑った。

  <br>

  と，ぬか喜びさせておいてから叩き落とされるのはいつものことだ。テントの隅に置いていたビンに，黒いもやが生じていたのだ。それが意味するのは，風の滞ったあの川には常に闇が在り，光の下ではその姿を隠している，という恐るべき可能性である。自分たちは川を渡る際，そして豚のような獣を狩る際，すでにあの空気を吸い込んでいる。身体は既に蝕まれていてもおかしくない。さらに不運なことに，ビンの中身が変容しているのを確認したのはアルジを救出した晩のことだった。つまり，ミミはその身体を通してアルジに伝染してしまった可能性があるのだ。

  あの霧がまともでないことは，あの豚のような獣，ボッチが苔豚モムルと名づけたもの，からも示唆された。ちなみに余談だが，ボッチにとってこの地のモンスターを命名するのは初めてであり，苔豚モムルというのは半日かけて悩みぬいた末につけたものである。その割に凡庸な名前なのはボッチの性格の表れであることを承知していただきたい。ともかく，この獣は鼻や目元などが塞がり，あたかも粘膜を空気に触れさせたくないかのようだ。この特徴を，川の霧を取り入れないようにするためのもの，と考えると納得できる。

  いずれにせよ里で診断を受けるまで，この霧がどのような悪意をもつものなのかはわからない。まあ身体にいいということはないだろう。不安の中でボッチたちは眠った。そうはいっても考えが頭をめぐる。ボッチは目を閉じて考えていた。もしあの霧が始終毒のあるものなら，苔豚が生息することもできないはずだ。少量ならば分解できるのだろうか。それとも時間帯によって毒性が変わるのだろうか。

  一方，アルジを感染させてしまったかもしれないと涙ぐむミミをシンキは夜通しなぐさめた。あそこでミミが手当をしなかったらアルジはもっと危険になっていたはずだから，ミミは正しかった，今はアルジを少しでも回復させることの方が重要だと。事実，何も知らず穏やかな顔で眠るアルジは，半日前からは想像もできないほど血色もよくなっていた。自力で十分なだけの呼吸もできているし，その寝息を首筋で感じると，ミミの気持ちも少しは安らぐのだった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
