#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 125

  空が明るさを取り戻す頃。すなわち霧を収めたビンの色が失われる頃。ボッチ達は里へ引き返し始めた。

  川岸のテント跡を経て，川を渡ってしばらく進み，ようやく獣車の留まる森のキャンプまで帰ってきた。二晩以上空いてしまったが，幸いダモスは無事だった。これまで説明してきたとおり，荷車を引けるだけの強い力をもつ家畜は里に二頭しかいない。それがこのダモスであり，一頭でも失えば里は大きな打撃を受けることになる。南との連絡が断たれたまま，これほど調査が広範囲に及ぶことは想定されていなかったため，出城としてのキャンプに資材を輸送できる二頭のダモスは虎の子である。それでありながら，隊員がキャンプを離れている間，ダモスは無防備におかれる。かといって監視のために一人置く，というのも現実的ではないし，敵の襲撃を一人で撃退できるのは限られた隊員だけだ。このいびつな状況をなんとか打開できるとよいのだが。

  そこから里への道中，ボッチは自分たちがなんらかの病に感染している可能性を手紙にしたためた。そして信号弾でビュンを呼ぶと，その手紙を持たせて送り返した。キャンプからは直接信号弾が里に届かない。不便である。こんなところに建てるなんてありえない，とマッパなら言うだろう。だがここは，数あるキャンプのなかでも群を抜くほど充実しており，解体して別の場所に移す，といった作業が行いにくい。まだボッチ団がピクニック気分で，というのは失礼な言い方だが，調査を行っていた頃の名残りだ。

  <br>

  五人が里の外にたどりつくやいなや，獣車に乗り込んでくる者があった。

  「ケライさん」ミミが驚く。ボッチは自分たちが危険であると警告する。だがそれも構わず，ミミの懐にアルジの姿を確認すると，ぶつかるような勢いで抱きついた。そのまま呼びかけても返事をせず，微動だにしない。

  ミミはその様子にふっと笑みをこぼした。「ボッチさん，これをショムさんに。お願いします」ミミは霧の入ったビンと，ショムへの手紙をボッチに渡した。このビンに，ここにいる全員の命がかかっている。

  <br>

  ボッチが獣車を降りると，外に白ずくめの人物が立っていた。ショムである。

  「それですか」マスク越しに声が発せられる。ボッチはうなずき，ミミから託された物を渡した。

  ビンと手紙を受け取ったショムがつづける。「みなさんにはしばらく里の外で過ごしてもらうことになります。ケライさんも」

  「安心しろ。みんな落ち着いている。他に必要なことはあるか」「そうですね，できれば，遭遇した生物の報告を，忘れないうちに」「わかった。他にやることもないからな。気晴らしになるだろう」ショムが申し訳なさそうに言うのを，ボッチは気にしないように配慮した。

  「そうだ」ボッチがひとつ思い出したように言った。「アルジに栄養をつけさせたい。何か送ってくれるとうれしいんだが，できるか」ショムはそのことでハッとした。「え，ええ。もちろん。ごめんなさい，忘れてて。アルジさんもいたんでしたね。すぐ送ります」

  それからいくつか確認をして，ボッチは獣車に戻った。シンキがにやけている。

  「なんだ」ボッチが照れる。「さっすが隊長だね。かっこいー」「からかうな」ボッチは顔を赤くしたまま，いくつかの資材に手を伸ばす。

  しばらくして獣車の外にテントが張られ，やや離れたところにいくつかの穴と仕切りが作られた。里を目前にしながら，ボッチ団とアルジ，ケライは隔離されることとなった。

  獣車は居心地がいいというわけではないので，アルジとボッチが獣車に残り，他はテントで過ごす予定になっていた。だがミミはアルジが目覚めるまで面倒を見ると言い張り，ケライも離れないため，テントにうつったのは結局シンキのみとなった。キセイは相変わらずコッコやゴリ，ワンワと過ごしている。シンキを仲間外れにするような事態となったが，本人は広々としたテントで寝泊まりできることに満足しているようなのでまあいいだろう。もしくはせっかくボッチが張ったテントを無碍にするのもよくないと思ったのかもしれない。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
