#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 125

  空が明るさを取り戻す頃。すなわち霧を収めたビンの色が失われる頃。ボッチ達は里へ引き返し始めた。

  川岸のテント跡を経て，川を渡ってしばらく進み，ようやく獣車の留まる森のキャンプまで帰ってきた。二晩以上空いてしまったが，幸いダモスは無事だった。これまで説明してきたとおり，荷車を引けるだけの強い力をもつ家畜は里に二頭しかいない。それがこのダモスであり，一頭でも失えば里は大きな打撃を受けることになる。南との連絡が断たれたまま，これほど調査が広範囲に及ぶことは想定されていなかったため，出城としてのキャンプに資材を輸送できる二頭のダモスは虎の子である。それでありながら，隊員がキャンプを離れている間，ダモスは無防備におかれる。かといって監視のために一人置く，というのも現実的ではないし，敵の襲撃を一人で撃退できるのは限られた隊員だけだ。このいびつな状況をなんとか打開できるとよいのだが。

  そこから里への道中，ボッチは自分たちがなんらかの病に感染している可能性を手紙にしたためた。そして信号弾でビュンを呼ぶと，その手紙を持たせて送り返した。キャンプからは直接信号弾が里に届かない。不便である。こんなところに建てるなんてありえない，とマッパなら言うだろう。だがここは，数あるキャンプのなかでも群を抜くほど充実しており，解体して別の場所に移す，といった作業が行いにくい。まだボッチ団がピクニック気分で，というのは失礼な言い方だが，調査を行っていた頃の名残りだ。

  <br>

  五人が里にたどりつくと，すぐさま獣車に乗り込んでくる者があった。

  「ケライさん」ミミが驚く。ボッチは自分たちが危険であると警告する。だがそれも構わず，ミミの懐にアルジの姿を確認すると，ぶつかるような勢いで抱きついた。そのまま呼びかけても返事をせず，微動だにしない。

  ミミはその様子にふっと笑みをこぼした。「ボッチさん，これをショムさんに。お願いします」ミミは霧の入ったビンをボッチに渡した。このビンに，ここにいる全員の命がかかっている。里を目の前にしながら，ボッチ団とアルジ，ケライはしばらく獣車のなかで過ごすことになる。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
