#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 126

  「私が先に毛鞠獣と名づけたんだから毛鞠獣だ。それに毛鞠獣のほうがモンスターの特徴をより正確に捉えている」「記録しなければ意味がありません。モンスターの名前は跳毬獣です。不満があるならアルジさんが正しいという証拠を出してください」

  ボッチ達が里から隔離されてから数日。体力と意識を回復したアルジは，ケライとの会話のなかで食い違いが生じた。それからずっと，ミミに抱かれたままの奇妙な格好で口論を続けているのだ。アルジが毛鞠獣テンバイと名づけたもの，それはケライが既に跳毬獣フフコルとして報告書に記してしまっていた。せっかく名づけたものが活かされないということでアルジは不満に思い，こうしてケライに言いがかりをつけているのである。

  自分が先に見つけていた，なんていくらでも言える。さらわれた空白があるとはいえ，記録を残さなかったアルジが何を言おうが説得力はない。アルジ自身それはわかっている。だが，すでに自分のなかで毛鞠獣として知識の回路ができてしまったものを，誤りだからといって書き直さなければならないのは苦痛なのだ。ここにきてようやくアルジは調査に伴うしがらみというものを経験していた。

  悪いことは重なるもので，アルジを襲撃したモンスターにも別名がつけられていた。アルジのなかでは虚凧ディディンナであったもの，それはボッチによると楠蜘蛛ベレエケである。こちらはこれから報告書にするところなのだが，代筆されなければ文字を書けないアルジは不利である。

  それだけではない。アルジは黒鼈甲ルンマ，天巾アールケナン，さらには塔粟蟹スサルバといった，アルジだけが知るモンスターについて記さなければならないのだ。事実，跳毬獣の命名議論などは既に終わったこととして，ケライは針山で出会ったコウモリについて骸飛鼠サザクレオという名で報告書を書き始めている。ボッチも同様だ。

  「アルジさん，私が代わりに書きますから，アルジさんが見つけたモンスターについて報告書を書きませんか」我を失ったように混乱するアルジをミミがなだめようとする。アルジは自分の知らないところで世界が書き換えられてゆくような気がして，落ち着いていられないのだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
