#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 127

  本章ではストーリーに進展はない。よって時間を進めたい読者は飛ばしてほしい。

  ミミに促され報告書を書き始めたアルジだっだが，当初，その作業は捗らなかった。書庫が使えず，資料が手元にないため引用ができないのだ。どうしても文章がぶつ切りになってしまう。これに対し頭の中に図書館をもつケライ，事実のみを記述するボッチは順調である。ミミも代筆をかって出たものの，いろいろと勝手が異なるのでアルジを助けるのは難しい。アルジは字が読めなくても，書庫のどこを調べれば目当ての情報があるのかある程度はわかっている。あとはそれを読んでもらえば特定できるのだが，隔離されているかぎりこの方法が使えない。

  ただそれで立ち止まっているわけではない。いくつかの試作品を経てできあがったアルジ用のタイプライター。それがアルジの目の前にある。隔離されて自由に動けないこの状況は，アルジが自力で書く能力を得る絶好の機会だった。このタイプライターは鍵盤のかわりに大きなレバーが一つあり，傾けた角度に対応した文字が打ち込まれる。文字の種類が少ない言語ならではの工夫がなされた道具だ。

  以前はこのレバーがダイヤル式のスイッチになっていて，角度を合わせてスイッチを押し込むと文字が入力されるようになっていた。ただそれでは腕，というか肘，にかかる負担が大きく，手間もかかるということで改良されたのだ。出したい文字の角度さえ頭に入れてしまえば，言葉を読めなくても書くことができるのだから，アルジにとってこれほどありがたいものはないだろう。

  当然ながら打ち出される内容をアルジは読めない。誤字もそこそこある。ただ，代筆にくらべれば，校正はそれほど大変ではない。文章の質についてもケライとボッチに鍛えられているだけあって悪くない。白紙，というほど上質の紙ではないが，それを自分の意思が伴ったインクで埋められるということが，アルジには魔法のように思えた。

  アルジにとって幸運だったのは，機械を作ったミミの存在もあるが，話し言葉と書き言葉との違いをケライが明確に指導したことである。ケライは書き方のルールが記された本を書庫から見つけ出し，まず，頭で考えるときに使う言葉，話し言葉，そして書き言葉の間には大きな違いがあることを教えた。そしてアルジも知っているはずの単純なルールから再学習させ，違いを意識させるようにした。そのなかには禁則処理などの基本的なことから，段落の構成といったやや複雑なことが含まれている。その後は徒弟的に添削を受け，シッショのような絵日記レベルの文章から脱却できたのである。なんとうらやましいことだろうか。

  とはいえシッショの名誉のために言っておくと，シッショは獣人であり，戦士である。もともとケライ達とは違う言語で暮らしていたし，母語以外で書くのは大変だ。里の面々と自由に意思疎通でき，率先して調査を行っているだけでも立派である。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
