#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 130

  シッショの一番恐れていたことが起きた。

  岸から離れた水面に，クビワが力なく浮かんでいる。

  「クビワ…」腰がぬけそうになるのをこらえ，シッショは地面に槍を深々とつきたてた。袖をまくり，手首に仕込んだフックをひっかけ，湖へと走り出す。甲高い音をたてながらフックから糸がのびる。

  クビワは泳ぐのが得意なはずだ。それがどうして。モンスターに襲われたのか。そんな疑問を持ったままバシャバシャと水をかきわける。湖は深い。足がつかなくなった。シッショは水が苦手だ。泳ぐのも苦手だ。自然と身体の動きは犬かきになる。だがクビワへの思いが恐怖心を凌駕した。

  あと少し。そう思った瞬間，ふいにシッショの身体が異様に重くなった。まるで接着剤がまとわりつくように，手足の動きが鈍い。こんなに自分は疲れやすかったか。それでも渾身の力でクビワへとたどりつく。

  「クビワっ!」運よく横向きのまま浮いていたクビワは，気を失いながらもなんとか呼吸はあるようだ。何かにこすれたのか，少し身体に赤みがさしているが怪我はなさそうだ。よかった。

  だがそんな安心はすぐに消し飛んだ。少しでも不安の心が消えた自身を激しく後悔した。クビワの全身に何か粘つくものがまとわりついている。いや，クビワだけじゃない。シッショにも。

  なんだこの水は。シッショはクビワを抱きかかえたまま，周りを見回した。

  水飴のようにきらきらと光を反射する湖面。だが違和感があった。これだけシッショたちが暴れたにも関わらず，波紋ひとつたたない。まるでスローモーションのように，波打つこともなく水が元に戻ってゆく。シッショは苦手なのを我慢し，水面を見下ろした。

  湖の奥深く，丸い透明な粒がひしめいている。そして自分がいる状況の恐ろしさにシッショは総毛立った。吐き気がした。全身が震え，泣き出しそうになった。誰か。

  これは湖じゃない。何かが吐き出した粘液のかたまりだ。この底にある透明な粒の軍団，ナマコのような何か，正体は定かではないが，それが大勢集まり，湖を模した巨大な罠を作っていたのだ。

  これだけ枯れた大地だ。水を求めて多くの生物がやってくるだろう。それを捕らえ，時間をかけて溶かしてしまう。クビワと自分はまんまとその罠にはまってしまった。

  クビワ。その胸に顔をうずめてシッショは震えた。

  「ん…」

  ハッとする。にじんだ視界でクビワを見る。そうだ。クビワは生きている。今クビワを助けられるのは僕だけなんだ。

  クビワ。愛してるよ。

  シッショは槍のフックが外れないことを祈り，手首のスイッチを起動した。腕がミシミシと音を立て，その激痛にシッショが吠える。すさまじい抵抗に，手首の機構から煙があがる。だが少しずつ，確実に二人の身体が持ち上がっていった。

  ふいに，空気の抜けるような音があり，二人の身体が宙に浮いた。そのまま透明な湖面を滑ってゆく。

  やがてなつかしい，荒れた大地へと戻ってきたのを感じ，シッショは意識を失った。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
