#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 128

  その日，ショムが獣車をのぞきこんでボッチを探した。白装束でないところを見ると，期待が持てる。

  「あら，みんないるんですね。説明の手間が省けたかも」「霧の結果が出たのか」ボッチが獣車から身体を乗り出して問う。ショムはうなずいて話しはじめようとした。

  「待て。シンキを呼んでくる」

  <br>

  全員はテントに集まり，ショムの分析結果を聞いた。ミミが採集してきた霧には恐ろしい生命体がひそんでいた。肉食性の細菌である。この菌は昼間は殻に閉じこもり，眠っている。その間，体内で共生する生物が光合成を行い，エネルギーを分けてもらうことで生きているのだが，日が傾くと，殻をやぶり黒い本性を現すのだ。それは呼吸などを通して相手の体内に入りこみ，ひたすらに食い，増える。もし，夜に川沿いを歩いたりなどして，殻をやぶった黒い霧を吸いこんでいたら，ボッチたちは全滅していた可能性が高い。

  幸い，ボッチたちは無害な状態で取り込み，体内の免疫システムが駆除できたため無傷で済んだ。また，苔豚モムルは目や鼻といった，菌が入りこむ場所を封じることで，夜の霧でも生活できている。夜通し呼吸しないことはないだろうからどこかで安全な空気を得ているのだろうが，この霧は苔豚にとって天敵のいない楽園なのだ。

  「ということは，俺たちはもう菌をばらまくようなことはないわけだな」

  ボッチが言い，全員が安堵する。

  「蝕霧ディエボラン」アルジがつぶやいた。「え？」「蝕霧ディエボラン。その菌の名前です」

  ショムが不思議な顔をする。アルジは必死だった。生物だとわかればいちはやく名前をつけなければ。アルジとケライたちに起きた口論をショムは知らない。ただこの菌はモンスターのような凶暴性はあるがモンスターではない。こうした名づけをするのは不適切なのだ。それをアルジは知らない。

  「ああ，こいつはバカだから気にしないでくれ」事情を説明するのは面倒なのでボッチが一言で説明する。

  だがケライがその言葉にかみついた。「アルジさんはバカじゃありません」

  そういう意味じゃない。ボッチが弁解しようとすると，ケライがたたみかけた。

  「アルジさんはバカで無知で無能で命知らずで礼儀知らずで貧弱でノロマでブサイクですぐにケガしてすぐに死にかけてすぐいなくなって人に迷惑かけて心配させるのだけは天才です」

  「そしていつもケライを悲しませるロクデナシです」アルジがケライの言葉に乗った。「わかっているなら直してください」「すみません」「謝らなくていいので直してください」「努力します」

  ケライがアルジをひたすら罵倒し，アルジが平謝りした。それだけなのに，なぜかそこにいた全員の心が温かくなるのだった。

  そのとき。

  ドン，と大きな地鳴りが襲った。

  「伏せろ!」ボッチが叫ぶ。言われるまでもない，といった速さで，即座にアルジがケライをかばい，ミミが二人に覆いかぶさる。

  身体を丸めていても揺さぶられるほど大きい。里の建物は大丈夫か。オヤブンたちは。

  揺れがおさまるのを確認して，皆が目を合わせ安全を確認する。ショムは立ちあがって里へ走った。

  「俺も里を見てくる。お前たちはここにいろ」そう言ってボッチも里へ向かった。

  「アルジさん，重いです」「ああ!ごめんなさい，重いのは私です」ケライの言葉にミミがあわてて飛びのき，アルジも起き上がる。ただ，なおもミミの身体がカタカタと震えているので，背中に腕をのばし安心させようとした。ミミはたまらずアルジを抱き締めた。骨がきしむほどの強さで。

  「シンキさん大丈夫ですか」アルジが息苦しそうに声をかける。シンキは震えるキセイを抱きしめながら「あたしは平気。結構怖かったけど。それよりみんなは？ケガしてない？」と答えた。

  「ボッチさんの足が曲がってましたけど」アルジは目ざとい。「ボッチはああ見えて臆病だからねー。みんなからかわないでね」ボッチは気丈にふるまっていたが，腰が引けていたようだ。

  テント内の全員が落ち着くのを待って，アルジたちは隔離されて以来久しぶりに里へ帰った。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
