#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 128

  「俺は疫病神か」

  石膏で固めたシッショの腕。それに包帯を巻きながら，マッパが文句を言った。マッパが誰かを連れて調査に出るたび，怪我人が出る。今回の被害者はシッショだ。ただ今回は脱臼で済んだため，比較的軽傷といえる。

  「面目ない」「シッショいじめたらころすぞ」「いじめてないよ。クビワが無事で本当によかった」その言葉にクビワは喜び，シッショの顔をなめる。

  「まあ，お前が命を捨てなかったのはほめてやる」包帯をカットしたマッパはシッショの背中を叩いた。マッパは冗談のつもりだったが，クビワはシッショをかばうように抱きしめ，マッパを睨む。

  シッショはクビワのぬくもりを背中に感じながら，マッパにはなんでもお見通しなのだと思った。シッショはフックの糸では二人を引き上げられないと思った。そこで腕輪をはずしてクビワにはめ，クビワだけでも助けようとしたのだ。だが自分の短い指では腕輪を外せず，やむを得ず二人の命を賭けることになった。ミミに渡されたときには気づかなかったが，極端に指の短い，獣人の手であったことが幸いした。おそらくミミ自身，こんなことになると思っておらず，シッショが自力で外せないことにも気づいていなかっただろう。

  だがその腕についたひっかき傷から，マッパは全てをさとった。シッショがクビワのために自分の命を投げ出そうとしていたことを。

  だからマッパは不機嫌だった。「シッショ」その言葉にシッショはクビワに向けていた目を戻す。「クビワのことを本当に思うなら，死んでもいいなんて絶対に思うな」

  その言葉にシッショは顔を伏せる。クビワには意味がわからない。「誰かのために死ぬなんてな，ただの身勝手だ。クビワのためにお前が死んだら，クビワは永遠にお前のことを忘れられなくなる。それは呪いだ。不幸にさせるだけだ。今後，どれだけ楽しいことがあろうと，幸せなことがあろうと，あるとき，ふと，お前を思い出し，悲しむ。本当にクビワの幸せを願うなら，一日でもクビワより長生きするんだ。いいな」

  あーっ!

  いきなりマッパは大声で叫んだ。シッショが驚いて飛び上がる。

  「臭っせーこと言ったら鳥肌がたっちまった。寝る!」

  そう言うとマッパはまだ夕方にも関わらず横になってしまった。

  こいつはバカなのか？そんなふうに，クビワが明らかにマッパを侮辱しようと口を開いたので，シッショがその口を塞いで笑顔を見せた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
