#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 128

  その日，ショムが獣車をのぞきこんでボッチを探した。白装束でないところを見ると，期待が持てる。

  「あら，みんないるんですね。説明の手間が省けたかも」「霧の結果が出たのか」ボッチの問いにショムがうなずき，話しはじめようとする。「待て。シンキを呼んでくる」

  <br>

  ミミが採集してきた霧には恐ろしい生命体がひそんでいた。肉食性の細菌である。この菌は昼間は殻に閉じこもり，眠っている。その間，体内で共生する生物が光合成を行い，エネルギーを分けてもらうことで生きているのだが，日が傾くと，殻をやぶり黒い本性を現すのだ。それは呼吸などを通して相手の体内に入りこみ，ひたすらに食い，増える。もし，夜の，殻をやぶった黒い霧を吸いこんでいたら，ボッチたちは全滅していた可能性が高い。

  幸い，ボッチたちは無害な状態で取り込み，体内の免疫システムが駆除したおかげで無傷で済んだ。また，苔豚モムルは目や鼻といった，菌が入りこむ場所を封じることで，夜の霧でも生活できている。夜通し呼吸しないことはないだろうからどこかで安全な空気を得ているのだろうが，この霧は苔豚にとって天敵のいない楽園なのだ。

  「ということは，俺たちはもう菌をばらまくようなことはないわけだな」

  ボッチが言い，全員が安堵する。

  「蝕霧ディエボラン」アルジがつぶやいた。「え？」「蝕霧ディエボラン。その菌の名前です」

  ショムが不思議な顔をする。アルジは必死だった。生物だとわかればいちはやく名前をつけなければ。ショムはアルジとケライたちに起きた口論を知らない。そしてこの菌はモンスターのような凶暴性はあるがモンスターではない。こうした名づけをするのは不適切なのだ。それをアルジは知らない。

  「ああ，こいつはバカだから気にしないでくれ」事情を説明するのは面倒なのでボッチが一言で説明した。

  だがケライがその言葉にかみついた。「アルジさんはバカじゃありません」

  そういう意味じゃない。ボッチが弁解しようとすると，ケライがたたみかけた。

  「アルジさんはバカで無知で無能で命知らずで礼儀知らずで貧弱でノロマでブサイクですぐにケガしてすぐに死にかけてすぐいなくなって人に迷惑かけて心配させるのだけは天才です」

  「ケライ先生ごめんなさい」アルジが謝る。「謝らなくていいので直してください」「努力します」

  ケライがアルジをひたすら罵倒した。それだけなのに，なぜかそこにいた全員の心が温かくなるのだった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
