#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 129

  「私が先に毛鞠獣と名づけたんだから毛鞠獣だ」「記録しなければ意味がありません。モンスターの名前は跳毬獣です。文句があるなら先に名づけたという証拠を出してください」

  ボッチ達が里から隔離されてから数日。体力と意識を回復したアルジは，ケライとの会話のなかで食い違いが生じた。それからずっと，ミミに抱かれたままの奇妙な格好で口論を続けているのだ。アルジが毛鞠獣テンバイと名づけたもの，それはケライが既に跳毬獣フフコルとして報告書に記してしまっていた。せっかく名づけたものが活かされないということでアルジは不満に思い，こうしてケライに言いがかりをつけているのである。

  自分が先に見つけていた，なんていくらでも言える。さらわれた空白があるとはいえ，記録を残さなかったアルジが何を言おうが説得力はない。アルジ自身それはわかっている。だが，すでに自分のなかで毛鞠獣として知識の回路ができてしまったものを，誤りだからといって書き直さなければならないのが苦痛なのだ。ここにきてようやくアルジは調査に伴うしがらみというものを経験していた。

  悪いことは重なるもので，アルジを襲撃したモンスターにも別名がつけられていた。アルジのなかでは虚凧ディディンナであったもの，それはボッチによると楠蜘蛛 (くすぐも) ベレエケである。こちらはこれから報告書にするところなのだが，代筆されなければ文字を書けないアルジは不利である。

  それだけではない。アルジは黒鼈甲ルンマ，天巾アールケナン，さらには塔粟蟹スサルバといった，アルジだけが知るモンスターについて記さなければならないのだ。こんなことに時間を割いている余裕はない。事実，跳毬獣の命名議論などは既に終わったこととして，ケライは針山で出会ったコウモリについて骸飛鼠 (むくろひそ) サザクレオという名で報告書を書き始めている。ボッチも同様である。

  「アルジさん，私が代わりに書きますから，アルジさんが見つけたモンスターの報告書を書きませんか」ミミが我を失ったように混乱するアルジをなだめようとする。だがアルジは世界が自分の知らないものに書き換えられてゆくような気がして，落ち着かなかった。

  毛鞠獣は毛鞠獣だし虚凧は虚凧だ。

  そんな自分を無視するように作業が進むので，アルジがあわてていると，ふいに自分の口がミミのそれで塞がれた。

  前とは違う。もう自分で呼吸もできるし，意識もしっかりしている。これまで散々見せられたものの，それとは明らかに違う目的で行われたことにボッチが呆気にとられる。

  アルジの身体から力が抜けたのを確認すると，ミミはようやく顔を離した。二人の唇をぬぐい，「報告書を書きましょう」と穏やかな表情で言う。

  「かきましょう」アルジは魂を吸い取られたかのような抑揚のない声で答えた。「ほうこくしょをかきましょう」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
