#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 129

  「湖なんてないけど」シッショが事実を口に出す。「そうだな。前はあったんだが」マッパはそれに応じるように過去の記憶を述べる。

  シッショはいらだった。「マッパさんが嘘をついてるとは思わない。でも僕らの気持ちもわかってほしい。マッパさんが最優先だっていうから」「最優先だ。船を組み立てずに済んだんだから好都合じゃないか」そう言ってマッパが山を下りはじめる。シッショはしぶしぶとついていき，クビワは羽織ったコートの違和感に不機嫌だった。

  里にシッショとクビワが帰還した日の晩，マッパとケライも帰ってきた。マッパは身体にしびれの残るケライをショムに託すと，オヤブンに報告中だったシッショの元へやってきた。そしてシッショたちを連れ明日早々に針山を越えると言ってきたのだ。それはシッショたちの狙いと衝突するものだった。クビワは湿地付近で兄の匂いを感じた。手がかりを得るためには追加の調査が必要だ。ここでマッパの調査に加わったら，貴重な機会を逃すことになるかもしれない。

  だがクビワの兄はすでに死んだ。クビワを守るために。それはクビワ自身から語られた事実だ。かたや自分たちは生きている。いや，これからも生きていたい。そのためには北の大陸により詳しくなるか，紫針竜を倒す方法を見つけるしかない。

  オヤブンの決定はマッパの意見に従うというものだった。その調査が済み次第，すぐにクビワの兄の手がかりを追うということで，シッショは表向きは納得した。

  シッショとクビワを針山に連れてきたのはマッパとともに船を組み立て湖を渡るためだ。小舟では沈むおそれがあるから，それなりに大きなものが必要だった。それがいざ針山の先から見下ろしてみたら，湖の痕跡さえもないのだ。もし湖があったのなら，水草や汚泥といった，かつて湖の底であったものの残骸があるはずだ。しかし昔からそんなものなどなかったかのように，地面は乾ききっている。

  こんなことなら自分たちはわざわざ来なくてもよかったのに。重い材料を運んできたシッショは不満だった。

  <br>

  針山を抜け，三人はまっさらな大地に降りたった。草木も生えぬ，とはこのことで，その地面は荒れはてている。おそらく雨もほとんど降らないのだろう。ただ平地の広さはそれほどでもない。ここは山々の窪地にあたるようだ。煙を上げる山々が視線の先にある。あれは火山か？仮にそうだとしても，風は針山から吹くので，こちらに有害なガスが溜まらずに済んでいるのかもしれない。

  早々にコートを脱ぎ捨てたクビワは大きく伸びをする。「そんなに着心地悪かった？」シッショもコートを脱ぎながら聞く。「せまい。チクチクする」

  「そうだ。服は窮屈だからな」マッパは自信満々に言った。

  マッパは二人にテントを張るよう言って，食料などを取るために針山のキャンプへ戻った。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
