#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 132

  クビワが酔っ払ったかのようにふらふらするのを支えながら，シッショは蒸気を吹き出す岩の群れに目を凝らす。こっちに既に気づいているのだろうか。もしくは早く縄張りから出ていけと威嚇しているのだろうか。

  「俺が釣り出す。お前らが急所を狙え。いいな」「待って。戦うの？」「ああ。あいつが俺たちの進路を塞いでいるからな」

  進路？相手に攻撃の意思がなければ，迂回して先を目指せるはずだが。シッショにはマッパの狙いはわからなかったが，クビワを揺すって起こした。「クビワ。敵だ。準備して」

  「おう」寝ぼけたような声でクビワが手を前に突き出す。シッショはクビワの腰につけた籠手を外し，持たせてやった。

  本当に大丈夫かとマッパは心配したが，杞憂だった。籠手を持ったクビワの目にみるみる生気が宿ってゆく。

  「クビワ。あの煙を出してる正面の岩が敵だ。マッパさんが仕掛けるから，横から行こう」「おう」クビワはさっきと同じ言葉で応えた。だが先ほどとは比較にならないほどの殺気を帯びている。

  <br>

  マッパが走った。岩ごと地面が盛りあがり，敵が姿を現す。それはクビワたちが湿地で倒した泥盤獣タルポラに酷似していた。違いはただひとつ。光を反射する，きらめく物質で全身を覆っている。泥盤獣にあったような柔らかい皮膚など全くない。それは身体から析出したものかもしれないが，明らかなのは，はるかに硬いということだ。

  急所を狙え，なんてマッパは気軽に言ってくれたが，そんなものこいつにはないではないか。それでも槍を構え，シッショは駆け出した。クビワも合わせる。

  敵は泥盤獣と同様に背中をこちらに向け，突進してきた。はるかに速い。ここがぬかるんだ湿地じゃないからだ。マッパがすんでのところで回避し，回り込んだクビワが拳を打ち込む。と，クビワの腕がゴムのようにしなった。弾かれたのだ。シッショからは敵の腹が見える。わずかな隙間も覆う鎧。クビワ，やめろ。殴るだけ無駄だ。籠手が欠けるだけだ。

  相手は自身の防御が完璧であるのをいいことに，マッパとクビワをひたすら追う。二人とも華麗に回避するが，少しでもひっかかれば，ブルドーザーのような身体にひきずりこまれ，肉塊になる。片手の不自由なシッショは思うように攻撃の機会が得られない。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
