#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 133

  「これは食えそうにないな」

  その亡骸，後に岩盤獣タルポラ・アプと名づけられることとなるモンスターであったものは，この土地の過酷さを物語るように，猛烈な悪臭を放っている。細胞ひとつひとつまで，捕食されることを拒絶しているのだ。この地で十分な食料は見込めない。そのかわり，ここに適応した細菌にとっては宝の山だ。このモンスターのニオイは，その細菌を体内で飼うか，利用していた証かもしれない。しかもそれが体内の隅々までニオイを沁みつかせ，結果，まずくて誰も手を出さないような身体になったのなら至れり尽くせりだ。

  クビワはなんでも食べるが，さすがにこの肉を口にすれば腹を下すだけでは済まないだろう。鉄板のような身体を持ちあげるのも困難だ。三人はその骸を置き去りにし，マッパの指示で先へ進んだ。

  ただ，シッショには一つ気になることがあった。「マッパさん」

  「何だ」「なんで遠回りしないでさっきのやつと戦ったんだ」

  マッパが立ち止まる。「何が言いたい」「マッパさんは不要な戦いはしない。あいつはこっちから仕掛けない限り攻撃してこなかったはずだ。なんでわざわざ倒そうなんて」「言っただろう。道を塞いでいると」「脇道にそれることもできたかもしれない」「ここに脇道なんてない」「どうしてそんなことわかるんだよ」

  シッショの語気が強まる。クビワを危険に晒した理由を求めているのに，マッパが肝心の説明をしないからだ。

  だがマッパは答えず，また歩きはじめた。シッショはなおも問う。

  「マッパさん，なんで，どうして道がここしかないって知ってるんだ。前に来たことでもあるっていうの？」

  「ある」

  その返事にシッショの鼓動がはねあがる。こんな遠くまで？一人で？でたらめだ。僕の注文にこたえるのが面倒になったのか。でも，もし本当に来たことがあるなら，これまでの針山の先を知らないようなそぶりは嘘だったのか？

  戦いの疲労，混乱，周囲を満たす悪臭で，シッショの足がふらついた。「シッショ，つかれたか？」「いや，大丈夫だよ」クビワには心配をかけまいと，槍を杖がわりに身体を支える。クビワだってそれなりに，疲労，もしくはニオイでつらい思いをしているだろう。

  マッパはそんな二人を気にせず，迷いなく足を進めた。まるで見知った道を歩いているかのように。

  <br>

  「ここだ」

  そう言ってマッパは歩くのをやめた。後をついてきた二人が横に並ぶ。

  視線の先に洞窟があった。山の根元にぽっかりと穴を開けている。この石灰質の土地では，掘ったものもすぐに崩れてしまう。そのためわざわざ穴を掘って暮らすのは割に合わない。つまりこの洞窟を作ったのは，モンスターではない。おそらく。

  いや，それ以上に重要なことがある。ここだ，とは，どういうことだ。目的地なのか。なぜこの穴が目的地なのか。そもそもここに目的地があると，

  「どうして知ってるの」

  心の内で爆発する疑問がノドを押し出し，シッショは思わずそれを口に出してしまった。気持ちが高ぶるあまり，何を指した問いなのか全くわからない。だがマッパはもはや隠す必要がないかのように，それら全ての疑問に一言で答えた。

  <br>

  「俺が観測省の一員だったからだ。昔な」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
