#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 137

  シッショはその言葉に呆然とした。はじめ何を言っているのかわからなかった。シッショはクビワの兄の手がかりについて聞きたかっただけだ。だがそれは，相手に，知っていることを話せ，と追及しているように伝わった。そう思われても仕方ない。書庫で資料を見つけたことなど，過去を探るような質問をしたのだから。そしてマッパは，この地で何を知り，そして何を見てきたのかを，先の一言で表した。

  「これで満足か」マッパはそう言って再び歩き出す。

  「シッショ？」棒立ちのシッショをクビワが心配する。その言葉でシッショはようやく動き，とぼとぼとマッパの後をついて行った。

  自分たちがこれまで屍の上を駆け回っていたという事実に，シッショの頭は真っ白になった。シッショは本物の雪を知らない。シッショだけじゃない。里の隊員で知っているのは，おそらく博学なケライとショムしかいない。そしてショムは里を出ない。ゆえにこの地の雪が異質なものであるとこれまで知られなかったのだろう。

  シッショは足が震えるのをクビワにさとられないよう，なんとかこらえた。人であったものを放っておくというのでもなく，埋葬するのでもなく，山のように積むという行為に，言い知れぬ狂気を感じた。なぜマッパはすぐに里を出ていき，調査をするのか。それは単に南へ帰還する手段を見つけるためだけではない。一秒でも長くその異常な世界から離れていたかったのだ。シッショだってそうだ。このことを知ってしまった以上，もはや里に帰りたくはない。

  クビワは何を気にすることもなく，空腹を訴える。だがマッパとシッショは無言のまま，足を進めた。

  <br>

  ふいに，ガチャン，という金属音が響き，そこから光がもれてきた。これまで暗闇に慣らされていたこともあって，目に突き刺すような痛みがはしる。

  マッパを筆頭に三人は光の中へ入る。壁いっぱいに張られた数々の設計図と，生物のスケッチ。乱雑に積まれた資料。それらを天から差し込む光が照らし出していた。

  埃をはらって，マッパが本をめくりはじめる。「紫針竜を倒す手がかりがあるはずだ。探せ」

  マッパの言葉に，クビワの腹の虫が景気良く答える。これだけ緊迫した状況なのに，シッショは思わず笑ってしまった。「黒い扉の奥が倉庫になっている。食える物があれば好きに食え」

  それを聞いたクビワは口の両端を上げ，シッショの背中を押して急かす。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
