#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 140

  シッショの覚悟はすぐに試されることとなった。甲高い金属音とともに，クビワの籠手が折れた。そのわずかな隙をザエルが逃すはずもない。振り上げるその腕は，最短距離でクビワの身体に迫る。と，ザエルがバランスを崩した。ザエルの唯一の弱点，その後ろ足に槍が突き立てられたのだ。シッショが噴射機構を起動する。

  だがその場所を選んだのは誤りだ。いや，正解などなかった。足先まで覆う分厚い毛が，刃が閉じるのを拒む。先端が岩盤獣との戦いで歪み，不完全な噴射ではその力を十分に発揮できなかったのだ。これではどこを攻撃しようが意味がなかった。

  ザエルは戦いに水を差したシッショを次の標的に選んだ。部屋全体が揺れるほどの雄叫びをあげる。それでもシッショは怯まない。

  「自分を信じろ!」

  そう叫び返し，シッショは己を鼓舞させた。

  咆哮で怯えさせられると思ったら大間違いだ!

  これまで戦ってきた全ての経験を全身に張りめぐらせながら，勘を研ぎ澄ませる。

  「シッショ!」クビワが叫ぶ。

  ズン!

  ザエルの拳が空を捉える。シッショは丸腰で攻撃をかわしたのだ。その爪は硬い床をバターのように削りとる。だがシッショは冷静だった。ザエルの骨格なら次はこっちだ。二撃目もかわす。

  なるほど。シッショはクビワが楽しんでいるように見えた理由がわかった。

  森での戦い，そしてその落とし子であるキバとツメと暮らすなかで，シッショはその動きが細胞の一つひとつにまでしみついていた。このザエルの爪が大きすぎるのもシッショに味方した。動きは速いが融通は利かない。初動を見切れば軌道は読める。これだけ速く，強力な攻撃でも，かわすことができるのだ。自身の限界が，その高みが引き上げられていくような快感があった。シッショはアルジを思い出した。なぜアルジは戦いのなかで喜んでいるように見えたのか。感じていたのはこれだったのだ。日々のいさかいで悩み，些細なことで己の卑小さを嘲り，誰かをそしり，後悔し，それでもクビワさえいれば，そんな虚偽でごまかしつづけてきただけのちっぽけな自分が，全てのしがらみや過去，ついには自分自身さえも忘れ，目の前のことに没頭する，その官能的な贅沢に酔いしれた。

  だがそれでも足りない。圧倒的に。シッショの肉体が，思考に追いつかない。爪がシッショの身体をかすめ，血が流れる。

  クビワも気をひこうとザエルに攻撃をする。だが利き手の籠手が砕けていては，ザエルの毛を貫くほどの力が生まれない。いや，もともとクビワの攻撃はあまり通っていない。ザエルの攻撃を誘導し，自滅を促していたようなものだったのだから。

  「ここであきらめてどうするんだ!」なおも吠えながらシッショは避けた。避けつづけた。来い。

  メリッ，という感触とともに，クビワの腕に手応えがあった。執拗な攻撃がようやく実ったのだ。ザエルの身体が揺らぐ。だがそれは仇となった。爪の軌道がわずかにずれ，シッショの片目が切り裂かれる。赤い血が線を引く。

  シッショの負傷にクビワの顔が歪む。クビワ，勘違いしないで。クビワは正しい戦いをしているよ。シッショは心の中で思った。だが距離感を失ったシッショに，もはやザエルの攻撃を避ける力はない。クビワほどの直感がなければ，勘で避けることは不可能だ。

  シッショは胸のダイヤルに手をかけた。自爆。この距離なら，クビワは少しの火傷で済むだろう。

  クビワ。元気でね。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
