#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 141

  「俺の言ったことを忘れたのか」

  聞きおぼえのある声が頭の上から響いてきた。その頭はシッショのものでもクビワのものでもない。

  ザエルの頭の上にマッパの姿があった。大槌に手をかけ，片膝を曲げてシッショをのぞきこんでいる。不快感にザエルが身体を振るわせ，マッパはシッショの前に降り立った。そしてザエルが攻撃する前に，大槌を振りかぶる。ザエルが飛びのいた。直撃した地面に大きな穴が穿たれる。

  「シッショ。崩れるぞ」

  そう言ってマッパは無闇に武器を振るう。それほど速くない。大振りの打撃を，ザエルが華麗にかわしていくが，視界からザエルを離さず，そして攻撃の手を決して緩めない。

  <br>

  何が起きているんだ。シッショは自分の目が信じられなかった。それはクビワだってそうだろう。大型のモンスターが繰り出す全ての攻撃は致命傷になりうる。それゆえ一撃離脱が基本なのだ。だがマッパはどうだ。こちらから一方的に攻撃するばかり。まるで相手のほうが逃げているみたいではないか。

  「クビワ!天井!」シッショが叫ぶ。マッパの言うとおり，部屋の中は戦いで限界を迎えつつあった。天井がじりじりと砕け，その破片が地面に落下する。重量はそれなりにある。直撃すればただではすまない。クビワはシッショを抱え，器用によけながら，ザエルとマッパの行く末を見守る。

  なんと緩慢で無計画な戦い方か。それほど未熟な戦い方に思えた。だがそんな印象は徐々に消えていく。攻撃の振りが速まる。慣性が大槌に伝わって，その速度を増してゆくようだ。シッショにはそう見えた。はじめは容易にかわし，反撃をうかがうザエルだったが，その余裕がなくなる。

  違う。マッパの身体からシッショは動きを読み取った。大槌に仕掛けなどない。マッパはザエル種と戦うのが初めてだから，どんな動きをしてくるのかわからない。それを把握する必要があったのだ。次の動きが読めないうちは，マッパの身体に無駄が生じ，力が大槌に伝わらない。だがやがて，次に取るであろう選択肢が狭まっていくと，迷いのない攻撃に変えていくことができる。それがあたかも，振れば振るほど速度を増す武器に見えただけなのである。

  いつまでも自分が攻撃できない，しびれを切らしたザエルが振ったその爪を，マッパの大槌がはじきとばした。ザエルは怒りの咆哮をあげ，マッパに襲いかかった。退却などしない。そして攻撃性の塊であったことが，その寿命を縮めた。

  突進するたび，その顔が大槌の直撃によって歪んでゆく。半身が，その全身が，みるみる赤く染まる。それでもザエルは退かない。腕の爪がボロボロに抉られ，吹き飛ばされた顎を醜く垂れ下げながら，嘔吐するようなガラガラ声でなおも挑む。

  もはや顔を失い，視覚も，嗅覚も失ったザエルは，やがて吠えることもなくなり，マッパの殴られるままとなっていった。血のまざった肉を棒で叩くような，鈍い音と，ニチャニチャと何かがへばりつくような音のまざった不快な響き。それは唐突におさまり，大きく息をつく声が聞こえた。その全身は返り血にまみれ，光でつやめいていた。

  マッパは大槌をその場に残すと，シッショを抱えたクビワを認め，髪から血を垂らしながらやってきた。そしてクビワには目もくれず，シッショの胸ぐらをつかむ。

  「俺が言ったことを忘れたのか」「シッショいじめるな。ころすぞ」「こいつは自分で死のうとしたんだ!」

  え？とクビワが拳の力を緩め，シッショを見る。シッショはクビワから目を反らし，「ごめん」と呟いた。

  マッパはシッショの目が潰れていることに気づくと，その手を離す。「感染症になるかもしれん。気をつけろ」とだけ言った。

  「クビワ，マッパさんの身体を拭くの手伝ってくれる？」「いい，余計なお世話だ」「助けてもらったんだ，お礼くらいさせてよ」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
