#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 142

  観測省の研究室。そこは入った頃の面影はなく，空へぽっかりと大穴を開けている。壁もいたるところが崩れ，時折吹く風が，わずかに残った紙の破片を揺らしていた。

  空は紫に染まり，外が夜であることを告げている。その床に布をしき，シッショは膝で眠るクビワの髪をなでながら，焚き火をはさんで虚空をながめたままのマッパに目を向けていた。

  「お前に自爆を教えたのは誰だ」その問いにシッショは記憶をたどった。「降伏した捕虜から」「北の大陸か」「わからない。そうかもしれない」

  自分の持つ武器で敵を倒せないとき，それでも倒さなくてはいけない敵に対し，自爆するのだ，とシッショはその捕虜から聞いた。シッショはこの地に来て，裂掌獣との戦いのなかで，その戦術がよぎった。いずれ自分でもかなわない敵が現れるだろう。そんなときは，自分を犠牲にしてでもクビワを守るつもりだった。それがクビワを悲しませることになろうが，失うことだけは避けたかった。

  「お前が自爆して，あいつを倒せたと思うか」「わからない」「どうして逃げなかった」「…クビワが逃げなかったから」「違うな。お前はあいつと戦って，自分の勇敢さを確かめたかったんだ」「違う。クビワを守ろうとした」

  わからない。シッショはマッパの問いがわからない。何を知りたいのかも。

  「マッパさんてそんなにネチネチした性格だったっけ」「そうだ。まともな性格ならこんな格好はしていない」「言えてる」ふっ，と二人は笑った。

  「それ，賤民の証でしょ」「…知ってたのか」「オヤブンに偉そうにしてるから知らないフリしてたけどさ」「なんだ，互いに隠しごとだらけじゃないか」「里なんてワケアリな人たちしかいないよ」「それもそうだ」また二人は笑った。

  南の世界では大罪を犯した者を賤民と呼ばれる身分に落とす。それは畜生にも劣る。賤民の証として衣服を身につけることを許さず，さらには時限式の毒を仕込んだピアスを装着させ，永久に辱めるのだ。この毒はピアスを外しても身体から抜くことはできず，定期的に解毒剤を受け取らなければ死ぬ。その投与は下層民に一任されることが多い。普段の生活で差別されることの多い下層民は，不満のはけ口として賤民を玩具にする。薬のためにはそれらの要求に従わざるを得ないのだが，それゆえ賤民のほとんどはその恥辱に耐えきれなくなり，自ら命を絶つ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
