#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 143

  夜になってもアルジとケライは書庫から戻らなかった。心配したシンキが二人の様子を見に行く。その間，ボッチは医務室でショム，オヤブンとともに食事をとりながら，手紙では伝えきれなかった，これまでの詳細を説明していた。特に，アルジやマッパでさえも知らない北の大穴について，内部に何があるのかオヤブンは興味津々であった。とはいえ穴に入るには，降りるためのロープも含め，多くの資材が必要である。簡易なテントでは拠点とするには不十分だ。

  そこで，大穴を調査するのであれば，いっそのこと一時的に本部を森のキャンプに移してはどうか，とボッチは提案した。調査隊の規模では，里が本来の機能を取り戻せるだけの人員を割けない。森のキャンプは暖房も含めそれなりの設備を持ち，全員を受け入れられるだけの広さがある。何より，大穴を本格的に調査するのであれば，ボッチとしては医療の要であるショムを自分たちの近くに置きたかったのだ。オヤブンは里から出るのは気後れしたが，善処する，とのことだった。

  <br>

  本部は崩れ，宿舎としては利用できない。ゆえに広場にテントを張り，そこを仮の住まいとしている。居心地が快適というわけではないが，安全が確保された場所というだけで疲れは癒される。そのなかでミミがうとうとしていると，シンキがアルジとケライの二人を連れて入ってきた。

  アルジの額には包帯が巻かれ，何があったのかミミが心配する。シンキはアルジを休ませるようケライに言い，ミミをテントの外に連れ出した。

  「書庫に地下室があったんだって」「地下室？」「うん，それでね」シンキが背後のテントを見やる。「血の嵐の記録が残ってたんだって」

  ミミの顔がこわばる。当然だろう。謎に満ちた北の大陸で何があったのか，その核心に迫るものだからだ。「すぐオヤブンさんに知らせないと」「待って，ミミ」シンキが呼び止める。「ちょっと，それでね」

  シンキが言いづらそうにミミの服をつかむ。「アルジさんがそれを見て，急に暴れ出したみたいで」「え？」「ケライから聞いたんだけどさ，アルジさん，その，血の嵐を知ってるらしいんだ」

  「知ってるって，それ…」シンキの言葉にミミの身体はこおりついた。シンキは自分で説明しながら鼓動が早まるのを感じる。ミミの姿に，書庫でそれを知らされたときの自分を重ねた。「アルジさん，北の大陸にいたってことですか？」「うん…たぶん」シンキは興奮を静めるため一息おく。「それでね，」

  シンキはミミの目を見て言った。「そのこと思い出して，すごくつらかったんだと思う。だから，みんな知りたいと思うし，あたしもそうだけど，でも，そっとしてあげてほしいんだ。たとえば，アルジさんの前では地下の話をしないとか」ミミがうなずく。「こんど，地下の掃除して，あたしたちができる範囲で，調べよ」再びミミがうなずいた。

  ミミの無言の返事にシンキはほっと息をつくと，本部の隣に目を向けた。ひびの入った医療棟が青白く夜の光を反射している。「ボッチが寂しがるからあたしは医務室行くね。ミミはアルジさんをお願い」

  わかりました，というミミの言葉を聞き，シンキはその場をあとにした。

  テントに引き返したミミは，中をのぞく。すると，テント内で食事を終えたケライが，二人分の食器を持って出てくるところだった。ケライは軽く頭を下げて出ていく。それと入れ違いにミミが入る。アルジは魂が抜けたようにぼんやりとしたまま，ミミの存在に気づくと，軽く会釈した。

  ミミは好奇心を抑え，怪我の理由を聞かず，具合はどうか，とだけ尋ねた。するとアルジから意外な答えがかえってきた。

  「私のケガよりも，聞いてほしいことがあるんです」その言葉にミミが身構える。「私の知っていること，思い出したことを皆さんに話さなければいけません」

  ミミはアルジに寄り添い，尋ねる。「話しても大丈夫なんですか？つらければ，無理しなくてもいいんですから」

  アルジは過去の苦痛に蓋をし，そして忘れた。そうしないと壊れてしまうからだ。軟弱な精神である。ただ，何も覚えていないのは幸いでもあった。もしアルジの記憶が封印されているだけである，ということが南で知られていたら。アルジは重要な情報を持っているかもしれない。その場合，ここに来る前に，自白剤などを使って強制的に記憶を呼び起こされ，そして目の前で起きた出来事が頭から離れず，苦悩の果てに死んでいただろう。

  「全部話せるかどうかはわかりません。でも，がんばってみます」アルジの言葉にミミは潤んだ瞳でうなずき，アルジに顔を寄せた。すると間もなく，何かに気づいたのか，アルジの目が急に見開かれてゆく。そして，光の灯らぬ視線でミミの方を向く。

  「話しても大丈夫って，つらければ，って，どういうことなんですか。ミミさんは，どうして私の記憶がつらいものだと知ってるんですか」ミミはハッとして顔を上げる。シンキから聞いただけだ。そう口を開こうとした。「紫針竜が南への道を封鎖していることだって，どうして知っていたんですか」「武器庫に対人用の武器がどうして置かれていたんですか，敵はモンスターじゃないんですか」

  矢継ぎ早に質問を繰り出しながら，ミミから離れていく。アルジのなかで，知識の断片が一つにつながってゆく。その顔に浮かんでいたのは，恐怖だった。

  「違います，私は」「ミミさんは何を知ってるんですか」「アルジさん落ち着いて」「私に優しくしたのもはじめから全部知ってたんですか」「お願いアルジさん，私の話を聞いて」「ミミさんまで私を」「聞いてください，私は」

  アルジはわめき出した。テントの壁に身体を押しつけ，ひっかきながら，そこから出ようとする。その声に異常を感じたか，ケライがテントに駆け込んできた。間を遮っていたミミを突き飛ばして奥で怯えるアルジを強く抱きしめると，ミミにきつい視線を向ける。それは手に力を込めたゆえのものだったかもしれない。だがそれは「せっかく落ちついていたのに，何をしたのか」とミミを非難するものに見えた。ミミは腕に突き飛ばされた感触をおぼえながら，弁解することもできず，ふらふらとテントを出て行った。

  <br>

  うつろな様子でどこへともなく歩いてゆく。その様子をキセイはながめていた。被害をまぬがれた獣舎で，アルジの異様な声に警戒するペットをなだめながら。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
