#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 143

  夜になってもアルジとケライは書庫から戻らなかった。心配したシンキが二人の様子を見に行く。その間，ボッチは医務室でショム，オヤブンとともに食事をとりながら，手紙では伝えきれなかった，これまでの詳細を説明していた。特に，アルジやマッパでさえも知らない北の大穴について，内部に何があるのかオヤブンは興味津々であった。そのためには十分な資材が必要で，簡易なテントではとても間に合わない。本部の建物に損害が出たのは残念であったが，大穴を調査するのであれば，いっそのこと一時的に本部を森のキャンプに移してはどうか，とボッチは提案した。

  本部は崩れ，宿舎としては利用できない。ゆえに広場にテントを張り，そこを仮の住まいとしている。居心地が快適というわけではないが，安全が確保された場所というだけで疲れは癒される。そのなかでミミがうとうとしていると，シンキがアルジとケライの二人を連れて入ってきた。

  アルジの額には包帯が巻かれ，何があったのかミミが心配する。シンキはアルジを休ませるようケライに言い，ミミをテントの外に連れ出した。

  「書庫に地下室があったんだって」「地下室？」「うん，それでね」シンキが背後のテントを見やる。「血の嵐の記録が残ってたんだって」

  ミミが驚く。当然だろう。謎に満ちた北の大陸で何があったのか，その核心に迫るものだからだ。「すぐオヤブンさんに知らせないと」「待って，ミミ」シンキが呼び止める。「ちょっと，それでね」

  シンキが言いづらそうにミミの服をつかむ。「アルジさんがそれを見て，急に暴れ出したみたいで」「え？」「ケライから聞いたんだけどさ，アルジさん，その，血の嵐を知ってるらしいんだ」

  その言葉にミミの身体は固まった。シンキは自分で説明しながら鼓動が早まるのを感じる。ミミの姿に，先ほどそれを知らされた自分の様子を思い出した。「北の大陸にいたってことですか？」ミミの声が自然と弱まる。「うん…たぶん，それでね」

  シンキは興奮を静めるため一息おく。「そのこと思い出して，すごくつらかったんだと思う。だから，みんな知りたいと思うし，あたしもそうだけど，でも，そっとしてあげてほしいんだ。たとえば，アルジさんの前では地下の話をしないとか」ミミがうなずく。「こんど，地下の掃除して，あたしたちができる範囲で，調べよ」再びミミがうなずいた。

  「ボッチがさびしがるからあたしは医務室行くね。ミミはアルジさんをお願い」

  わかりました，というミミの言葉を聞き，シンキはその場をあとにした。

  テントに引き返したミミは，中をのぞく。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
