#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 144

  里の外に廃材の積まれた場所がある。その影に座り込んで，ミミは頬を冷たい風になでられていた。

  眠気と疲労は興奮と不満に打ち消され，気分はすこぶる悪い。こんな気持ちになってしまうと，それと関連する記憶ばかりがよみがえってきて，余計に嫌悪と苛立ちがつのる。

  ああ，あんなこと思い出したくなかった。それはミミがここに来る前の忌まわしい出来事だ。まだミミが自分には力があると，心のどこかに自分を誇るものがあった頃。世間の事情など知らないミミは，その知識と才能を活かした作品をつくりあげ，国を挙げたコンテストに出品してしまった。だがそのコンテストは，竜人のなかでも類まれなる才を持つ，その者に栄誉を与えるために催されたものだった。ミミの無分別な行動は事態を複雑にした。

  本来そんな目的のもとに企画されたものなら，ミミがどれほど優れたものを作ろうが関係ないことだ。実際優勝したのもその竜人である。ただミミの作品は，審査した竜人達をもうならせた。それは自分たちがいかに古い考えに囚われ，研鑽を怠っているか知らしめるのに十分であった。日々虐げられる獣人達のほうが，もはや知識も技能も卓越したものであることを痛感させたのだ。才ある竜人，といっても井の中の蛙である。その竜人を旗頭にし，力を持とうとしていた一派は急速に衰退していった。

  過ちではなかった，はずだ。けれどもミミはそれ以来自分自身が生きたまま解剖されていくように感じた。その才を買おうとする者，嫉妬する者，自尊心を傷つけられた者，それらが入れ替わり立ちかわりミミに襲いかかり，その身体と心をばらばらにした。ミミはもうこれまでのミミでいられることはできなかった。

  <br>

  茶葉を炒るような香ばしい匂いがただよってくる。その香りにミミは伏せていた顔をあげた。歪な円板がくすぶり，一本の白い煙がゆらめいている。それはダモスのフンで作った燃料である。分解された繊維は火を保つのにうってつけなのだ。

  そこでミミはようやくキセイが隣に座っていることに気づいた。キセイは思い出したように燃料をくべながら，無言で煙をながめている。里の外でミミが凍えないよう後をつけてきたようだ。だがミミはどう切り出せばいいのかわからなかった。

  「あの，ありがとうございます」ミミはとりあえず礼を言った。キセイは聞こえていないようにその姿勢を崩さない。反応がないのでミミも言葉を続けづらく，互いに沈黙が続いた。

  <br>

  「それでいいのか」

  <br>

  ミミはハッとする。キセイは新たな円板を投げ込んで言った。「今度はどこへ逃げるんだ」

  里で聞いたことのないほど，低い，流暢な言葉遣いである。ミミは歯ぎしりをするように口を動かし，しかし声にならない。

  「逃げて…いません」ミミは震える声で言った。ようやく，自分の居場所を得られたはずなのに。そこへずかずかと入りこんで，身勝手に振る舞い，勝手に傷つき，暴れる者。

  <br>

  やがてミミの心にふつふつと熱いものがこみあげてきた。どうしてこの私があんな生意気な，子供のようなやつに気を配り，こんなところで反省するようなことをしなければならないのだ？

  ミミは地面を両手で叩き，立ち上がった。そしてその音にびっくりするキセイを無視し，大地を穿つような足音をたてて里へ向かっていった。

  <br>

  「ミミさん」

  里の入口には，落ち着きを取り戻した様子のアルジとその身体を支えるケライ，そしてボッチとシンキが立っていた。みなミミを見て安心したように見えたが，直後，その怒りに満ちた顔にうろたえる。

  ミミはアルジをきっと睨み，腹からわきあがる声で言った。「私，謝りませんから」その言葉にアルジはきょとんとする。「あなたがどう思うか知りませんが，私，今のまま変わるつもりありませんから」

  ボッチがアルジを見て何か言おうとする，その口をシンキが塞ぐ。

  アルジはケライの肩に回していた腕を外し，「すみません」とミミの目を見たまま詫びた。それでミミの気がおさまるはずはない。だがアルジはミミが自分に感情をあらわにするのが嬉しかった。

  「私，ミミさんのこともっと知りたいです。もっといろいろ，ミミさんの知っていること，教えてくれませんか」

  「？」その言葉に，ミミの肩から力が抜ける。それを聞いたシンキは笑いだし，ミミに歩み寄ってマフラーを巻いてやった。

  「これは」「アルジさんに教えてもらったんだよ。ほら，昔，ミミも作ってたんでしょ，一緒に」

  シンキの腕を通した残り香が毛糸から漂ってくる。ミミは，かつて夜の書庫で，ボッチやショムらとともにアルジから編み物を教わっていたことを思い出した。

  里は崩れた。多くの者が傷ついた。それでも前を向いて皆歩いている。ミミの頬を涙が伝った。

  「アルジさん。教えます。私の知っていること」ミミは軽く顔を振って，やや鼻声でアルジに言った。「はい」アルジもうなずいて答える。

  「でも私の知っていることを全部聞こうと思ったら，何十年もかかりますよ。覚悟してください。途中で逃げたりしたら許しませんから」「もちろん，大歓迎です」アルジは即答し，冗談を真に受けた様子にミミも笑ってしまった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
