#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 144

  里の外に廃材の積まれた場所がある。その影に座り込んで，ミミは頬を冷たい風になでられていた。

  眠気と疲労は興奮と不満に打ち消され，気分はすこぶる悪い。こんな気持ちになってしまうと，それと関連する記憶ばかりがよみがえってきて，余計に嫌悪と苛立ちがつのる。

  ああ，あんなこと思い出したくなかった。それはミミがここに来る前の忌まわしい出来事だ。まだミミが自分には力があると，心のどこかに自分を誇るものがあった頃…。

  ミミは首を振って忘れようとした。だが頭は勝手に，もつれた糸を引きあげるようにするすると昔の思い出をよみがえらせる。

  世間の事情など知らないミミは，気後れしがちな自分を変えようとした。そしてその知識と才能を活かした作品をつくりあげ，国を挙げたあるコンテストに出品してしまったのだ。いかなる結果になっても良いと，いや，少しはいい賞をもらえれば，そんなほのかな期待もあった。

  だがミミの無分別な行動は，事態を複雑にした。そのコンテストは，竜人のなかでも類まれなる才をもつ，ある者に与えるために催されたものだった。それは竜人達のなかでこれから進められるであろう計画のきっかけになるものだった。その竜人は確かに優れた才を持っていた。旗頭にするには十分なほどの魅力もあった。

  ただミミは自身の能力を侮っていた。これまでアルジを幾度も助けた数々の道具，モンスターの特性を組み込む発想の豊かさからもわかるだろう。ミミが出品した作品，いや，隠さず言おう，その兵器はあまりにも素晴らしすぎた。それを応用すれば，全ての人間を根絶やしにすることも可能なほどだった。

  審査に携わった竜人達は戦慄した。それは自分たちがいかに古い考えに囚われ，研鑽を怠っているか知らしめるのに十分であった。さらに，日々虐げられる獣人達のほうが，もはや知識も技能も卓越したものであることを痛感させたのだ。しょせん結果の決まったコンテストである。優勝したのはその竜人であり，ミミは何の褒賞も与えられなかった。しかし空気は一変した。才ある竜人，といっても井の中の蛙である。その竜人を旗頭に，力を持とうとしていた一派は急速に衰退していった。

  過ちではなかった，はずだ。実際にミミは竜人のもとで新たな生活ができるようになった。これまでには考えられなかったほどの贅沢な世界で。けれどもミミはそれ以来自分自身が生きたまま解剖されていくように感じた。その才を買おうとする者，嫉妬する者，自尊心を傷つけられた者，それらが入れ替わり立ちかわりミミに襲いかかり，その身体と心をばらばらにした。どうして自分は誰も殺めたわけでもないのに，これほど責められなければならないのか。ミミはもうこれまでのミミでいられることはできなかった。

  <br>

  茶葉を炒るような香ばしい匂いがただよってくる。その香りにミミは伏せていた顔をあげた。歪な円板がくすぶり，一本の白い煙がゆらめいている。それはダモスのフンで作った燃料である。分解された繊維は火を保つのにうってつけなのだ。

  そこでミミはようやくキセイが隣に座っていることに気づいた。キセイは思い出したように燃料をくべながら，無言で煙をながめている。里の外でミミが凍えないよう後をつけてきたようだ。だがミミはどう切り出せばいいのかわからなかった。

  「あの，ありがとうございます」ミミはとりあえず礼を言った。キセイは聞こえていないようにその姿勢を崩さない。反応がないのでミミも言葉を続けづらく，互いに沈黙が続いた。

  <br>

  「それでいいのか」

  <br>

  ミミはハッとする。キセイは新たな円板を投げ込んで言った。「今度はどこへ逃げるんだ」

  里で聞いたことのないほど，低い，流暢な言葉遣いである。ミミは歯ぎしりをするように口を動かし，しかし声にならない。

  「逃げて…いません」ミミは震える声で言った。ようやく，自分の居場所を得られたはずなのに。そこへずかずかと入りこんで，身勝手に振る舞い，勝手に傷つき，暴れる者。

  <br>

  やがてミミの心にふつふつと熱いものがこみあげてきた。どうしてこの私があんな生意気な，子供のようなやつに気を配り，こんなところで反省するようなことをしなければならないのだ？せっかく作った義肢だって，すぐにボロボロにして帰ってくる，あんな道具の使い方も知らない素人に。

  バカで無知で無能で命知らずで礼儀知らずで貧弱でノロマでブサイクですぐにケガしてすぐに死にかけてすぐいなくなって人に迷惑かけて心配させるのだけは天才の，そして自分を悲しませてばかりのロクデナシだ。

  ミミは地面を両手で叩き，立ち上がった。そしてその音にびっくりするキセイを無視し，大地を穿つような足音をたてて里へ向かっていった。

  <br>

  「ミミさん」

  里の入口には，落ち着きを取り戻した様子のアルジと，その身体を支えるケライ，そしてボッチとシンキが立っていた。みなミミを見て安心したように見えたが，直後，ピンと立ったその耳と，怒りに満ちた顔にうろたえる。

  ミミはアルジをきっと睨み，腹からわきあがる声で言った。「私，謝りませんから」その言葉にアルジはきょとんとする。「あなたがどう思うか知りませんが，私，今のまま変わるつもりもありませんから」

  ボッチがアルジを見て何か言おうとする，その口をシンキが塞ぐ。

  アルジはケライの肩に回していた腕を外し，「すみません」とミミの目を見たまま詫びた。それでミミの気がおさまるはずはない。だがアルジはミミが自分に感情をあらわにするのが嬉しかった。

  「私，ミミさんのこともっと知りたいです。もっといろいろ，ミミさんの知っていること，教えてくれませんか」

  「？」その言葉に，ミミの肩から力が抜ける。それを聞いたシンキは笑いだし，ミミに歩み寄ってマフラーを巻いてやった。

  「これは」見覚えのない模様のマフラーに，ミミは不思議そうな目でシンキを見る。「アルジさんに教えてもらったんだよ。ほら，昔，ミミも作ってたんでしょ，一緒に」

  ミミは手の平で感触を確かめた。シンキの腕を通した残り香が毛糸から漂ってくる。そこから，かつて夜の書庫で，ボッチやショムらとともにアルジから編み物を教わっていたことが思い出された。

  里は崩れた。多くの者が傷ついた。それでもみな前を向いて歩いている。そしてなぜか，その先頭にはいつもアルジがいる。どれほどひどいめにあっても，なぜかまた列の先頭に戻っている。ミミはふっとそんなアルジの背中が浮かび，頬を涙がつたった。

  <br>

  ミミは軽く顔を振って，やや鼻声でアルジに言った。「アルジさん。教えます。私の知っていること」

  「はい」アルジもうなずいて答える。

  「でも私の知っていることを全部聞こうと思ったら，何十年もかかりますよ。覚悟してください。途中で逃げたりしたら許しませんよ」ミミは意地悪そうな笑顔で言った。「もちろん，よろしくお願いします」アルジは即答し，冗談を真に受けた様子にミミもふきだしてしまった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
