#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 145

  「ミミさん」

  里の入口には，落ち着きを取り戻した様子のアルジと，その身体を支えるケライ，そしてボッチとシンキが立っていた。みなミミを見て安心したように見えたが，直後，ピンと立ったその耳と，怒りに満ちた顔にうろたえる。

  ミミはアルジをきっと睨み，腹からわきあがる声で言った。

  「私，謝りませんから」その言葉にアルジはきょとんとする。「あなたがどう思うか知りませんが，私，今のまま変わるつもりもありませんから」

  ボッチがアルジを見て何か言おうとする，その口をシンキが手で塞ぐ。ボッチが入ると余計なことになるからだ。なりゆきを見守らなければならない。

  アルジはケライの肩に回していた腕を外し，「すみません」とミミの目を見たまま詫びた。それでミミの気がおさまるはずはない。

  アルジはこれまでミミが自分にそんな表情を向けるのを見たことがなかった。そして，それが嬉しかった。おかしなことだ。自分に怒りを向けられることが嬉しいとは。ただそこには理由がある。ミミはいつも自分に優しかった。アルジはそんなミミに包まれていると，なんだか自分が弱いもののように思えてしまう。

  確かに自分は弱い。でもそのままではだめなのだ。どんな形であれ自分は進んでいきたい。できないことができるようになるとは限らない。でも，できることを，より上手く，少しでもいい。少しでも変えていければ。だから，怒りであろうと，ミミの本心を聞けて嬉しかった。相手が何を思っているのか，少しでもわかれば，それを手がかりに，より相手を知ることができるからだ。

  アルジは息まくミミの目をまっすぐ見つめて言った。「私，ミミさんのこともっと知りたいです」

  「？」予想外のその言葉に，ミミの肩から力が抜け，その大きな耳がはねるように動く。「こんなに長くいるのに，私，ミミさんのことを全然知りません。もっと知りたいです。学びたいです。もっといろいろ，ミミさんのこと，それに，ミミさんの知っていること，教えてくれませんか」

  まさに目が点になったかのようにミミは呆然としている。気持ちが静まっていくのを表すかのように，つりあがった耳もしおしおと垂れ下がってゆく。それを見たシンキは思わず笑いだしてしまった。それからミミに歩み寄って，隠していたマフラーを巻いてやった。帰ってきたら渡すつもりだったのだ。

  「これは」見覚えのない模様のマフラーに，ミミは不思議そうな目でシンキを見る。「アルジさんに前に教えてもらったんだよ。ほら，昔，ミミも作ってたんでしょ，一緒に」

  ミミは手の平で感触を確かめた。シンキの腕を通した残り香が毛糸から漂ってくる。そこから，かつて夜の書庫で，ボッチやショムらとともにアルジから編み物を教わっていたことが思い出された。

  里は崩れた。多くの者が傷ついた。それでもみな前を向いて歩いている。そしてなぜか，その先頭にはいつもアルジがいる。どれほどひどいめにあっても，なぜかまた列の先頭に戻っている。ミミはふっとそんなアルジの背中が浮かび，頬を涙がつたった。

  <br>

  ミミは軽く顔を振って，やや鼻声でアルジに言った。「アルジさん。教えます。私の知っていること」

  「はい」アルジもうなずいて答える。

  「でも私の知っていることを全部聞こうと思ったら，何十年もかかりますよ。覚悟してください。途中で逃げたりしたら許しませんよ」ミミは意地悪そうな笑顔で言った。「もちろん，よろしくお願いします」アルジは即答し，冗談を真に受けた様子にミミはふきだしてしまった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
