#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 145

  朝，クビワが目覚めるのを待って，マッパ達は里を目指した。真っ暗な通路を抜け，ガスに満ちた谷をわたる。幸い湖は張っておらず，容易に針山へとたどりつくことができた。だが奇妙なことに，針山に獣の姿が見えない。ふだんは頭上をあのイガ栗のような獣が飛びかっているのだが。

  その原因は山の頂上に達したことでわかった。そこから見通せる湿原はその面影もなく，茶色い土があちこちから盛り上がり，平坦な大地をデコボコに変えてしまっている。何が起きたのか。マッパたちは白きザエルとの死闘に集中するあまり，この地を襲った地震のことを知らない。里に大きな損害を与えた地震は，どれほど広い範囲に及んだのか，想像もつかない。

  「!」

  マッパはその土の合間に，コールタールのような黒く粘ついた物が漂うのを見た。地面が液状化したとでもいうのか。二人を急かし，山を下る。よかった。麓のキャンプで，ダモスは怯えながらも無事のようだった。今ここでこいつを操れるのはシッショだけだが，キセイほど動物の扱いは上手くない。たった一人，いや一頭で恐怖の夜を過ごしたダモスは神経が高ぶり，今にも暴れ出しそうだった。これほど取り乱す様子を見たことはシッショにもない。一体どうしてしまったのか。

  「シッショ」クビワが呼んだ。「なに？」必死にダモスをなだめながら，シッショは答える。

  <br>

  「兄チャのニオイがする」

  <br>

  「伏せろ!」マッパの叫び声とともに，地面が大きく揺れた。あわててシッショは身をかがめる。「クビワ!しゃがんで!」だがクビワは言うことをきかない。足元もおぼつかないのに，視線は湿原をとらえつづける。やがて揺れはおさまったが，もはやダモスは完全にパニックになっていた。もはやシッショの力でなだめることはできない。

  このままではキャンプも湿原のように崩れてしまう。かといってダモスを置いていくことはできない。里の運搬の要だからだ。マッパはやや熱を帯びた頭で考えた。「クビワ。頼みがある」

  「なんだ」クビワはすんすんと鼻を鳴らしながら言った。「ここから先，湿原のキャンプについたらこの信号弾を放て。キセイを呼ぶ」「おう」

  「ちょっと待って。こんなところにキセイを？」シッショが抗う。「そうだ。今のこいつを落ち着かせられるのはあいつだけだ」「無茶だ」「ならここに獣車を置いていくしかないな」「そうかもしれないけど，でもこんな危険なところに呼ぶなんてどうかしてる」「お前は獣車の数が半減してまともに調査ができると思ってるのか？」「この状況で里にだって被害が出ているかもしれない」「そんなのやらなければわからん。クビワ。頼む。俺だけじゃない。ここにいるシッショの命もかかっている」

  シッショを持ち出すなんて卑怯者。だが議論をしている時間も惜しかった。クビワは「わかった」とすぐにうなずき，シッショが止める間もなく信号弾を受けとってキャンプを飛び出してしまった。そのまま荒れた地面をものともせず風のように駆けぬけてゆく。

  <br>

  嵐のような時間が過ぎ，シッショはため息をついた。ダモスを撫でつづけてはいるが，この調子ではまだまだ時間はかかるだろう。思いどおりに操るなんてとてもできない。そんな様子のシッショをよそに，マッパは時間ができたとばかりに研究所から持ち出した資料を広げる。

  「マッパさん，それ」シッショはてっきり研究所の資料はザエルとの戦いでほぼ失われたと思っていたが，マッパはしたたかである。「倉庫にあったものを持ってきた」「倉庫？」「お前らがあの白いのと遭遇したところだ」

  マッパはザエルが飛び出してきたところで相手の思惑に気づいた。ザエルの背後に自分の求めるものがあると。たいてい重要な情報ほど大事に隠しておくものだ。適当な本棚につっこんでおくことなど，小心者にはできない。そして仮にそんな胆力のあるような相手なら，そもそもこんなところにこそこそ隠れることもない。何より小心者であろうが胆力のある者であろうが，白いザエルは圧倒的に強い。こいつに任せていれば，全ての侵入者を葬ってくれるはずだったのだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
