#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 147

  クビワの放った信号弾は里に伝わった。キセイがコッコに飛び乗り，湿原に向かおうとする。

  「俺も行こう」ボッチがジブーを呼ぼうとするのをキセイは手で制し，湯治場を指さした。再び使えるようにするには，瓦礫を撤去しなければならない。「お前一人じゃ危険だ。何があるかわからないだろう」キセイは首を振り，笛を吹くと，ゴリとワンワを連れて早々に里を出発してしまった。仕方なくボッチは仕事にとりかかる。せめてゴリは置いていってもらいたかった。アルジがケライに話を聞いてもらう間，力仕事ができるのはボッチだけになってしまったのだ。ミミとシンキは書庫の地下を調べる作業に入っている。ボッチは肩を落とし，先の地震で散った瓦礫の山を拾うところから始めた。

  <br>

  「ミミはもう揺れは平気なの？結構大きかったけど」「少し怖いですけど，それよりせっかく掃除したのがまたやり直しなのがもう腹立ってしょうがないです」書庫の地下で，シンキの問いに苦笑いしながらミミは答えた。昼食のさなか，大きな揺れが里を襲い，テントは歪むわ，せっかく片付けた本棚はまた散乱するわで大変だったのだ。もし書庫の地下で揺れに遭遇していたら閉じこめられていたかもしれないが，ここだけは何事もないかのように平穏を保っている。あえていえば，アルジが暴れた床と机が拭かれ，埃のない表面が明かりを反射している。

  本棚はそれぞれの棚に金属板が通され，本が飛び出さないようになっている。まるで取り出されるのを拒んでいるかのようだ。それでいて板を外して目につく本を開いてみても，上の階にあったようなものと大して違いがない。ただミミは目ざとく，ここにある本には竜人の紋章がないことに気づいた。調査隊が持ち込んだものではないのだ。では誰が。

  「なつかしいね」ふいにシンキがつぶやいた。振り向くミミにページを広げて見せる。絵本だ。こんなところにそんな子供向けのものが。いや，そんなことよりもその中身。ミミも思い出すやいなや，大きな声をあげてそのページを指さし，大喜びした。

  南で育った者なら誰もが知っている有名な絵本だ。丸い繭のような巣を作る，不思議な蝶の話。その蝶は巣の中に宝石を集め，独り占めしようとした。だが，そのあまりに大きな笑い声は巣の中を跳ね回り，全ての宝石を粉々にして，台無しにしてしまうのだ。そして悲しんだ蝶はどこかへ飛び去って行く。傲慢さを戒める物語であり，クライマックスである蝶の大声にあわせて子供達も叫ぶ，というのがお決まりだった。

  それがどうしてこんなところにあるのだろう。シンキは目を落としながら，「ここにいた子供達に読んであげていたのかもしれないね」と少し寂しそうな声で言った。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
