#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 147

  クビワの放った信号弾は里に伝わった。キセイがコッコに飛び乗り，湿原に向かおうとする。

  「俺も行こう」ボッチがジブーを呼ぼうとするのをキセイは手で制し，湯治場を指さした。憩いの場だ。ここを再び使えるようにするには，瓦礫を撤去しなければならない。「お前一人じゃ危険だ。何があるかわからないだろう」キセイは首を振り，笛を吹くと，ゴリとワンワを連れて早々に里を出発してしまった。仕方なくボッチは仕事にとりかかる。せめてゴリは置いていってもらいたかった。アルジがケライに話を聞いてもらう間，力仕事ができるのはボッチだけなのだ。ミミとシンキはすでに書庫の地下を調べる作業に入っている。ボッチは肩を落とし，先の地震で散った瓦礫の山を拾うところから始めた。

  <br>

  「ミミはもう揺れは平気なの？結構大きかったけど」「少し怖いですけど，それよりせっかく掃除したのがまたやり直しなのがもう腹立ってしょうがないです」書庫の地下で，シンキの問いに苦笑いしながらミミは答えた。昼食のさなか，大きな揺れが里を襲った。その被害たるや，テントは歪むわ，せっかく片付けた本棚はまた散乱するわで大変だったのだ。もし書庫の地下で揺れに遭遇していたら閉じこめられていたかもしれないが，杞憂のようだ。あれだけの地震に二度も遭遇しながら，ここだけは何事もないかのように平穏を保っている。あえていえば，アルジが暴れた床と机が拭かれ，埃のない表面が明かりを反射している。

  本棚はそれぞれの棚に金属板が通され，本が飛び出さないようになっている。まるで取り出されるのを拒んでいるかのようだ。それでいて板を外して目につく本を開いてみても，上の階にあったようなものと大して違いがない。ただミミは目ざとく，ここにある本には竜人の紋章がないことに気づいた。調査隊が持ち込んだものではないのだ。では誰が。

  「なつかしいね」ふいにシンキがつぶやいた。振り向くミミにページを広げて見せる。絵本だ。こんなところにそんな子供向けのものが。いや，そんなことよりもその中身。ミミも思い出すやいなや，大きな声をあげてそのページを指さし，大喜びした。

  それは南で育った者なら誰もが知っている，有名な絵本だった。丸い繭のような巣を作る，不思議な蝶の話。

  二匹の大きな蝶，ネフレとブリエは，世界中の宝石を巣の中に集め，それを独り占めしようとした。だが，そのあまりに大きな笑い声は巣の中を跳ね回り，宝石を粉々にして，台無しにしてしまうのだ。そして悲しんだ蝶はどこかへ飛び去って行く。

  傲慢さを戒める物語であり，蝶の笑い声にあわせて子供達も叫ぶのがお決まりだった。その大声であたかも宝石を壊すように思えたのだ。

  それがどうしてこんなところにあるのだろう。シンキは本に目を落としながら，「ここにいた子供達に読んであげていたのかもしれないね」と少し寂しそうな声で言った。

  <br>

  片っ端から本を調べたものの，北の大陸や，血の嵐につながるような情報はない。アルジとケライが発見したこの部屋について，オヤブンは何も知らないと言った。いや，オヤブンはこの地についてほとんど何も知らない。何か隠している可能性もなくはないが，少なくとも本人はそう言っている。素朴に，この大陸を安全に知りたいと思っているだけだ。だから地下の書庫から何か新しいことがわかれば歓迎である。にも関わらず，書庫にあるのは南でも見るような絵本や小説，聖典など，なんでこんなところに大事に置いておくのか意図がわからないものばかりだ。むしろ，そんなものがここに置いてあること，そのこと自体に何かの意味があるのかもしれない。

  あと目につくものといえば，なんらかの民芸品のようなもの。

  「血の嵐で滅んだ民族のものですかね」ミミが聞く。「わかんない」

  当然だ。調査隊は民俗学の組織ではない。それに，仮に紫針竜を退け，南へ帰り，そこから新たに連れてきた学者が一様に「知らない」と答えたところで，この工芸品の数々が北の大陸に暮らしていた民族のものであるとは限らない。学者は地上の全てを知っているわけではないからだ。学者がまだ知らない民族の作品をここに持ってきただけかもしれないし，もしくは創造力豊かな誰かがここで作っただけ，という可能性だってある。

  あとはアルジに任せよう。そう思って引き上げようとしたときだった。シンキが一冊の本に何かが書き込まれているのに気づき，ミミを呼んだ。ボロボロの聖典，その余白にびっしりと字が綴られている。

  「汚すぎて読めないよ」シンキはあきれたように言う。ただ，持ち主の想像はつく。何かあるたびに，または気づいたことを，肌身離さず持ち歩いた聖典に書き込んでいったのだろう。この本は，その人物の人生を凝縮したようなものだ。するとそこから，ミミは一つの考えに至った。

  「南からここに来た人たちの，思い出みたいなものなんでしょうか」「え？何が？」「この部屋に置かれている物の意味です。故郷から長く離れるから，ここに来るときに大切な思い出を一緒に持ってきて，さびしくなったときとかに，読んでなぐさめられたのかな，って」

  シンキが大きな声を出す。「あー!そっか。そうかも。だからこんなに大事に保管してあるんだね」「いえ，適当に言っただけですから。違うかもしれませんよ」納得するシンキに，ミミは慌てて両手を振る。「でもそれなら，あたしたちも汚さないようにしないとね，ここ」シンキは部屋を見回して言う。ミミもうなずく。

  それから二人は部屋のほこりを払い，地下をあとにした。

  <br>
  <br>
  
  [[https://github.com/jamcha-aa/OblivionReports/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>

  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
