#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 150

  価値は俺が決める。そんな信念の塊が仲間とともに雪山を登る。マッパたちである。湿原のキャンプにたどりついた一行は，早々にそこを引き払い，里に迫る危機を伝えるべく進んでいたのだ。すると，坂を下ってとぼとぼと歩いてくる義足の人間に遭遇した。

  「アルジ」マッパの威勢の良い声が聞こえる。上の空だったアルジは我を取り戻し，思わず隠れようとしてしまう。あんな啖呵をきって里を飛び出しておきながら，どうマッパたちに顔向けすればいいのか。とりあえず顔を拭い，平静を装う。

  「アルジ!」クビワが走って抱きついてきた。身体は熱を帯び，頬ずりするその目は半開きである。とても眠そうだ。アルジは自分の立場も忘れ，「おかえり。早く里に戻って寝たほうがいいよ」と優しく言った。

  「こんな時間にどうしたの」シッショがクビワの後ろから聞いてくる。「いえ，その」言い訳を思いつく前にシッショはニヤっとした顔で言った。「また逃げたの？」その言葉にアルジは目をそらす。「にげた？オヤブンにしかられたのか？」「いえ，そういうわけじゃないですけど…それよりもシッショさん，その目」「ああ，名誉の負傷みたいなもんだよ」「すぐに手当てを」

  三人の様子を見ていたマッパは，隣でダモスに乗るキセイに何かを言い，コッコらと共に先に里へ向かわせた。元よりそのつもりだったようだ。ウジウジするアルジを軽く見やり，キセイはそのまま行ってしまう。

  「お前がどんな状態か知らんが，そんなことに構っていられる時間はない。緊急事態だ」そう話しながらマッパはクビワを抱きかかえるアルジのもとへやってきた。

  「緊急事態？」ずり落ちるクビワを持ち直し，アルジはマッパを見る。「皆さんが手ぶらなのと関係してるんですか」「見ればわかるだろ。なんとか獣車の動力は守れたが，荷車どころか拠点も木っ端微塵だ」動力とはダモスをさす比喩である。マッパの言葉にアルジの眉が動く。「拠点まで。何があったんですか。敵襲ですか」

  アルジの瞳が輝きを取り戻してゆく。「そうだ。それもとびきりでかい。放っておけば里も食われるだろう」「そんな大物なんですか。シッショさんもそいつにやられたんですか」「いや，僕のケガは別の敵にやられたものだよ」

  「こんなところで話してても時間の無駄だ。今すぐ里に帰るぞ」マッパが話を切り上げようとする。「いえ，私は…」「クビワを里で寝かせてやらないのか」「え」

  見ると，クビワはアルジに抱かれたまま寝息をたてている。よほど疲れたのだろう。片腕の使えないシッショには預けられないし，マッパはアルジを里に返すために受け取りを拒否するに違いない。しばし目を泳がせていたが，アルジは観念して里へ帰ることにした。

  マッパはアルジが里でまたトラブルを起こしたのだろうとうんざりしていたが，それで放っておくつもりはなかった。アルジがどんな面倒な人間かは知らないが，『あれ』に対処するには不可欠なのだ。

  <br>

  アルジが出ていった後，疲れていたボッチはそのままテントで眠り，邪魔をしないようシンキも自分のテントへ戻っていった。ミミも待ち疲れて眠る頃，獣の足音に起こされる。それは意図的なものか定かではないが，キセイとダモスの帰還を告げるものだった。間もなくマッパらとともにアルジも里に帰ってくる。アルジはテントから出てくるボッチたちに身体を向けると，大きく頭を下げた。

  「すみませんでした」

  寝ぼけまなこのボッチは大きくため息をつく。ミミとシンキはアルジが正気に戻ったのに安心すると，クビワを寝かせるよう促した。

  「こいつの頭の悪さはなんとかならないのか」ボッチがアルジに聞こえないようシンキに愚痴り，すぐに小突かれる。アルジの管理はケライに一任されている。アルジの更生を依頼しよう，と考えた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
