#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 151

  マッパは医務室で寝ていたショムとオヤブンをたたき起こし，湿原が消滅したことを伝えた。その言葉に，マッパについてきたボッチらの顔が凍りつく。さらにその被害は拡大する一方で，やがて里にも迫るだろうとのことだった。

  「モンスターか」オヤブンが聞く。「たぶんな。確証はないが」「詳しく説明してほしい」マッパの答えにかぶせるようにボッチが聞いてくる。だがマッパは「わからん。捉えどころがないやつだ」としか言えない。

  マッパは自分の知る範囲で話をした。クビワらと湿原のキャンプまで退却するなかで，マッパは長い首を持つ真っ黒な何かに追いかけられているのに気づいた。ただ，それをシッショらに伝えれば混乱するため，シッショに決して振り返らないよう告げたのだ。キャンプにたどりつく頃にはその姿は消えていたが，そこから見下ろすと，湿原だった大地のすべてが黒い泥に飲み込まれていた。

  捉えどころがない，とは，どこまでがモンスターの仕業で，どこまでが自然災害なのかがわからない，ということだ。たとえば調査隊を襲った地震とも関係があるのか。あのモンスターは地震をきっかけに現れたのか，もしくは地震さえも起こせるのか，といったように疑問が次から次へとわいてくる。それにひきかえ，真実を明らかにするには情報の量もそれを分析する時間も足りない。

  「それは突然現れたんですか，予兆みたいなものもなく」アルジが口をはさんだ。「それって何だ」「地面が飲み込まれる，というやつです」「どうだろうな。ここから火山に行くときにはなかったからな」「火山？」

  アルジの言葉で思い出したように，マッパは次の目的地が決まったと伝えた。こんな状況で話すのは場違いかもしれないが，話さなくてはいけないことは山ほどある。そしてマッパが東の大穴について切り出すと，ボッチが食いついた。「それって俺たちが見つけたやつと同じかもしれない」

  マッパが「知っているのか？」と聞くと，「ボクも知っているよ。ボッチ君が東の森を捜索していて見つけたんだ」とオヤブンが代わりに答える。「底の見えない大穴に，心臓が脈打つような音が響いているそうじゃないか。ボクも面白く聞かせてもらったよ」

  「入ったのか？」マッパが尋ね，ボッチが「いえ」と否定する。役立たずが，とマッパが悪態をついた。すぐにシンキがボッチの腰をなで，なだめる。

  話せば話すほど疑問が生じる。「どうしてマッパさんはそこに大穴があるって知ってるんですか」「地図に書かれていたからな」「地図？」「秘密の地図だ」

  「…観測省のものか？」アルジとマッパのやりとりにボッチが割って入る。その言葉にアルジの顔が険しくなる。

  「観測省って？マッパさん，観測省の地図持ってるの？」何も知らないシンキが聞く。「ああ。俺は観測省の一員だったからな」

  場が騒然となる。と，「そうなの？すっごーい!」とシンキだけが大騒ぎだった。「何がだ」「観測省って超一流の天才しか入れないんでしょ？マッパさんそんな天才だったんだ!」「悪かったな，俺がバカで」「いえ，そんなつもりで言ったんじゃないんですけど，でもそんな頭よさそうに見えなくて」「シンキさんその言い方は失礼です…」興奮するシンキをミミがいさめる。

  「でもどうして観測省が北の大陸の地図を持ってるんですか？血の嵐が終わってようやくあたしたちが調査に入ったんじゃ」

  マッパが大きくため息をつく。これから何度同じことを説明しなければならないのだろう。そんな気持ちはつゆしらず，シンキは笑顔のまま疑問符を浮かべた。そんなマッパに助け船を出したのは意外にもボッチだった。「シンキ，俺も黙っていたことがある。あとで話すから，今は里の対応を優先しよう」そうマッパの思惑を翻訳し，シンキの好奇心を後回しにした。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
