#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 158

  ケライの言葉に医務室が急に色めき立つ。

  「どうして早く言わないんだ」オヤブンがアルジを責める。なぜアルジは口を開かなかったのか。発言の許可をショムに依存していたからだ。ショムに目を向けると，申し訳なさそうに頭を下げる。

  藁にもすがる思い，とはこのことだが，全員の期待を一身にあびるアルジは，順を追って説明するはずだったのをケライがすっ飛ばしてしまったため，どう話せばいいのか迷う。

  するとアルジの肩がぽんぽんと叩かれた。ケライだ。顔を向けるアルジの前に書類を見せ，その一箇所を指差す。

  「アルジさん，ここですよ」そこには色のついた下線が引かれていた。混乱したときのため，事前に見出しを複数の色で分けてあったのだ。字が読めなくても，今がどこなのか把握できる。

  アルジさん，ここですよ。アルジはその優しい言葉を何度も思い返した。ケライは言われたことをしただけだが，その言葉はアルジの頭の隅から隅まで行き渡り，勇気をもたらした。

  「土蜘蛛が虚凧と同じなら，倒せると思います」アルジはオヤブンを見て言った。「どうするんだ」横からマッパが聞く。「でも，土蜘蛛が進出した領域には，二度と足を踏み入れることはできないかもしれません。それでもいいですか」

  アルジは自分の言葉で，山の頂上から見た海を思い出した。あの海は今はなき草原の先にある。だが，アルジが考える方法で土蜘蛛を倒せば，もはやそこへたどりつくことはかなわないだろう。いや，土蜘蛛がいるかぎり，いずれにせよその海を目の前でながめることはできないのだ。

  マッパは「とりあえず言ってみろ」と促す。ふっとアルジはボッチの目を見て口を開こうとした。ボッチが何かに気づいたように目を見開き，「あ」と声を出す。

  ボッチは驚いた顔で全員を見回し，そうか，と呟く。「何だ」マッパがやや苛立ち，話を進めるよう急かす。ボッチもわかったか。アルジは確信を持った目でボッチを見つめる。その眼差しにアルジもうなずいた。

  「黒い霧を使うんだな」「はい」

  それは二人だけの暗号のように聞こえ，周囲ははじめ何を言っているのかわからなかった。だがすぐにショムはわかり，その口から全員に説明する。

  ボッチたちが森の東で遭遇した，人を喰う霧。アルジが蝕霧ディエボラン，と呼んでいたものだった。昼は空気に紛れ大人しくしているものの，夜の訪れとともに本性を表し，全ての肉を食らいつくす，恐るべき細菌である。虚凧のような皮膚の柔らかいモンスターならば，その表皮から侵食し，みるみるうちに増殖しながら肉体を跡形もなく消し去るだろう。それは土蜘蛛であろうと例外ではない。

  問題は，蝕霧はエサを食いつくしたあともその場に留まりつづけるであろう，ということだ。言い換えれば，土蜘蛛が侵食した場所すべてが，蝕霧に覆われることになる。風向き如何では，その範囲をさらに拡大することになる。下手をすれば，土蜘蛛以上の脅威にもなるかもしれない。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
