#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 158

  ケライの言葉に医務室が急に色めき立つ。

  「どうしてそれを早く言わないんだ」オヤブンがアルジを責める。なぜアルジは黙っていたのか。発言の許可をショムに依存していたからだ。ショムはアルジと目が合うと，申し訳なさそうに頭を下げる。

  藁にもすがる思い，とはこのことだが，全員の期待を一身にあびるアルジは，順を追って説明するはずだったのをケライがすっ飛ばしてしまったため，どう話せばいいのか迷う。

  するとアルジの肩がぽんぽんと叩かれた。ケライだ。アルジの前に書類を見せ，その一箇所を指差す。

  「アルジさん，ここですよ」そこには色のついた下線が引かれていた。混乱したときのため，事前に見出しを複数の色で分けてあったのだ。どこまで話したか忘れても，色を見れば思い出せる。字が読めなくても筋の通った話ができるようにする工夫だった。

  アルジさん，ここですよ。アルジはその優しい言葉を何度も思い返した。ケライは言われたことをしただけだが，その言葉はアルジの頭の隅から隅まで行き渡り，勇気を与えた。

  「土蜘蛛が虚凧と同じなら，倒せると思います」アルジはオヤブンを見て言った。「どうするんだ」横からマッパが聞く。アルジはその問いには答えず，「でも，土蜘蛛が進出した地域には，二度と足を踏み入れることはできないかもしれません。それでもいいですか」と話を続けた。いちいち応答していたらまた忘れてしまうからだ。

  そのときアルジは，山の頂上で見た海の様子を思い出していた。あの海は今はなき草原の先にある。だが，アルジが考える方法で土蜘蛛を倒せば，もはやそこへたどりつくことはかなわないだろう。いや，土蜘蛛がいるかぎりは，どんな形であれその海を間近で見ることはできない。

  マッパは「とりあえず言ってみろ」と促す。オヤブンもうなずく。アルジはボッチの目を見て，それから口を開こうとした。

  「あ」アルジの視線から，ボッチは何かに気づいたように目を見開き，思わず声を出してしまう。

  ボッチは驚いた顔で全員を見回し，そうか，そうだ，と呟きながらも，話すのをためらうように，いや，それはさすがに，と一人芝居をする。「何だ」マッパがやや苛立ち，話を進めるよう急かす。

  ボッチはアルジの顔をうかがった。ボッチも気づいたか。アルジはまっすぐな眼差しを向ける。ボッチはうなずくと，答えを言った。

  「黒い霧を使うんだな」「はい」

  それは二人だけの暗号のように聞こえ，周囲ははじめ何を言っているのかわからなかった。だがすぐにショムはわかり，ボッチが気づいたときと全く同じような反応をする。連想ゲームのような滑稽な状況のなか，ショムが決着をつけるべく，その口から全員に説明する。

  ボッチたちが森の東で遭遇した，人を喰う霧。それがボッチが黒い霧と呼び，かつてアルジが蝕霧ディエボラン，と勝手に名づけたものだった。昼は空気に紛れ大人しくしているものの，夜の訪れとともに本性を表し，全ての肉を食らいつくす，恐るべき細菌である。虚凧のような皮膚の柔らかいモンスターならば，その表皮から侵食し，みるみるうちに増殖しながら肉体を跡形もなく消し去るだろう。それは土蜘蛛であろうと例外ではない。

  問題は，蝕霧はエサを食いつくしたあともその場に留まりつづけるであろう，ということだ。言い換えれば，土蜘蛛が侵食した場所すべてが，蝕霧に覆われることになる。風向き如何では，その範囲をさらに拡大することになる。下手をすれば，土蜘蛛以上の脅威にもなるかもしれない。本来なら十分な検証が必要な考えだった。

  もっと時間があれば，こんなに追いつめられる前に，大穴の調査が行えていたかもしれない。それに，もっと時間があれば，蝕霧を無効化する薬だって開発できていたかもしれない。そしてもっと時間があれば，地震にも耐えうる頑丈な設備だって構築できたかもしれない。

  もっと時間があれば。この場の誰もが思っていることだった。ただそれなら，過去，漫然と調査をさせ，時間と資源を空費してきたオヤブンに責任がある。その怠慢がもたらした罪は，今，正しい選択で全員を導き，その命を救うことで償うしかない。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
