#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 159

  「僕はそいつをあるべき姿に返してやりたい」

  沈黙を破ったのはシッショだった。「あるべき姿に返すって，ボッチが言った方法でか」マッパが聞く。ボッチの言った方法，という言葉にアルジがひっかかるものがあったが，事態はアルジにとって意図せず都合の良いものになった。蝕霧を使うという方法は，アルジが先に思いついたものとはいえ，ボッチの口から出た考えである。もし失敗してもアルジだけの責任にはならなくなるのだ。

  「どんな方法でもいい。あいつはこの世界にいるべきじゃない。楽にさせてあげよう」その言葉には，クビワの家族を思う気持ちがこめられていた。

  「まるで痛みを知っているかのような言い方だな」「わかるよ。自分の望まない形で無理矢理生きのびさせられることが，どれほどつらいか」

  その言葉には重みがあった。シッショは調査隊に入る前，そうしたものを直接見てきたのだから。

  「でも，その，なんだっけ」オヤブンが口を開く。「土蜘蛛です」「そいつを倒したあと，人喰い霧とかいうやつのほうが危なくなるかもしれないんだろ？」ショムの補助を受け，オヤブンはシッショに蝕霧の危険性を訴えた。まだ決断を迷っている。

  シッショの瞳には苛立ちが宿っていた。心を落ち着けるように息をし，自分の考えを述べる。「竜人や，人間は，壊すのがうまい。守ろうとしたものさえ壊す。その霧は敵を殺すために使う。だから僕たちに牙を向けることはない」

  「何を言ってるんだ？」シッショの不可解な言葉にオヤブンが問う。それはここにいる誰もが思ったことでもある。

  「昔，獣人が築いていた砂漠の街に賊がやってきた。竜人たちは賊から街を守るために軍を送った。その軍は何をした？」

  「…街の住人から略奪をしたんですね」ショムの言葉にシッショがうなずく。賊と戦うなんて危険なことをするより，手軽に報酬にありつけるからだ。「他にもある。東方の部族が飢えに苦しんでいるから，人間は自分たちが食べている穀物を育てさせた。そうしたら，その作物は全ての地力を吸いつくし，いっそう飢餓が進んだ」その土地の特性を理解していなかったからだ。「南方の希少な種を保護しようと運動を起こしたら，かえって密猟が進んで絶滅した」希少な生物は高い価値があるからだ。

  シッショは自分が獣人であることをいいことに，ここで不満をぶちまけて何が言いたいのだろうか。「守ろうとするほど竜人や人間は壊してしまう。けれども狙ったものを壊す力だけなら一流だ。ここで四十三の氏族を一人残らず根絶やしにしたようにね」その言葉に，アルジはめらめらと沸き立つような血の高ぶりをおぼえる。喧嘩を売っているのか？

  「もしその霧を，里を守るために使おうとしていたのだったら，使い方を誤って，いずれそいつは僕らを殺すことになっただろう。でもアルジやボッチは，その，土蜘蛛を倒すために使うことを選んだ。だからうまくいくと思う。人間の，壊す能力は一流だから」

  「よ，要するに，土蜘蛛を退治するために蝕霧を使うのは，安全だってことですよね？」険悪な空気をかき消すため，ショムが明るい声でまとめる。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
