#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 159

  「僕はそいつをあるべき姿に返してやりたい」

  沈黙を破ったのはシッショだった。「あるべき姿に返すって，ボッチが言った方法でか」マッパが聞く。ボッチの言った方法，という言葉にアルジがひっかかるものがあったが，事態はアルジにとって意図せず都合の良いものになった。蝕霧を使うという考えは，アルジが先に思いついたものとはいえ，ボッチの口から出たものである。もし失敗してもアルジだけの責任にはならなくて済むからだ。

  「どんな方法でもいい。あいつはこの世界にいるべきじゃない。楽にさせてあげよう」その言葉には，クビワの家族をこれ以上辱めたくない思いが込められていた。

  「まるで痛みを知っているかのような言い方だな」「わかるよ。自分の望まない形で無理矢理生きのびさせられることが，どれほどつらいか」

  その言葉には重みがあった。シッショは調査隊に入る前，そうしたものを直接見てきたのだから。

  「でも，その，なんだっけ」「土蜘蛛ですか」オヤブンが口を開き，ショムが補う。「そう。そいつを倒したあと，人喰い霧とかいうやつのほうが危なくなるかもしれないんだろ？」

  オヤブンはまだ決断しきれず，シッショに蝕霧の危険性を訴えた。それはまるで，もしものときに非難するための口実にしようとするかのようだ。ボクはあのとき危ないと言った。それでも押し切ったシッショが悪い，と。

  シッショの瞳には臆病なオヤブンへの苛立ちが宿っていた。心を落ち着けるように息をし，自分の考えを述べる。「竜人や，人間は，壊すのがうまい。守ろうとしたものさえ壊す。その霧は敵を殺すために使う。だから僕たちに牙を向けることはない」

  「何を言ってるんだ？」シッショの不可解な言葉にオヤブンが問う。それはここにいる誰もが思ったことでもある。

  「昔，獣人が築いていた砂漠の街に賊がやってきた。竜人たちは賊から街を守るために軍を送った。その軍は何をした？」

  「…街の住人から略奪をしたんですね」ショムの言葉にシッショがうなずく。賊と戦うなんて危険なことをするより，手軽に報酬にありつけるからだ。「他にもある。東方の部族が飢えに苦しんでいるから，人間は自分たちが食べている穀物を育てさせた。そうしたら，その穀物は全ての地力を吸いつくし，いっそう飢餓が進んだ」その土地の特性を理解していなかったからだ。「南方の希少な種を保護しようと運動を起こしたら，かえって密猟が進んで絶滅した」希少な生物は高い価値があるからだ。

  シッショは自分が獣人であることをいいことに，ここで不満をぶちまけて何が言いたいのだろうか。「守ろうとするほど竜人や人間は壊してしまう。けれども狙ったものを壊す力だけなら一流だ。ここで四十三の氏族を一人残らず根絶やしにしたようにね」その言葉に，アルジはめらめらと沸き立つような血の高ぶりをおぼえる。喧嘩を売っているのか？

  「もしその霧を，里を守るために使おうとしていたのだったら，使い方を誤って，いずれそいつは僕らを殺すことになっただろう。でもアルジやボッチは，その，土蜘蛛を倒すために使うことを選んだ。だからうまくいくと思う。人間が壊す才能は一流だから」

  「よ，要するに，土蜘蛛を退治するために蝕霧を使うのは，安全だってことですよね？」険悪な空気をかき消すため，ショムが明るい声でまとめようとする。

  <br>

  「どうして安全なのかわからないんですが」

  迷いのない澄んだ声が響いた。ケライだった。あとはオヤブンの了承をとって計画を実行にうつすだけだったのに。余計なことを，とショムは心の中で舌打ちする。

  「今のシッショさんの発言に安全性を裏付ける証拠はありません。それで安全だというのは論理的に破綻しています」「別に論理的に納得させるつもりなんかない」「別にって何ですか。本題があるんですか」「そんなものないよ。僕の妄想だと勝手に思ってくれればいい」「里の責任者が集まる重要な会議で妄想で話を進めようとしていたんですか。それで結論を出そうとしているんですか」

  「安全だなんて根拠はどこにもない」ボッチが口論に加わった。「根拠がなくても決断しなきゃいけないときがあるんだ。今みたいにな」

  「根拠の有無に関わらず，決断するのはオヤブンさんの仕事じゃないんですか。そこにシッショさんの話を入れる必要はないと思います」

  そう。その通りだ。オヤブンが煮えきらない態度だからシッショが私見を述べる事態になって，さらにケライが文句を言うことでより混乱した状況になっている。

  「要するに，お前が早く決断して，全部の責任を取れってことだ」マッパがオヤブンの方に顔だけ向けて言った。「霧を使わないなら使わないで，それで今後生じる被害の責任を全て取れ。使うなら使ったで，予想外の事態になってもお前が全部責任を取れ」

  ふいに，ドン!とマッパが机を叩く。

  「それで尻ぬぐいされるのは俺たちだがな!」

  場に緊張がはしる。するとマッパは別人のように穏やかな顔になり，机の手を引っ込め，話を続けた。

  「ただ，これでうまくいけば手柄は全部お前のものだ。こんな予測不能な状況で，的確な判断で隊員を救った，ってことでな」

  その言葉に，全員がオヤブンに注目する。地震が里を襲ってから，ずっとオヤブンは迷っていた。これ以上里が壊れないことを祈りつつ，一日でも長く穏やかな状況が続いて，やがて奇跡か何かが起きて全てを解決してくれることを願っていた。だがマッパの言葉で自分の立場を思い出した。自分はこの調査隊の隊長で，皆の命は自分にかかっているのだ。身勝手なアルジが来てからというもの，これまでずっと忘れていた気持ちがふつふつとよみがえってくるようだった。

  オヤブンは背中を押されたような気持ちで，まっすぐ顔を上げ宣言した。

  「蝕霧ディエボランを用いて土蜘蛛アクタニスを掃討する。全ての隊員は，ボッチの指示のもと迅速に行動するように。以上!」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
