#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 161

  本章でもストーリーに進展はない。時間を進めたい読者は飛ばしてほしい。

  アルジは嘘をついている。その言葉で食事の手は完全に止まった。「食べないと，午後もちませんよ」その原因を作ったケライは心ない言葉をかけるが，さらにその根本の原因を作ったのはアルジ自身だ。自分の口に無理矢理押し込み，水で胃に捨てると，行こう，と書庫へ誘った。

  <br>

  「あれ」作業が再開されて間もなく，アルジは書庫で身体の不調をうったえた。「どうしましたか」「なんだろう，なんか，気分が乗らない」

  大して動いてもいないのに，その顔は青ざめ，汗でびっしょり濡れている。その様子を異常に思ったケライはショムを呼ぼうとした。だが，先の施設から漂う殺伐とした雰囲気にケライを送るのは危険だ。ゆえに祈るような声でケライに書庫に留まってくれるよう頼んだ。

  席につき，汗をぬぐってもらいながらも，その息は荒い。ただ，布越しにケライの手を感じるだけで，アルジの気分は随分と楽になる。やがて目を閉じ，ケライの肩にもたれかかると，その温もりにどこか懐かしさをおぼえた。

  「私は臆病だった」ふいにアルジがつぶやいた。

  「そうですか」「昔からずっと逃げつづけていたんだ」「何からですか」「嫌なものから」

  嫌なもの。それは戦いに巻き込まれるなかで，人を死に追いやったり，仲間の死を見ることだった。怖くて仕方なかった。できなかった。だから戦わずに逃げた。それは今でも何かあるたびに逃げる，アルジの悪癖として残っている。そして過去からも逃げ，そこに蓋をした。

  記憶の釜から忌まわしい過去が絶えず蒸気のように吹きあがる。それを必死に押さえこむなかで，いつのまにか自身の見たものと伝聞が曖昧になっていた。東に出発して西から帰ってくるようなことが起きた。歪んでしまった。嘘になっていた。忘れたから歪んだのではない。意図せず思い出してしまう，そのたびに，記憶の内容が少しずつ形を変え，やがてアルジ自身も気づかない偽の思い出になってしまったのだ。

  アルジは忘れてなどいなかった。必死に忘れようと葛藤するなかで，思い出を，受け入れられるように作り変えていたのである。むしろ，血の嵐を忘れ，思い出すことさえ一度もなかったなら，その記憶は新鮮なまま保たれていただろう。そして，何かのきっかけに，その新鮮な血のしぶき，飛び散る臓物，骨の砕ける音，断末魔の叫び，憎悪，嘲り，腐敗，それらが起きたときのまま目の前に展開されたなら，アルジは狂乱の渦に飲まれ，二度と帰ってくることはできなかったはずだ。

  アルジは日記をつけない。ゆえにどこまでが事実でどこまでが嘘なのか，永久にわからない。ケライが苦労して聞きとった記録も，誤りがあるとわかれば価値はない。アルジは血の嵐で起きたことを伝えようとした。けれども自分で全ての過去を台無しにした。多くの者が倒れゆくなか，戦いもせず身を隠し，ひたすら泥棒のように生き抜いた卑怯な自分が。投降した南でさえも居場所がなく，後発隊に志願することでそこからも逃げようとした愚かな自分が。

  裏切り者!

  そうだ。裏切り者だ。自分だけ生きのびた臆病者なのだ。自分を守りたい，それだけのために，生き証人としての資格も失ってしまった。

  あのとき死んでいればよかった。そうすれば北の大陸は未踏の地として，新たな時代が幕を開けるはずだったのだ。謎と発見に満ちた，美しい場所として。

  <br>

  話を聞き終えたケライは，「本当にバカですね」とあきれるように言った。同時に，自分が関わっていながら，すぐにその嘘に気づけなかったことを反省した。アルジと付き合っていると，自分の物の見方が歪む，と文句も言った。ただ不幸中の幸いだったのは，これが世に知られる前に明らかになったことである。臆病なのを隠す，というのはアルジの生まれついての性分なのかもしれないが，いかなる手を用いても矯正しなければ，今度こそ取り返しのつかないことになるだろう。

  「私が以前，不誠実な人が嫌いと言ったのを覚えていますか」「覚えてる。忘れたくなるほどの痛みの記憶と一緒に」「アルジさんは不誠実ですね」「仰るとおりです」「皆さんに謝りましょう」「わかった」

  ケライの手がアルジの頬に触れた。「でも死んじゃダメです」「…どうして。私は裏切り者なのに」「大切な人ですから」「…ケライって時々素直になるよね」

  その手は頬を強くつねりあげた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
