#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 162

  マッパたちは森のキャンプに資材を運んだ。すぐさまシッショとキセイは新たな資材を輸送するため，獣車で里へ引き返す。マッパは川向こうにテントを設営するため案内役にボッチを連れてキャンプを出た。留守番のクビワは暇なのでキバとツメとともに遊びに行ってしまい，シンキは暇な時間を過ごしている。

  自分から進んで一人になることはよくあったが，周囲の事情で一人ぼっちにされると，途端に寂しさがおしよせてくる。おまけにこのキャンプは自分にとって忘れられない悪夢を思い出させるのだ。ボッチは自分を危険なめに合わせないためにクビワを護衛に残したのだろうが，自分もボッチたちと行きたかった。

  今では皆に明るく振る舞っているが，それは一人でいたくないからだ。明るくしていれば，友達ができる。けれどもいつでも誰かに気を配っているのはあまり楽しくない。調子が悪くても里の変わり者たちをまとめるためにカラ元気を振り絞るのははっきりいって疲れる。それでも里の人たちが笑顔でいられると，少し救われたような気になる。

  昔はもっと大人しい性格だった。いや，今でもきっとそれは変わらない。裁縫が好きだった。嫌なことがあっても，何も考えずに手を動かしていると，どんどん模様ができあがっていく。それで，他の子の服よりもちょっぴりお洒落な，自分だけの服を着て，特別な気持ちになっていた。

  幼い頃，村に変わった子供がいた。よく泣き，ケンカも弱い。ただ何でも知っていた。天の星は決まった場所に並んでいるから，その模様を覚えれば自分がどこを向いているかがわかるのだと言った。虫は順番に大人になるから時期によって鳴き声が違うのだと言った。

  その後，戦火に巻き込まれ，その子とは二度と会うことはなかった。やがて都でボッチに会った。弱虫だが強がりで，物知りなのが，その子に似ていた。

  クビワが帰ってきた。泥だらけな身体で座ろうとするので，外で落としてくるように言う。空腹をうったえるので積んできたばかりの食料を見繕って渡した。

  シンキは口には出していないが，クビワが苦手だ。いや，おそらく他にもクビワと話すのが苦手な者はいるだろう。アルジやシッショはどうしてこんな獣のような人間とまともに話せるのだろうか。こんなこと，もしシッショに知られればただでは済まないが，恐ろしくないのだろうか，こんな子供のような知能で，すさまじい力を秘めた怪物が。

  制御できるとでも思っているのか？

  会話をしようにも，淡白な返事ばかりで話題が広がらない。まあ，もともと話すのは得意じゃないから仕方ないのかもしれないが。それにクビワもシンキがあまり自分を好いていないことをわかっているようで，食べ終わるとすぐに丸まって眠りはじめた。シッショなら毛布をかけるのだろうが，自分がやればおそらく敵襲だと誤解されてしまうだろう。

  どうしてボッチは自分を置いてけぼりにしたのだろうか。そのことを愚痴るつもりはないが不満であった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
