#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 163

  ボッチはマッパとともに川を渡り，設営予定の場所を目指していた。マッパは先ほど通りすぎた穏やかな川が夜には黒く染まるとは俄には信じられなかった。それに土蜘蛛がここまでたどりつけば，勝手に霧が倒してくれるのではないか，と疑問を述べた。

  「蝕霧が活動を始めるのは夜だから，それまでに土蜘蛛に飲まれたら何の意味もない」

  マッパの問いにボッチが答えた。この地には真夜がないこともあり，蝕霧が正体を現す時間はそれほど長くない。ゆえに，川の蝕霧に土蜘蛛の討伐を任せる，という賭けは分が悪い。もし一日中霧が立ちこめていたのであれば，アルジも自分も土蜘蛛を放っておいただろう。

  マッパは不要な戦いを避けるため，森に入ったことはほとんどない。珍しく，ボッチのほうが滞りなく進んでいくのを，マッパがところどころでひっかかりながら追いかけるような状態になった。手間取るマッパを見たことのないボッチはやや得意気であった。

  とはいえ，そんな余裕でいられる時間はそう長く続かない。ボッチが急に立ち止まる。

  「何だ」マッパが隣に立って問う。「迷ったのか？」

  「おかしい」「おかしいのはお前の記憶だろう」「道が消えている」「なに？」

  無言でボッチが武器を構える。柄の長いピッケル状の武器，戈 (か) だ。マッパもそれに合わせ，しぶしぶと大槌を手に持つと，全身の感覚を研ぎ澄ませる。

  地面には見覚えがある。ボッチはさほど森を歩くのに慣れていないとはいえ，一度歩いた場所を忘れるほどではない。それにも関わらず，開けていたはずの獣道が，まるで以前から無かったように塞がれている。ボッチは下ろしていたフードを頭まで被り，聴覚が鈍くなるのを犠牲にしてでも頭部を守った。後退するよう，手でマッパに合図を送る。何に狙われているのかは明らかだ。

  楠蜘蛛，アルジが虚凧と呼んでいたものである。仲間が二匹，もしくは二人，やられたことを忘れていないのだ。いずれやってきたときのため，バリケードを張って対抗するつもりだったのだろう。そしてまんまとマッパとボッチの二人がやってきたわけだ。復讐を果たすいい機会だった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
