#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 165

  シッショとキセイが獣車に乗って森のキャンプに戻ってきた。今日運ぶ分はこれで終わりだ。夕食の準備に取りかかるため，キャンプの奥で一人座りこむシンキを呼ぶ。シンキはのそのそと出てきて手伝おうとするが，いつもの元気な様子ではない。

  「シンキ，何かあったの？」シッショが気になってたずねる。シンキはすぐには答えず，手を動かしながら何か迷っているようであった。「シンキ」シッショは優しく言い，シンキの心配を打ち明けるよう促す。

  「シッショさん，あたしクビワを怒らせたかもしれない」

  その言葉に一瞬シッショの手が止まり，キャンプの中にクビワがいなかったことを思い出す。だが間もなく元の表情に戻り，「何かあったか知らないけど，もうすぐご飯だし，すぐに戻ってくると思うよ」とシンキを安心させるように言った。

  その日の夕食には，クビワの好きな香りのするスパイスを多めに入れた。

  <br>

  クビワは戻ってこなかった。シンキの顔は暗い。シッショはシンキの向かい側に座ったまま，火を眺めている。それがシンキにとっては無言の怒りを表しているように感じられ，つらかった。

  シッショがわずかに動く，と，その口が開く前に「シッショさんごめんなさい」とシンキが謝った。謝らせるつもりなどなかったのだが。シッショは姿勢を直し，「何があったのか言ってくれる？」と説明を求める。ついつい尋問口調になってしまうことを詫びながら。

  シンキにもどうしてクビワがいなくなったのかわからない。

  ボッチが心配になったシンキは，置き手紙を残して川の向こうへ行こうと考えた。そのうえで，どう川を渡るかが問題になった。船は一艘しか用意しておらず，それはボッチたちが向こう岸に残したままにしてあるはずだからだ。そこで怪力のクビワに泳いで自分を運んでもらうことを考えた。昼寝から覚めたクビワにそれを伝えると，暇なクビワもはじめは乗り気だった。だが，川向こうでボッチを見つけるにはクビワの鼻が頼りだ，と伝えた途端，急に暴れ出し，シンキが止めるのを振り切ってどこかへ行ってしまったのだ。

  話を聞くかぎり，シンキに非はないように思える。シッショは気にしないよう言い，クビワを探しに出た。キバとツメの姿もないから，クビワについて行ったのだろう。

  地面に鼻を近づけ，わずかなにおいを嗅ぎ取ろうとする。シッショは人よりは鼻がいい。はじめに感じたのはキバとツメ，すなわち裂掌獣のにおいだ。強い体臭は居場所を知らせ，無用な争いを防ぐことができる。

  ぬかるんだ土に足跡を見つける。シッショはクビワの好きな香草を手でもみながら，においにつられて出てくるのを願う。

  <br>

  「クビワ」

  斜面の盛り上がった土，その影から裂掌獣の尻尾がのぞいている。回り込むように進むと，うずくまるクビワ，その顔をなめるツメ，後ろ足で自分の顔を掻くキバの姿があった。

  「クビワ」再度呼びかける。だが返事はない。「帰ろう」「やだ」「どうして」「かえらない」

  「シンキに何かひどいこと言われたの？」クビワは顔を横に振る。シッショはクビワの隣に座ってその顔をなでる。クビワはそのままシッショに抱きつき，いかないで，と泣き出した。「僕はどこへも行かないよ」そう言って震える背中に腕を回し，ゆっくりとその背をトントンとたたいてやった。

  <br>

  シッショが持ってきた食料を，鼻をすすりながらクビワは食べる。キバとツメは一瞬でたいらげてしまい，足りない様子だ。帰ってから食べさせてやろう。

  「どうしてこんなところまで来たの？」

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
