#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 165

  シッショとキセイが獣車に乗って森のキャンプに戻ってきた。今日運ぶ分はこれで終わりだ。夕食の準備に取りかかるため，キャンプの奥で一人座りこむシンキを呼ぶ。シンキはのそのそと出てきて手伝おうとするが，いつもの元気な様子ではない。

  「シンキ，何かあったの？」シッショが気になってたずねる。シンキはすぐには答えず，目を泳がせながら何か迷っているようであった。「シンキ」シッショは優しく言い，シンキの心配を打ち明けるよう促す。

  「シッショさん，あたしクビワを怒らせたかもしれない」

  その言葉に一瞬シッショの手が止まり，キャンプの中にクビワがいなかったことを思い出す。だが間もなく元の表情に戻り，「何かあったか知らないけど，もうすぐご飯だし，すぐに戻ってくると思うよ」とシンキを安心させるように言った。

  その日の夕食には，クビワの好きな香りのするスパイスを多めに入れた。

  <br>

  クビワは戻ってこなかった。シンキの顔は暗い。シッショはシンキの向かい側に座ったまま，焚き火の穏やかにゆらめく様子を眺めている。何かを待っている。それがシンキにとっては無言の怒りを表しているように感じられ，つらかった。

  シッショがわずかに動く，と，その口が開く前に「シッショさんごめんなさい」とシンキが謝った。謝らせるつもりなどなかったのだが。ただ，都合は良い。シッショは姿勢を直し，「何があったのか言ってくれる？」と説明を求める。ついつい尋問口調になってしまうことを詫びながら。

  シンキにもどうしてクビワがいなくなったのかわからない。

  ボッチが心配になったシンキは，置き手紙を残して川の向こうへ行こうと考えた。そのうえで，どう川を渡るかが問題になった。船は一艘しか用意しておらず，それはボッチたちが向こう岸に残したままにしてあるからだ。そこで怪力のクビワに泳いで自分を運んでもらうことを考えた。昼寝から覚めたクビワにそれを伝えると，暇なクビワもはじめは乗り気だった。だが，川向こうでボッチを見つけるにはクビワの鼻が頼りだ，と伝えた途端，急に暴れ出し，シンキが止めるのを振り切ってどこかへ行ってしまったのだ。

  話を聞くかぎり，シンキに非はないように思える。シッショは気にしないよう言い，クビワを探しに出た。キバとツメの姿もないから，クビワについて行ったのだろう。

  地面に鼻を近づけ，わずかなにおいを嗅ぎ取ろうとする。シッショは人よりは鼻がいい。はじめに感じたのはキバとツメ，すなわち裂掌獣のにおいだ。強い体臭は森の中で自分の居場所を知らせ，無用な争いを防ぐことができる。

  ぬかるんだ土に足跡を見つける。シッショはクビワの好きな香草を手でもみながら，においにつられて出てくるのを願う。

  <br>

  「クビワ」

  斜面に土の盛り上がった場所がある。その影から裂掌獣の尻尾がのぞいていた。回り込むように進むと，案の定，うずくまるクビワの姿があった。先ほどまで泣いていたのか，ツメがクビワの顔をなめている。キバは後ろ足で自分の顔を掻いていた。

  「クビワ」再度呼びかける。だが返事はない。「帰ろう」「やだ」「どうして」「かえらない」

  「シンキに何かひどいこと言われたの？」クビワは顔を横に振る。シッショはクビワの隣に座ってその顔をなでる。クビワはそのままシッショに抱きつき，いかないで，と泣き出した。「僕はどこへも行かないよ」そう言って震える背中に腕を回し，ゆっくりとその背をトントンとたたいてやった。

  <br>

  シッショが持ってきた食料を，鼻をすすりながらクビワは食べる。キバとツメは一瞬でたいらげてしまい，足りない様子だ。帰ったら好きなだけ食べさせてやろう。

  「どうしてこんなところまで来たの？」「いきたくないから」「川の向こうに？」クビワはうなずく。「どうして」「もりがあるから」「森？クビワは行ったことがあるの？」クビワは顔を横に振る。「シンキがいった」

  シンキの証言には誤りがあった。クビワが暴れたのは，川の向こうに森があることを言ったからだ。

  「その森にはクビワの兄弟がいるの？」クビワは顔を横に振る。「きょうだいはみんなしんだ。でもなかまがいる」

  そういうことだったのか。シッショは森に虚凧がいることを知らなかった。もっとアルジから話を聞いておくべきだった。アルジはこのことを知っているのか。いや，むしろクビワは自分に隠しておきたかったのかもしれない。シッショと会う前に，クビワたちの仲間だった者が，やがて調査隊の前に立ちはだかる敵になることを。

  「もしかして，あの宿営地にも来たくなかった？」「どこだそれ」「昨日，みんなで寝たところだよ」

  クビワはためらうように少し時間を置いて，うなずく。森のキャンプはその名のとおり，キャンプから森を見下ろすことができる。一度，シッショを救うために，そこへ足を踏み入れた。だが，いつかそこへまた行くことがあるのではないかと，クビワは気が気でなかったかもしれない。

  「でもシッショがいくっていったから」最後まで言わせず，シッショはクビワを強く抱きしめた。「ごめんよクビワ。僕のせいだ。絶対クビワを森には行かせないから」

  動かないシッショの片腕を見ながら，クビワは残った腕から伝わる力と，自分を大事に思う気持ちにほっとした。シッショの腕の毛を鼻息でなびかせながら，そのままクビワは安心したように眠りにつく。二人と二頭はそこで夜を過ごし，翌朝キャンプに帰還した。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
