#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 167

  森のキャンプが臨時の本部として機能しはじめるのも早々に，川向こうの森から引き返してきたマッパは大穴の調査に行けそうな者を選んだ。本来はシッショとクビワを同行させたかったのだが，とある事情で連れていけない。やむを得ず案内人のボッチと，それを補助するシンキに，アルジを加えた四人で出発した。

  マッパとしてはボッチ以外は数合わせとしてしか考えていない。シンキを置いていって後から勝手についてこられるのも面倒だし，アルジなら放っておいても地の果てまで勝手についてくるだろう。それなら始めから指名し，責任を自覚させたほうがよい，という判断だった。もしマッパらが出かけている間，土蜘蛛がキャンプまで迫ってくるようなことになったら，シッショに全ての指揮を委ねてある。そうならないことを祈る。

  さすがに以前の倍の人数では虚凧たちも簡単には手を出せないようだ。とはいえ，あの光る手足を持つのは仇の一人に間違いない。それがのこのこやってきたのだ。隙があれば狙い撃つ。そんな殺気が漂っていた。これでは休憩地点が作れない。もとより敵の巣のど真ん中を突っ切るというのが無茶な話なのだが，相手の数も把握できない状況で，安全を確保しながら進んでいる時間はない。

  「大穴を下って，平地があったらそこに建てよう」ボッチの提案で四人は先に進んだ。それをマッパが聞いているかは定かではないし，聞いていたところでその通りにするかどうかはわからない。いざとなればマッパが進むのを無視して休憩していれば，やむを得ずマッパもつきあうだろう。ボッチはある程度マッパの性格は把握しているつもりだった。

  シンキはお荷物かと思いきや，意外と遅れることもなくついてくる。鎧の見た目は同じだが軽量化されているのだろうか。重装に盾，という装備を変えない姿勢にアルジは多少の心配を持ったものの，虚凧に対してはまさに鉄壁の防御を誇る。仮に一斉射撃を受けたとしても無傷で生還できるところに安心感があった。いや，重装をも粉々にするほどの超重量の敵が闊歩するこの地が異常なのだといえる。

  <br>

  「そろそろだ」そう言って枝やツルをかきわけると，急に目の前が明るくなる。

  「わあ，すごい」その情景に思わずシンキが声をあげる。

  見渡す限りに広がった大穴。森，いや，この大陸のへそと言ってもいいほどの巨大な空洞が目の前にある。その周囲は木々に覆われ，気づかずに進めば落ちてしまいそうなほど，極端に風景が変わっている。まるでコケで覆われた地面をスコップで削り取ったかのようだ。

  穴へ流れこむ川が滝をつくり，やがて霧に変わりながら七色の虹を作っている。それに彩られるように，穴の中央には天辺に葉のない巨大な木が，脈打つような音をたてながら緑色の身体を日光に照らしていた。いくつもの平らな葉が幹から伸び，効率よく光を得るため，雑に作られた階段のように下へと続いている。

  「行くか」

  迷いなくマッパは近くの木にロープを巻きつけ，崖を下りて行った。シンキが盾を背負い直して続く。そしてボッチ。腕がフックになっているアルジは自力でするすると滑ってゆく。その崖から反対側の崖に視線を送った。霧でぼやける森林。あの先，またはるか先まで陸地が続いている。自分たちが訪れたのは北の大陸のごくわずかでしかない。そしてあの向こうから自分はやってきたのだ。いずれ故郷へ帰れるときが来るだろうか。

  いや，そもそも自分は帰りたいとも思っていないのかもしれない。南に居場所がないからここへ来たが，しょせん，過去の自分を知る者など誰も生きていないのだ。ふっとアルジはケライに会いたくなった。会って，また今までのように頬をつねってほしいと思った。

  と，そんなくだらないことに気をとられ，あやうく落下するところだった。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
