#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 169

  先に敵の姿をはっきりと捉えたのはアルジだった。マッパが猿と言ったのは正しい。ぎょろりとした大きな目を持つ猿。ただし，普通の猿とは明らかに違う。

  プロペラのような平たい尾。それを回転させ，あたかもヘリコプターのように自在に飛び回っているのだ。いや，正確には尾を回転させ，落下速度を穏やかにすることで横方向への移動を可能にしているのだろう。

  翅尾獣トゥントゥク。羽根のような尾からアルジはそう名づけた。それは群れをなし，覇鱗樹の実であろう球体を爆弾のように投下してくる。一方的に有利な状況を作るため，アルジたちが下に行くまで隠れていたのだろう。狡猾なやつだ。奴らを倒すには，さらに高く。

  そう思った瞬間。幹から黄色いガスが噴出し，まともにくらったアルジは空中で視界を塞がれた。

  「アルジ!」

  花粉か。いや，それはどうでもいい。強烈な悪臭。感覚を遮断されたアルジはみるみる落下してゆく。シンキは思わず片手で顔を覆った。

  ふいに放たれたフックが幹に突き刺さった。視界が封じられながら，なお身体の感覚で上下を把握したのだ。だが巻き取るのが間に合わず，その身体が弧をえがいて勢いよく幹に叩きつけられてしまう。なんとか命はつながったものの，負傷したのか，その場で動かなくなってしまった。

  シンキはボッチを守り，かつ翅尾獣の的になっているため動けない。マッパの位置からではアルジの救出にも翅尾獣に攻撃を届かせることもできない。敵の特性を理解していながら与せないことにマッパは苛立った。ならば。

  マッパは大槌を勢いよく振りかぶり，幹に打ちつけた。黄色くドロつく液体が噴き出す。二度，三度。上からしか攻撃してこない相手なら，上を無くしてしまえばいいのだ。覇鱗樹を伐りたおす。それがマッパの判断だった。

  そんなことしたら帰れなくなってしまうではないか。いや，それよりも慌てたのは翅尾獣のほうだ。侵入者を退治できたとして，自分たちの巣がなくなっては元も子もない。こんな突拍子もない行動をとる相手に混乱したのか，攻撃をやめ威嚇の咆哮をはじめた。だがそんな警告に応じるようなマッパではない。なおも剛力で覇鱗樹を抉りつづける。

  と，翅尾獣の一頭が弾け飛んだ。ひときわ大きな個体が一瞬にしてやられ，その様子に翅尾獣たちは先とは違う金切り声をあげる。

  目覚めたアルジがついに翅尾獣の高さまで達し，ボスを仕留めたのだ。マッパが注意を引く狙いだったかはわからないが，時間稼ぎには十分だった。いくら猿の木登りが得意とはいえ，ミミの努力の結晶である機動装置の性能を引き出したアルジの速さにかなうはずがない。その逃げ道を塞ぐように現れては消え，縦横無尽に暴れ回る。統制を失った翅尾獣たちはパニックに陥り，崖に空いた穴，おそらく巣だろう，そこへと次々に逃げ去ってゆく。

  やがて全ての翅尾獣が姿を消し，下りてきたアルジはボッチたちに合流した。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
