#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 171

  「油は足りてるか」「まだ十分ある」

  テントを出発した四人は，真っ暗な通路を進んでいた。連れている者が違うだけで，マッパには既視感がある。来たことがなくてもわかる。ここは観測省の研究施設なのだ。その内部構造は手にとるように把握できる。

  「痛ッ」

  鉄の山が崩れるような騒音とともに，ボッチの叫ぶ声が響いた。

  「シンキ，大丈夫か」そう言ってボッチは跪いたまま動けないシンキは壁によりかからせる。

  「ごめん，足，くじいちゃったみたい…」その足元を見ると，窪んだ穴ができている。そこに踏み入れてしまったのだろう。暗くて足の状態はわからないが，このまま立たせるのは危険だ。

  「置いてくぞ」命に支障がないからか，マッパが無慈悲な声をかける。「怪我人がいるんだぞ!」ボッチは声を荒らげて反発した。

  「シンキ，俺が背負う」そう言ってボッチはしゃがみこみ，シンキに背中を見せた。「無理だよ，重いから」

  そう。鎧を身につけた重さがかなりのものであることは，覇鱗樹の葉が大きくへこんだことからも知れる。ボッチが背負えば確実に腰を痛め，負傷者を増やすことになるのだ。

  シンキはボッチに明かりを託されたアルジを申し訳なさそうに見上げる。「ごめんね，あたし，こんなところまで足手まといで…」

  「気にしないでください。ボッチさん，どうしますか」「どうするったって，置いていけるわけがない」「アルジさん，行って。明かりがなくても，ボッチがいてくれれば，あたし，待っていられるから」

  四人を照らす明かりは，用意周到な，というか心配性のボッチが持ってきた分しかない。救急道具にしてもそうだ。それは準備が足りないといってしまえばそれまでなのだが，真夜のないこの地において，照明の優先度は低い。休憩するためのテントや食料を考えると，かさばるうえ燃料もかかる照明を全員が持ち歩くということがこれまでほとんどなかったのだ。こんな暗闇を歩くことになると事前に知らせていれば対応もできただろう。前回，火山の研究施設を訪れた際にクビワとシッショがうまく立ち回ってしまったことが仇となった。

  「大丈夫ですか。本当に暗いですよ」アルジがシンキに問う。「平気だよ。でしょ，ボッチ」その言葉にボッチが一瞬怯む。が，シンキの手前，弱音は吐けず，「ああ」とうなずいた。

  「絶対帰ってきてね」そうアルジと約束した。

  <br>

  アルジは明かりで前方を照らしながら，マッパの後をついて行く。こんな同じような風景を迷いもせず歩いていけるのが不思議で仕方なかった。

  「マッパさんは以前ここに来たことがあるんですか」予想以上に自分の声が響き，アルジは驚く。「ない」「それなのに迷わないんですか」「どこも似たような造りだからな」

  似たような造り，というのが，この殺風景なトンネルに皮肉を言っているようにも聞こえた。ただ，言葉に緊張する様子が感じられ，無闇に話しかけることはためらわれた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
