#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 176

  「それで，こんなケガをしたわけですか」アルジの開いた目に光を当てながら，ショムが言う。眼球そのものは傷ついていないようだ。「はい」

  森の本部に帰ったボッチたちは，早々に治療を受けた。本部を移転した意味があったというものだ。怪我をしないことが一番なので，これを喜ぶべきことかどうかはわからないが，ショムがいなければアルジの視聴覚が失われていたかもしれない。幸い，アルジはまだ耳鳴りが激しく，片耳の聴力が回復していないものの，視力を取り戻し，耳以外に頭などの後遺症がないか検査を受けていた。ボッチは両手に大きな手袋をはめ，その滑稽な様子をシンキにからかわれている。

  そんな二人の様子を見て，アルジはショムに首を曲げられながら質問した。「そういえばお二人はどうやってあの部屋まで来れたんですか」

  「へ？あたしたちのこと？」シンキが間の抜けたような声を出す。「はい」「そういえばアルジに返してなかったな」ボッチはアルジの言葉を受け，懐を探る。

  「返す？」二人のやりとりに，一旦ショムが手を止める。取り出せないボッチに代わってシンキが引き抜き，ボッチとアルジに見せた。「これ？」ボッチがうなずく。「そうだ」

  それは液体の入った試験管だった。

  「あ」光沢を放つ管を通して，アルジの目に，はるか遠くの光景が浮かんだ。目の前でシンキが軽く振ると，青く淡い光が生じた。

  南と北の大陸をつなげる，アルジが持っていた唯一の道具。紫針竜の襲撃を受け，全てを失ったアルジが，懐にしのばせていた，ただひとつの物。まだ手があった頃，それを振って助けを呼び，そうしてやってきたのがミミだった。

  ショムが代わりに受け取り，転がらないよう，机の本に立てかける。それをもう手に持つことはできない。あれから，本当にたくさんのことがあった。自分はずっと北の大陸にいたのではないかと思うほどに。けれどもその光が，自分がどこから来たのかを思い出させた。

  「ありがとうございます」アルジは顔を上に向け，潤んだ瞳を隠す。その様子にシンキは笑いながら，「お礼を言うのはあたしたちの方だよ。ありがと，アルジさん」と言った。

  「アルジの部屋にあったのを借りっぱなしになってたんだが，それを思い出してな。シンキがお前たちを追いかけるって言ったから，それを使って後を追ったんだ」「マッパさんのベトベトの足跡がきっちり残ってたからね」「俺は目が悪いから見えなかったが」「栄養が足りてないんだよ。もっと食べなきゃ」「余計なお世話だ」

  ショムはそんな掛け合い漫才に笑みをこぼしながら，そろそろいいですか，とアルジの顔を下げさせ，検査を続けた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
