#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 177

  オヤブンの私室は期待と疑いの空気で満たされていた。治療もそこそこに駆けつけたマッパ。ショム。アルジの要望で同席するミミとケライ。会議を回すのに欠かせないボッチ。そして全員の注目を一身にあび，恐縮するアルジ。

  紫針竜の討伐は調査隊の悲願である。南へ向かう者，北へ向かう者を見境なく粉砕する凶悪なモンスター。調査隊の目的は，未踏の地の解明から，いつの間にか紫針竜討伐の手がかりを探すことへと変わっていた。もしアルジの言うようにそれを滅ぼすことができたなら，南との連絡を経て，より充実した設備で北の大陸を調査できるようになる。日々の輸送が二頭のダモスに依存することも，信号弾という脆弱な連絡手段に頼ることもなくなるのだ。

  未だ頭痛に悩まされるアルジにとって，部屋の熱気にあてられるのは苦痛だった。だから自分を落ち着かせるためにケライを呼んだ。話し始める前に，ケライの手に持った紙切れを見ながら順番を慎重に確認する。これほど話すのは苦手ではなかったはずなのだが。

  「まず，説明する前に皆さんに確認しておきたいことがあるんですが」

  そう切り出して全員を見回す。「皆さんのなかに，紫針竜の攻撃を直接見た方はいますか」アルジの目が合う者，皆が顔を横に振る。

  「では，ケライと私が見た，紫針竜の攻撃方法から説明して，対策にうつりたいと思います」

  皆が真剣な顔でアルジを見ている。視線の槍に貫かれる心持ちがする。まるで裁判だ。

  「あの，もっと皆さん，気楽な気持ちで聞いてもらえませんか」こんな雰囲気ではとても話せなかった。

  御託はいいからさっさと話せ。そうマッパが急かそうとするのをミミが被せた。「アルジさんの言う通り，私たち，気合いが入りすぎていませんか。こんな様子ではすぐに倒れちゃいますよ。お茶でも飲みながら落ち着いて話し合いましょう。ショムさん，手伝っていただけますか」

  その呼びかけにショムは「は，はい。もちろん」と気の抜けた返事でこたえ，二人で部屋を出ていった。重苦しい空気が残る。

  「どうしてみんなこんなに怖い顔しているんだ？」

  そんな雰囲気を奇妙に思ったボッチは，表情を変えないまま素朴な疑問を呈した。どうしてってそれは。そう答えようとした誰もがハッとする。

  知らないのだ。ボッチは。いや，ボッチだけじゃない。シンキも，キセイも，シッショもクビワも，紫針竜が南との連絡を断っていることを知らない。裂掌獣と遭遇する前まで，ボッチ団は，観察や収集を続ける平和な生活を続けていた。自分たちが閉じこめられていることを伝えたら，要らぬ不安を与えることになる。だからオヤブンはボッチたちに事実を隠しつづけていた。ボッチたちからすれば，紫針竜は今でも夜空を流れる星でしかない。強力なモンスターであることは聞いているが，そんなことよりも土蜘蛛のほうがよほど危険なモンスターなのだ。

  マッパがオヤブンに目配せする。これだけ知られていたら，今さら隠す必要はない。オヤブンは調査隊が抱える状況について，ボッチに話し，そして今まで秘密にしていたことを詫びた。

  オヤブンが謝罪するとは。アルジはそんなボッチをうらやましく思った。

  とはいえ，ボッチは以前，マッパから紫針竜のことを聞いている。そのことをこれまでオヤブンに言わなかったのは，何らかの意図，たとえば不要な心配をさせないなど，があるのだろうと考慮していたからだった。自分が知っていることを打ち明けてオヤブンに恥をかかせるのはよくない。「ふむ」と腕を組み，黙って考えるそぶりをする。

  「そんなことわざわざ隠さなくてもよかったんだが，」と話しかけ，すぐに言葉を続ける。「と言いたいところだが，色々あって俺たちも度胸がすわるようになったからな。昔なら不安になっていたかもしれん。オヤブンの配慮には感謝するよ」

  それに，と言ってアルジの顔を見る。「アルジがそいつを倒してくれるんだろう？早く倒して南に帰ろう。いい加減，故郷が懐かしくなってきた」

  ボッチが少し空気を和ませたところで，ミミとショムがお茶と菓子を持ってやってきた。いい香りだ。

  「大穴で飲んだのと同じにおいがするな」とマッパがすすりながら言う。「同じ葉ですから。皆さんの休憩した場所がわかったのも，このお茶のおかげなんですよ」そう言って香りの良さをミミが自慢する。「お茶を入れたら，どこにいてもミミさん飛んできますもんね」ショムがからかうと，私に隠れてお茶会しようとしてもムダですよ，と意地悪そうにミミが微笑んだ。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
