#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 178

  会議を終え，解散した者の顔は一様に暗かった。ケライをのぞいて。ミミは提案されたとおり作業にとりかかるものの，気が進まない。ついさっきまでは和やかな雰囲気だったのに，何があったのか。

  紫針竜の攻撃は高高度からの突進である。その針のような尾が直撃すれば命はない。それは明らかだ。だが，攻撃の本体は別のところにある。抉った大地から弾丸のように放たれる無数の石つぶてだ。それは全ての生物を根絶やしにし，一瞬にして不毛の地へと変える。

  その様子を，アルジは大穴の研究所で見たものと重ねた。あれは，音ではねあがった破片を弾力のある膜に反射させ，内側にあるものすべてを虚無に帰す。もし，その中央に紫針竜がいたなら。

  アルジが挙げた紫針竜の討伐計画というのは，つまるところ，紫針竜が作り出す石つぶてを，膜を使って反射させ，直接紫針竜自身にぶつける，というものである。突拍子もないアイデアだったが，その威力を知るマッパはその有効性を見出し，計画にのった。だが，その計画を実行するには大変な問題があった。

  生贄が必要だったのである。

  すなわち，誰かが紫針竜の元まで膜を運ばなければならない。その者は紫針竜を倒すのと引き換えに犠牲になる。しかもそれはあくまでも計画が上手くいった場合であって，無数の石つぶてをものともしないほど紫針竜が頑丈であれば，犠牲も無駄になるだけだ。

  ここへ来て，アルジの気づかないところに隠されていた悪癖が露になった。まさに血の嵐の亡霊であった。誰かの命を犠牲にすることに，何のためらいも感じないのだ。アルジが最も嫌悪していたはずのものは，アルジの根幹に深く染みついていたのである。生贄の必要性をボッチが指摘するまで，アルジ自身も全く自覚していなかったところにその深刻さがうかがえる。

  自分がその役をする。もしそこでアルジが真っ先に名乗り出ていたら，少しは変わったかもしれない。ただ，その刹那，ダモスや，ジブーや，ビュンの姿が浮かんでしまった。そしてあまりにも卑劣な自分に気づき情けなくなった。アルジは，一瞬であれ，ダモスたちが人間ではないから，ただそれだけの理由で身代わりにしようと考えてしまったのだ。かけがえのない調査隊の一員を，自分は意識しないところで見下していた。なんとおぞましいことか。自分の考えていることは竜人と同じではないか。誰一人欠けても調査隊はここまで来ることができなかったのに。それなのに。

  アルジはそれ以上話をすることができなくなってしまった。話が進まなくなったので，詳細は今後の課題ということにして，オヤブンとマッパを残し，会議は終わった。

  犠牲さえなければその計画は試す価値のあるものである。ミミはショムとともに，その膜を調べ，場合によっては再利用する可能性も視野に入れ，作業をすることになった。ただ，自分たちが死装束を作っているかのような気分の悪さをおぼえた。

  最も困ったのはオヤブンである。隊員たちが，入れ替わりたちかわり，自分をその役に，と訴えてくる。皆を思う隊員たちの気持ちを嬉しく思う反面，誰かの犠牲を強いろうとする里，あえて里と言おう，その雰囲気に対する違和感もあった。まだ誰かが生贄になると決まったわけではないのに，自己犠牲という甘美な響きは，こうも容易に人を魅了し，狂わせるものなのだろうか。

  どうしてアルジが自分を使えとはじめに言わなかったのか，と多少恨んでもいた。はっきりいえば，南へ帰還する計画がたった今，もはやアルジは用済みである。それに，どこか死に場所を求めているようなその生き方は，同時に，常に誰かの注目や賞賛を求め続けているようで不快だった。仮に紫針竜を討伐して南に帰ったところで，調査隊を再編成する際に雇い直すことはしないだろう。だからここでいなくなってしまっても構わない。そう思っている。ただ，オヤブンとアルジの仲が良くないことは誰もが薄々とわかっている。それでアルジを任命してしまったら，嫌いなやつを始末しようとした，と思われてしまうに違いない。そんなことで自分の信用を失いたくはない。

  ミミが膜を完成させたら，ひっそりとアルジが紫針竜の元に向かってはくれないか。今までさんざん自分の命令を無視してきたように。オヤブンはそんな淡い期待を持っていた。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
